### ISSUE TITLE
ContractNegotiationStore: add two methods to query for `ContractAgreements`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1008]
# Feature Request

Add two methods to the `ContractNegotiationStore`: 
- `Stream<ContractAgreement> getAgreementsForDefinitionId(String definitionId)`: returns all `ContractAgreement` objects that are based on a particular definition ID
- `Stream<ContractAgreement> queryAgreements(QuerySpec query)`: returns all `ContractAgreement` objects that match that query.

## Which Areas Would Be Affected?
ContractNegotiationStores based on memory, cosmos and SQL.

## Why Is the Feature Desired?
For the data management API we need to have a way to perform these queries, especially for defensive checks, e.g. a contract definition can only be deleted if no agreement exists based on it.

It's required for #969 
Depends on #979 

## Solution Proposal
in SQL this could look like this:
```sql
--assuming a prepared statement
SELECT * FROM edc_contract_agreement WHERE id LIKE '?:%'
```

## Type of Issue
feature

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
Depends on #979
