### ISSUE TITLE
Add test for sample 04.3

### ISSUE THREAD

**Issue by ouphi** [eclipse-dataspaceconnector/DataSpaceConnector#1045]
# Feature Request

Add integration tests for sample 04.3.

## Which Areas Would Be Affected?
CI

## Why Is the Feature Desired?
To avoid breaking sample 04.3. It broke in the past.

## Solution Proposal
Sample 04.3 is based on a docker-compose + commands specified in the readme.
Test running the docker-compose + the commands to make sure that the sample is not broken.

## Type of Issue
test improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by pkirch** [comment]
Reopen: start working downstream on this issue in https://github.com/agera-edc/DataSpaceConnector/issues/198 again.
