### ISSUE TITLE
SQL contract negotiation store: agreements not persisted

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-dataspaceconnector/DataSpaceConnector#1073]
# Bug Report

## Describe the Bug
When using an SQL based contract negotiation store, the agreements are never persisted during contract negotiation. After the negotiation is confirmed, the `edc_contract_agreement` tables are empty for both provider and consumer.

### Expected Behavior
Contract agreements are persisted.

### Observed Behavior
Contract agreements are not persisted.

## Steps to Reproduce
1. Exchange the in memory contract negotiation store for sample 04.0's provider and consumer with an SQL based one.
2. Add database connection properties to provider's and consumer's `config.properties`.
3. Start provider and consumer and initiate the contract negotiation as described in the README.
4. Call `curl -X GET -H 'X-Api-Key: password' "http://localhost:9191/api/control/negotiation/{UUID}/state"` and see the following response: `{"status":"CONFIRMED","contractAgreementId":null}`
5. Check the agreement tables in the Postgres instance, which are empty for both provider and consumer.

## Detailed Description
Agreement tables after the negotiation is completed:

```shell
select * from edc_contract_agreement;
 id | provider_agent_id | consumer_agent_id | signing_date | start_date | end_date | asset_id | policy_id 
----+-------------------+-------------------+--------------+------------+----------+----------+-----------
(0 rows)
```

## Possible Implementation
In the `SqlContractNegotiationStore`, the `save` method will internally call `insert` or `update`, depending on whether a negotiation with the respective ID already exists. In the `insert` method, the contract agreement is persisted. But since this is only run when the initial negotiation is persisted, the agreement is always null here. In the `update` method, neither agreement nor agreement ID of the negotiation are persisted. Therefore, the information is lost after the update.

The `update` method should also persist the agreement and the negotiation's agreement ID.

**Comment by paullatzelsperger** [comment]
i'll take a look
