### ISSUE TITLE
Implement integration test for auth-basic module

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-dataspaceconnector/DataSpaceConnector#1107]
# Feature Request

## Which Areas Would Be Affected?
`:extensions:api:auth-basic`

## Why Is the Feature Desired?
Regarding the finalization of Release 3 we decided to postpone the implementation of the integration test for the `auth-basic` module.

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
Please try to fill out the issue template properly. Almost all of the template sections were filled out insufficiently.
Also, proper milestone planning for this issue was missing.
