### ISSUE TITLE
DataManagementApi: Lack of payload check for the contract definition

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-dataspaceconnector/DataSpaceConnector#1111]
# Bug Report

## Describe the Bug
- You can create `ContractDefinitions` without any `Policy`.
- You can create `ContractDefinitions` with `Policies` which are not existing

### Expected Behavior
Throw an exception if the payload is not correct or the policies are not existing already. This should then be mapped into an 400 status code.

### Observed Behavior
The current implementation just accept the payload and generate random policy IDs if they are not provided.

## Steps to Reproduce
1. Boot up an EDC with the `DataManagementApi` module (and in my case the in-memory storage mechanism)
2. Create a `ContractDefinition` without any `Policy`:
	```shell
	$ curl -i -X POST -H 'Content-Type: application/json' --data "{
	  \"id\": \"1\",
	  \"selectorExpression\": {
	    \"criteria\": []
	  }
	}" http://localhost:9192/api/v1/data/contractdefinitions
	
	HTTP/1.1 204 No Content
	...
	```
3. Create a `ContractDefinition` with not existing `Policies`:
	```shell
	$ curl -i -X POST -H 'Content-Type: application/json' --data "{
	    \"id\": \"2\",
	    \"accessPolicyId\": \"AP_0\",
	    \"contractPolicyId\": \"CP_0\",
	    \"selectorExpression\": {
	      \"criteria\": []
	    }
	  }" http://localhost:9192/api/v1/data/contractdefinitions
	
	HTTP/1.1 204 No Content
	...
	```
4. Fetch the stored `ContractDefinition`:
	```shell
	$ curl -i -X GET http://localhost:9192/api/v1/data/contractdefinitions

	HTTP/1.1 200 OK
	...
	  
    [
      {
        "accessPolicyId": "9a979963-6df9-4e9f-a456-554a75739b33",
        "contractPolicyId": "f37ad194-752e-40ea-a427-9a023752c4dc",
        "criteria": null,
        "id": "1"
      },
      {
        "accessPolicyId": "AP_0",
        "contractPolicyId": "CP_0",
        "criteria": null,
        "id": "2"
      },
    ]
	```
5. Check that no policies have been created:
	```shell
	$ curl -i -X GET http://localhost:9192/api/v1/data/policies

	HTTP/1.1 200 OK
	...
	  
	[]
	```

## Possible Implementation

- If not all necessary fields are provided in the payload: return 400
- Check relationships:
	- If related object doesn't exist return 400

## Context Information

- Used version: `milestone-3`
- This could maybe also happens at all the other `DataManagementApi` endpoints. I haven't check it until now.

**Comment by paullatzelsperger** [comment]
this is probably part of a wider topic, which is "strict request body validation"

**Comment by paullatzelsperger** [comment]
As a start I suggest doing two things:
- implement general object validation, e.g. using Jax-RS's [`@Valid` annotation](https://www.logicbig.com/tutorials/java-ee-tutorial/jax-rs/entity-validation.html) on the controller method.
- use a Jackson ObjectMapper that [fails on unrecognized properties](https://www.baeldung.com/jackson-deserialize-json-unknown-properties). The global one created in the `TypeManager` does *not* fail.

**Comment by MoritzKeppler** [comment]
Request body validation wouldn't solve the problem with ContractDefinitions containing non existing policies, or?
Think there should not just be a validation on API layer but also in the service that creates the contract definition. We need to protect our internal domain model independent from the API the triggered the change.

**Comment by ndr-brt** [comment]
Yes, validation should exists on two levels:
- input validation: check that the input object is valued correctly and without inconsistencies.
- domain validation: before applying the domain logic we should assure that the operation can be done against the current state.
