### ISSUE TITLE
SQL Contract Negotiation :: Not able to get ContractAggrementId

### ISSUE THREAD

**Issue by dilipdhankecha07** [eclipse-dataspaceconnector/DataSpaceConnector#1112]
# Bug Report

## Describe the Bug
We are trying to integrate EDC with postgres Sql. During the integration we found this issue.
Let me describe the issue, 
First we are creating the Assets and once asset is created we offer a contract to consumer.
And consumer need to start the contract negotiation, once contract negotiation will completed then we want to know the status of the contract. And in the response, we got the **contract status** and **contractAgreementId**.
At that time, we are not able to get the **contractAgreementId** but the status for this negotiation is **CONFIRMED**.

### Expected Behavior
So the expected behaviour for this issue is, we must get the contractAgreementId once negotiation status will be CONFIRMED.

## Steps to Reproduce
```
1.CURL : curl --location --request POST 'localhost:8181/api/assets'
  DESCRIPTION : Create Assets

2.CURL : curl -X GET -H 'X-Api-Key: password' http://localhost:9191/api/control/catalog?provider=http://localhost:8282/api/v1/ids/data
  DESCRIPTION : Get Catalog (ContractOffer json will comes here for assets.)

3.CURL : curl -X POST -H "Content-Type: application/json" -d @samples/smart-sense-edc/contractoffer.json "http://localhost:9191/api/negotiation?connectorAddress=http://localhost:8282/api/v1/ids/data"
  DESCRIPTION : Start Contract Negotiation

4.CURL : curl -X GET -H 'X-Api-Key: password' "http://localhost:9191/api/control/negotiation/{contractNegotiationId}/state"
  DESCRIPTION : Return Contract Negotiation State
  RESPONSEBODY : 
		{
		    "status": "CONFIRMED",
		    "contractAgreementId": null
		}
```
you can get access of our implementation [here](https://github.com/nitinsmartsense/DataSpaceConnector).
In this project we have implemented two samples as mentioned below.
    1. [smart-sense-edc](https://github.com/nitinsmartsense/DataSpaceConnector/tree/main/samples/smart-sense-edc)
    2. [smart-sense-edc-in-memory](https://github.com/nitinsmartsense/DataSpaceConnector/tree/main/samples/smart-sense-edc-in-memory)
the same integration with in-memory implementation, we are not facing the issue but with postgres implementation we have faced this problem.

For build and run you can use below commands.
```
./gradlew samples:smart-sense-edc:provider:build -i -x test -x javadoc
java -Dedc.fs.config=samples/smart-sense-edc/provider/config.properties -jar samples/smart-sense-edc/provider/build/libs/provider.jar

./gradlew samples:smart-sense-edc:consumer:build -i -x test -x javadoc
java -Dedc.fs.config=samples/smart-sense-edc/consumer/config.properties -jar samples/smart-sense-edc/consumer/build/libs/consumer.jar
```

## Possible Implementation
As per our understanding, during the contact negotiation update, we need to create contract agreement.
![sql-edc](https://user-images.githubusercontent.com/67418065/162710404-faf2a86a-97fb-4759-ae44-1bdc7cc90c96.png)

**Comment by ndr-brt** [comment]
Thanks for reporting, could you paste here the log output from the connectors?

**Comment by dilipdhankecha07** [comment]
@ndr-brt 
Thanks for support.
But this is working in new PR.
Now we are able to get contractAgreementId.
