### ISSUE TITLE
Delete `control` api module

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1116]
# Feature Request

Delete `control` api module as it is deprecated and `data-management` should be used instead.
To be done after #1118 is completed

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by DominikPinsel** [comment]
Please correct me if I am wrong, but I assume we currently have no API,yet, to request a offer catalog from anther connector?

**Comment by paullatzelsperger** [comment]
I think there's an issue for it already

**Comment by DominikPinsel** [comment]
> Correct,but I think there's an issue for that already

Yes, you are correct. I haven't seen the issue yet when I wrote this comment.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
Done in #1310
