### ISSUE TITLE
Data Management API: negotiate a contract with an already existing policy

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1117]
# Feature Request

Currently it's only possible to use a custom policy passing it into the `POST /contractnegotiations` API request body.
Would be good to have the possiblity to specify only the `policyId` and have the negotiation manager fetch it from the database.

## Which Areas Would Be Affected?
contract negotiation manager

## Why Is the Feature Desired?
To avoid having to define a new policy every time a contract needs to be negotiated

## Solution Proposal
-

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by janpmeyer** [comment]
I just wanna clarify your idea if I understand it correctly.

The communication is now this way, if i remind and understand correctly:

**POST Request** with full Customized Policy -> **Consumer Connector** -> **Provider Connector** (Tries Matching his saved Policy with Customized Policy of the starting POST Request)


So i think their are two ways you can do it. 

**(A)** First the Consumer Connector has a database of existing Policies to exchange so it could work this way:

**POST Request** with PolicyID -> **Consumer Connector** (loads the policy with the policy ID) -> **Provider Connector** (Tries Matching his policy with the loaded policy of the consumer connector)

**(B)** The second way would be like:

**POST Request** with PolicyID -> **Consumer Connector** -> **Provider Connector** (Checks if the PolicyID is existing) 


Im right that you speak about way **A**?

**Comment by ndr-brt** [comment]
This is issue is probably obsolete now, there were some discussions goin' on about policies, I think this will be fixed by PR #1365
