### ISSUE TITLE
System Tests: Update EDC System test to use DataManagement API for asset transfer

### ISSUE THREAD

**Issue by cpeeyush** [eclipse-dataspaceconnector/DataSpaceConnector#1120]
## Description

Currently EDC system tests has its own custom Api controller to perform contract negotiation, initiate transfer and fetch transfer. DataManagement API is capable to provide these functionalities hence it should be used instead of a custom implementation.

(UPDATE: Contract negotiation already covered as part of PR #1113) 

## Acceptance Criteria

- [x] System test updated to use DataManagement API for asset transfer.
- [x] Sample 04.0-file transfer updated to use DataManagement API for asset transfer.
- [x] Removed existing custom implementation of ConsumerApiController.

**Comment by ndr-brt** [comment]
Take a look at #1113

**Comment by cpeeyush** [comment]
@ndr-brt Need your help on two things:

-  Do you plant to merge #1113 today ? 
- Are you already working on using Data Management APIs for asset transfer in system-tests ?

**Comment by ndr-brt** [comment]
@cpeeyush I have no merge permissions, but it's ready and it will be merged soon.
yes, take a look at `EndToEndTransferTest` (in the #1113 branch)
