### ISSUE TITLE
Story: add strict body validation for REST APIs

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1128]
# Feature Request

This story deals with two things actually:
- [ ] validate the request body using Jax-RS `@Valid` annotations and constraints
- [ ] disallow unrecognized JSON properties.

## Which Areas Would Be Affected?
REST APIs/endpoints

## Why Is the Feature Desired?
While the first item serves mostly serves to fail fast when invalid request bodies are supplied, the second one could actually be a security feature (overloading an endpoint with very large JSON).

## Solution Proposal
ad 1) use the Jax-RS `@Valid` annotation plus the corresponding constraint annotations (e.g. `@NotNull`,...)
ad 2) use an `ObjectMapper` that sets the `FAIL_ON_UNKNOWN_PROPERTIES` flag to true: 
```java
objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```
_Note that this MUST ONLY be set for REST APIs, possibly that means generating/duplicating the `ObjectMapper` specifically for that purpose_

## Type of Issue
Improvement

relates to #1111 

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by MoritzKeppler** [comment]
+1 for validating the request body.
Thinking about API backward compatibility it could make sense to tolerate unknown properties. 
From a security perspective it could be sufficient to limit the overall body size of a request.

**Comment by paullatzelsperger** [comment]
> Thinking about API backward compatibility it could make sense to tolerate unknown properties. From a security perspective it could be sufficient to limit the overall body size of a request.

could we use API versioning for this? or is introducing a new API version just because some DTO got a new property too invasive?
