### ISSUE TITLE
`ContractDefinitionDtoToContractDefinitionTransformer` does not transform `Policies`

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1137]
# Bug Report

## Describe the Bug

The `ContractDefinitionDtoToContractDefinitionTransformer` does not transform `Policies`. Therefore, all contract definitions that are created using the DataMgmt API do not contain any policy information besides the ID.

### Expected Behavior

`ContractDefinitionDtoToContractDefinitionTransformer` does not leave out information when creating `ContractDefinition` objects.

### Observed Behavior

`ContractDefinitions` that are created using the DataMgmtAPI carry the expected policy information. The `ContractDefinition` is takes later from the `ContractDefinitionStore` and causes unexpected behavior (e.g. `Offers` are created when the `Permission` wouldn't allow it).

## Steps to Reproduce

- Obvious in the code...

## Context Information

```java
  @Nullable
    public ContractDefinition transform(@Nullable ContractDefinitionDto object, @NotNull TransformerContext context) {
        return Builder.newInstance().id(object.getId()).accessPolicy(org.eclipse.dataspaceconnector.policy.model.Policy.Builder.newInstance().id(object.getAccessPolicyId()).build()).contractPolicy(org.eclipse.dataspaceconnector.policy.model.Policy.Builder.newInstance().id(object.getContractPolicyId()).build()).selectorExpression(org.eclipse.dataspaceconnector.spi.asset.AssetSelectorExpression.Builder.newInstance().criteria(object.getCriteria()).build()).build();
    }
```

## Detailed Description

-

## Possible Implementation

I assume there are two ways to fix this.
1. The `ContractDefinitionDtoToContractDefinitionTransformer` creates the `ContractDefinition` with the correct policy from the policy store.
2. The `ContractDefinition` should only contain the ID of the `Policy` and not the policy objects itself. This would force other components to always get the lates policy from the corresponding store.

I'd go with solution 2. What do you think?

Edit: Just saw that there is a ToDo for solution #2 in the source code. When I was debugging I only had the class files and didn't see it.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
Actually, that's a work in progress.
Currently the `ContractDefinition` contains the whole access/usage Policy object, but as you said, it should contain only the ids, this is already described in #828 

As the TODOs report in the code:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/8a3ab0295f2c57db08163cd35f41310ec563a915/extensions/api/data-management/contractdefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/contractdefinition/transform/ContractDefinitionDtoToContractDefinitionTransformer.java#L42-L43

Probably this issue can be closed in favor of #828
