### ISSUE TITLE
Data Management API: callback mechanism for all async operation

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#1160]
# Feature Request
all API operations that cannot be answered synchronously should provide a callback mechanism so that no polling for status update is necessary.
see also #914 

## Which Areas Would Be Affected?
data management API

## Why Is the Feature Desired?
Improve response time, avoid http calls

## Solution Proposal
Pass callback information in standardized way during request.
Proposal: Just notify about "update available"
Same concept can also be used in dataplane to notify a backend service about updates available for a data transfer. Update could include things like  "endpoint data reference ready" see #922, or "data transfered and available under local dataaddress"

## Type of Issue
improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by MoritzKeppler** [comment]
cc: @dr-markus

**Comment by ndr-brt** [comment]
My proposal here would be to provide an url at configuration level where all the events produced by the EDC will be sent as a POST http request, with the body similar to:
```json
{
  "eventType": "ContractNegotiationConfirmed",
  "data": {
    "id": "557f56f9-13fd-44ff-bd87-ba725f6a4905"
  },
  "timestamp": 1651148678,
  "connectorId": "connector:controlplane:id"
  ... other informations ...
}
```

The next step could be to have an event subscription api, similar to the "data plane registration", so that everyone could register themself to the connector events in every moment.

**Comment by florianrusch-zf** [comment]
@ndr-brt you could also have a look at this issue for an example use-case: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/914

**Comment by ndr-brt** [comment]
@florianrusch-zf yes, I'm aware of the use cases. the first draft of the Event Framework has been PR'd: #1413 , after it gets merged the event framework can be implemented and then the asynchronous communication can be put in place
