### ISSUE TITLE
Decentralized Identity: JWT hardening

### ISSUE THREAD

**Issue by marcgs** [eclipse-dataspaceconnector/DataSpaceConnector#1176]
# Feature Request

JWTs are used in EDC as means to authenticate IDS requests. The current implementation allows for a malicious entity that gets ahold of a JWT to impersonate the original sender, and thus send requests to any other participant. Two categories or impersonation attacks are possible depending on how the JWT used for the impersonation attack is obtained:

1. "JWT reuse": A malicious participant might reuse JWTs sent to him as provider, to send requests to other participants as a consumer impersonating the signer of the JWT.
1. "JWT leak": A malicious attacker that gets ahold of a leaked JWT token might use it to send request to any participant impersonating the signer of the JWT.
 
The goal of this story is to evaluate possible solutions for these two attack vectors and provide an implementation of the selected solution.

## Which Areas Would Be Affected?
Decentralized Identity

## Why Is the Feature Desired?
EDC complying with Decentralized Identity security standards

## Solution Proposal
TBD in this story

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
I think we should consider this scenario not only in the context of Decentralized Identity, but other JWTs, e.g. DATs.
