### ISSUE TITLE
Replace Metadatastore with AssetIndex

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#118]
Hello everyone,

I hope I understood correct, that the AssetIndex replaces the Metadata store. In case I understood this wrong, please feel free to close this issue.

If I'm correct this issue includes

- Delete the Metadatastore interface
- Adjust existing implementations, so that they use the AssetIndex instead
- Extend the AssetIndex Interface, so that it can be queried by Asset ID

At least some sample extensions depend on the possibility to add data to the Metadatastore/AssetIndex. This is a function I would not see in the AssetIndex, and I would suggest do remove this functionality instead. What do you think?

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
Sounds good, but we should only do this after the AssetIndex work is functional and the extensions using MetadataStore have been migrated. Otherwise, we will break those downstream extensions.

**Comment by ndr-brt** [comment]
Maybe the issue could be divided in some tasks which would be solvable by different PRs, like:
- introduce an in-memory implementation of the `AssetIndex` (similar to the `DemoAssetIndex`)
- add the `findById` method to `AssetIndex`
- substitute the usages of `MetadataStore` with `AssetIndex` (and migrate the extension to use the in-memory `AssetIndex`)

We also need to establish a mapping between `Asset` and `DataEntry` (if that does not exist yet), right?

**Comment by DominikPinsel** [comment]
You are right. Maybe a ``findById`` with an ``Optional<Asset>>`` as return value is the better solution.

Regarding the ``DataEntry``.  I assume this class should be deleted, too. But the current ``Asset`` implementation cannot describe any means of transportation,  like it is done with the ``DataAddress``. So maybe we must add this to the list as well.
