### ISSUE TITLE
Data management API: Transfer process: can't create more than one transfer

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1182]
# Bug Report

## Describe the Bug

If different data transfers are created (`POST /api/v1/data/transferprocess`) for the same asset, the same ID is returned back. The reason is that the `DataTransfer.id` field is not populated (as it is not present in `DataTransferDto`), and the idempotency mechanism in `TransferProcessManagerImpl#initiateRequest` is based on it.

## Possible Implementation
- Add id to DataTransferDto and convert it

**Comment by paullatzelsperger** [comment]
slightly tangential, but `org.eclipse.dataspaceconnector.api.datamanagement.asset.model.TransferRequestDto` is not used and can be removed. I suspect it's the product of a merge/rebase.
