### ISSUE TITLE
SPI to Policy-Model reference

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#119]
Hello everyone,

at the time of writing the SPI references the policy model extension. I think the SPI should not depend on any EDC extension. Therefore I would suggest moving the code from the policy model to the SPI and delete it. The policy model is included in the SPI by reference anyway.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
This is by design. The core policy model (different from the policy engine) should not depend on any runtime classes. The idea here is that the policy model can be embedded in an offline tool for authoring policy.

The other benefit is this would allow policy enforcement in external subsystems.

**Comment by DominikPinsel** [comment]
ah ok :) Then it was just a misunderstanding on my side. Now that you mention it, I think you already explained it at some point in time. Thanks for the fast reply and  I will close this issue now.
