### ISSUE TITLE
Rename Monitor to Logger

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#120]
Hello everyone,

I think naming the logger Monitor can be misleading. As far as I know it's a de facto standard, naming the logger component Logger (or similar).
Also, if we add at some point a real monitor component, we would have to rename it anyway.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
The intent of the Monitor interface is not simply to function as a log but to also provide a mechanism for observing system messages (different than events). 

I'd propose we selectively tackle issues given the amount of roadmap work we have.

**Comment by DominikPinsel** [comment]
Thanks for the reply. Now I understand why its named monitor :) Should we still rename the component to logger for now? This would prevent confusion, because currently it looks and is used like a logger. If the monitor appears on the roadmap, and the current Monitor class should still be used as monitor, we can rename it again.
