### ISSUE TITLE
Dataplane: improve and document interaction with controlplane

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#1201]
# Feature Request
Dataplane and Controlplane can run independently but depend on each other. The dependencies should be expressed as well-defined interfaces.
There are/might be interactions as part of
* enqueue transfer job, get job status
* validate/decrypt token
* enforce policies
* share secrets / access vault (or could dataplane be configured against idependent vault instance?)
* resource provisioning?

## Which Areas Would Be Affected?
DPF, dataplane, API

## Why Is the Feature Desired?
create more dataplane implementations, e.g. one based on a OSS solution as discussed in #1121

## Solution Proposal
swagger documentation for all API interactions

## Type of Issue
cleanup

**Comment by juliapampus** [comment]
#1519
