### ISSUE TITLE
Documentation and implementation not in sync

### ISSUE THREAD

**Issue by ppuetsch** [eclipse-dataspaceconnector/DataSpaceConnector#1218]
# Bug Report

## Describe the Bug
There are situations in documentations where the explanation does not match the actual implementation.
Examples: 
In https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/samples/03-configuration#2-access-the-config-value it's explained that one can express dependencies by overriding `requires()` from `ServiceExtension`, however in [ServiceExtension.java](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/ServiceExtension.java) as well as in the upstream [SystemExtension.java](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/system/SystemExtension.java) there's no `requires()` method.

Additionally, in the same file the property `dataspaceconnector.fs.config` is mentioned, which was probably renamed to `edc.fs.config`

### Expected Behavior
Current state of readme markdown files match the current state of the code

### Observed Behavior
Current state of readme markdown files does not match the current state of the code

## Steps to Reproduce
N/A

## Context Information
N/A

## Detailed Description
N/A

## Possible Implementation
adapt the readme files

**Comment by ndr-brt** [comment]
thanks for reporting, PR opened
