### ISSUE TITLE
Move Configuration out of ServiceExtension

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#123]
Hello everyone,

currently the Service Extension is used to load the configuration. I assume it is better if the configuration is part of its own service. 

This would
- reduce the size of the ServiceExtension Interface (separation of concerns)
- prevent that low level implementations, that only care about configuration, reference the whole ServiceExtension interface

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
I'm not sure about tunnelling a configuration object through multiple layers of services. The pattern we have used thus far is ServiceExtension implementations access configuration from the context and configuration is explicitly passed to downstream services. That makes it explicit which configuration an extension is using. Downstream services do not need to reference ServiceExtension or ServiceExtensionContext in this approach.

**Comment by jimmarino** [comment]
We resolved this by using POJOs for configuration. This also allows configuration errors to be trapped early, which a separate service object does not do.
