### ISSUE TITLE
ServiceExtensionContext should be able to provide multiple instances of the same type

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#124]
Hello everyone,

at the time of writing the ServiceExtensionContext interface cannot provide multiple interfaces of the same type. A current workaround is to register some kind of interface registry at the ServiceExtensionContext, which then can be used to retrieve multiple interfaces of the same type.
I would prefer it, if the ServiceExtensionContext would be able to return a List of implemented interfaces. So that creating these intermediate registry classes becomes obsolete.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
This would be simple to implement but I'm not sure it will make the registry concept obsolete. If the registry is removed, then each service implementation will need to guarantee that it is registered in the extension context prior to clients that depend on it.

This situation is handled by DI graphs, but introducing such a framework will then require us to write bind implementations into the DI configuration (e.g. Guice's module concept), which doesn't really simplify the problem, or perform some form of classpath scanning which brings its own set of issues given that the EDC should be constrained embeddable in other runtimes (i.e. EDC should not assume control over the host classpath). 

Registries are one of the tradeoffs of going with the limited dependencies approach in EDC. FWIW, some OSGi-based systems adopt a similar concept of a registry.

**Comment by DominikPinsel** [comment]
> This would be simple to implement but I'm not sure it will make the registry concept obsolete. If the registry is removed, then each service implementation will need to guarantee that it is registered in the extension context prior to clients that depend on it.
> 
> This situation is handled by DI graphs, but introducing such a framework will then require us to bind implementations into the DI configuration (e.g. Guice's module concept), which doesn't really simplify the problem, or perform some form of classpath scanning which brings its own set of issues given that the EDC should be embeddable in other runtimes (i.e. EDC should not assume control over the host classpath).
> 
> Registries are one of the tradeoffs of going with the limited dependencies approach in EDC. FWIW, some OSGi-based systems adopt a similar concept of a registry.

Yea, I also though about this. This becomes a problem if we get cyclic dependency between "service-extension-interface-packages". I don't know how to name it better 😄 
While this is a problem and makes it impossible for the ServiceExtensionContext to provide multiple interfaces at once, I think it would be really interesting to know whether this is the case in the code base. Just from a design perspective it would indicate, the service extension points that might not be well designed.

Maybe we should do a prototype? It could show us the interfaces, where the problems occur. In case we have these type of cyclic dependencies.

**Comment by jimmarino** [comment]
I'm not sure I follow the cyclic dependency issue. The runtime already checks for cyclic dependencies between requires/provides at boot.

I'm not against adding support for multiple service implementations but I don't think it will allow us to replace the registry pattern.

**Comment by denisneuling** [comment]
Hi @jimmarino, I've created a draft pull requests extending the DefaultServiceExtensionContext making it able to provide a list of service instances instead of just one. As you already mentioned the code change will not introduce any new issues while computation of the dependency graph happens, since that's done prior during boot phase.
