### ISSUE TITLE
Getting single contract negociation failed

### ISSUE THREAD

**Issue by lucian-torje-siemens** [eclipse-dataspaceconnector/DataSpaceConnector#1240]
# Bug Report

While running the sample samples/04.0-file-transfer/README.md I've got into an interesting situation - after creating the contract and listing all contracts, my contract is in the list, getting only that specific contract leads to 404 error.

$ curl -X GET -H 'X-Api-Key: password' "http://localhost:9192/api/v1/data/contractnegotiations"
[{"contractAgreementId":"1:9bded42a-ba83-4f86-9ac2-25f972046b0c","counterPartyAddress":"http://localhost:8282/api/v1/ids/data","errorDetail":null,"id":"8b40ca86-fafe-47cf-92a6-61c9ec2ff87e","protocol":"ids-multipart","state":"CONFIRMED","type":"CONSUMER"}]

$ curl -X GET -H 'X-Api-Key: password' "http://localhost:9192/api/v1/data/contractnegotiations/86348b40ca86-fafe-47cf-92a6-61c9ec2ff87e"
{ error: '404'}

### Expected Behavior
Getting a single contract should work.

### Observed Behavior
Return 404

## Steps to Reproduce
Steps:
- create contract POST /data/contractnegotiations and save UUID
- get contract negociation by UUID - GET /data/contractnegotiations/86348b40ca86-fafe-47cf-92a6-61c9ec2ff87e --> returns 404
- get all contract negociations GET /data/contractnegotiations/ --> my contract is in the list

## Context Information

- Used version [commit 013dcecaa - Introduce factory methods to provide object dependencies (#1150)]
- OS: [Windows, GitBash]

## Logs

INFO 2022-04-29T15:27:57.7710844 edc-0f315932-36ef-4a72-aa53-442374a02e57 ready
DEBUG 2022-04-29T15:34:06.8085957 Get all contract definitions QuerySpec{offset=0, pageSize=50, filterExpression=[], sortOrder=null, sortField=null}
DEBUG 2022-04-29T15:37:09.5361015 [Consumer] ContractNegotiation initiated. 8b40ca86-fafe-47cf-92a6-61c9ec2ff87e is now in state INITIAL.
DEBUG 2022-04-29T15:37:13.5959528 Response received from connector. Status 200
DEBUG 2022-04-29T15:37:13.6805121 [Consumer] ContractNegotiation 8b40ca86-fafe-47cf-92a6-61c9ec2ff87e is now in state REQUESTED.
DEBUG 2022-04-29T15:37:15.3487144 [Consumer] Contract agreement received. Validation successful.
DEBUG 2022-04-29T15:37:15.3487144 [Consumer] ContractNegotiation 8b40ca86-fafe-47cf-92a6-61c9ec2ff87e is now in state CONFIRMED.
DEBUG 2022-04-29T15:38:38.1475339 Get contract negotiation with id UUID
DEBUG 2022-04-29T15:40:44.7324008 Get contract negotiation with id 86348b40ca86-fafe-47cf-92a6-61c9ec2ff87e
DEBUG 2022-04-29T15:50:40.2547878 Get all contract definitions QuerySpec{offset=0, pageSize=50, filterExpression=[], sortOrder=null, sortField=null}

DEBUG 2022-04-29T15:56:04.3825291 Get contract negotiation with id 86348b40ca86-fafe-47cf-92a6-61c9ec2ff87e
DEBUG 2022-04-29T16:02:16.8971645 Get contract negotiation with id 86348b40ca86-fafe-47cf-92a6-61c9ec2ff87e

**Comment by bscholtes1A** [comment]
Not sure to understand. Nego ids do not match in your two requests:
$ curl -X GET -H 'X-Api-Key: password' "http://localhost:9192/api/v1/data/contractnegotiations"
[{"contractAgreementId":"1:9bded42a-ba83-4f86-9ac2-25f972046b0c","counterPartyAddress":"http://localhost:8282/api/v1/ids/data","errorDetail":null,"id":"**8b40ca86-fafe-47cf-92a6-61c9ec2ff87e**","protocol":"ids-multipart","state":"CONFIRMED","type":"CONSUMER"}]

Then you are asking for **86348b40ca86-fafe-47cf-92a6-61c9ec2ff87e**:

$ curl -X GET -H 'X-Api-Key: password' "http://localhost:9192/api/v1/data/contractnegotiations/86348b40ca86-fafe-47cf-92a6-61c9ec2ff87e"

**Comment by lucian-torje-siemens** [comment]
Could it be that the _curl -X POST -H "Content-Type: application/json" -H "X-Api-Key: password" -d @samples/04.0-file-transfer/contractoffer.json "http://localhost:9192/api/v1/data/contractnegotiations"_ output is not the nego id?

**Comment by florianrusch-zf** [comment]
As @bscholtes1A mentioned, there were a typo within the id which was tried to receive. Therefor no to do for us and we can close this.
