### ISSUE TITLE
Transfer process: Consumer does not receive information about failed transfers

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1242]
# Bug Report

## Describe the Bug

If a transfer fails on Provider/DPF side and moves to terminal error state, the consumer is not aware of this. If the destination is e.g. a blob storage container, the consumer will keep endlessly polling for a marker `*.complete` file.

### Expected Behavior
Provider should send a message to Consumer to put the transfer process in ERROR state.

**Comment by algattik** [comment]
See also #1287

**Comment by paullatzelsperger** [comment]
@juliapampus is there an IDS message we could abuse to communicate this information back to the consumer?

**Comment by schoenenberg** [comment]
Please reopen.

**Comment by ndr-brt** [comment]
Completed by: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/2116

**Comment by algattik** [comment]
@ndr-brt I haven't looked at your PR in detail, but from the title it seems to address a different scope than this issue? This issue is about two EDCs communicating with each other.

**Comment by ndr-brt** [comment]
@algattik that PR introduced a communication channel between data-planes and control-plane, so the first will notify about completed/failed transfers the latter. Doing this the transfer will stop the polling for the `*.complete` file
