### ISSUE TITLE
`ContractDefinitionService` interface exists twice

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1248]
# Feature Request

Currently there are two different kind of interfaces for a `ContractDefinitionService`. I would suggest to rename one,
They are implemented in the following packages
- `org.eclipse.dataspaceconnector.api.datamanagement.contractdefinition.service`
- `org.eclipse.dataspaceconnector.spi.contract.offer`

## Which Areas Would Be Affected?
- 

## Why Is the Feature Desired?

Avoid confusion in documentation and code.

## Solution Proposal

Rename one ContractDefinitionService.

## Type of Issue

Improvement / Cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
Completely agree, the one in the `contract-spi` module is a factory actually

**Comment by ndr-brt** [comment]
subsequent of #1887
