### ISSUE TITLE
Validate IDS Self-Description against SHACL Shapes

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#125]
Hello everyone,

as mentioned in [this](https://github.com/International-Data-Spaces-Association/InformationModel/issues/468) closed issue from the information model, the self-description should be validated against SHACL shapes.
In the ([currently open](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/115)) IDS self-description pull request there is no SHACL validation implemented.

A reference implementation may be found in the [IDS Messaging Services](https://github.com/International-Data-Spaces-Association/IDS-Messaging-Services) repository.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
Are you proposing that the self-description "should validate against" a specific shapes graph, i.e. the output conforms to a specific "schema", or that the runtime "must validate" a self-description as it is produced during a request?

**Comment by DominikPinsel** [comment]
If a saw it correct in the code, IDS-Messaging-Services does the SHACL validation only on responses. 

But I would assume our mapping from the EDC to the IDS model is not always perfect. The existing factories are not checking for values, that are not nullable. Everything that is allowed by the Fraunhofer IDS Information Model Builder, is also allowed by our factories. For example in case someone sets the default endpoint in the settings to an invalid URI or null, the factories will still create a self-description object. But this self-description has no default endpoint and is not SHACL valid.
Therefore I think it would be an idea to enable the validation on requests, too, and log the result as warning.

**Comment by MoritzKeppler** [comment]
Would be great to detect misconfigurations as early as possible, e.g. during startup, to avoid that a user accidently breaks IDS conformity. Not sure if we need to have the check being executed on every message. Maybe enough to check with every release that we produce valid structures.
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
I think I agree with Moritz. That is expensive to do at runtime or even startup.  Instead, this can be done through testing.

**Comment by DominikPinsel** [comment]
> Would be great to detect misconfigurations as early as possible, e.g. during startup, to avoid that a user accidently breaks IDS conformity. Not sure if we need to have the check being executed on every message. Maybe enough to check with every release that we produce valid structures.
> Moritz Keppler [moritz.keppler@daimler.com](mailto:moritz.keppler@daimler.com), Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

Yea. There's already a TODO for that in the IDS ConfigurationProvider class. We didn't implement this, because we logger/monitor doesn't have a warning level yet. That's maybe also something we need a new issue for. I made a note and will create this issue in the next days.

Back to the shapes validation: Do you agree, that you should validate the shapes in request and response messages?

**Comment by jimmarino** [comment]
> > Would be great to detect misconfigurations as early as possible, e.g. during startup, to avoid that a user accidently breaks IDS conformity. Not sure if we need to have the check being executed on every message. Maybe enough to check with every release that we produce valid structures.
> > Moritz Keppler [moritz.keppler@daimler.com](mailto:moritz.keppler@daimler.com), Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
> 
> Yea. There's already a TODO for that in the IDS ConfigurationProvider class. We didn't implement this, because we logger/monitor doesn't have a warning level yet. That's maybe also something we need a new issue for. I made a note and will create this issue in the next days.
> 
> Back to the shapes validation: Do you agree, that we should validate the shapes in request and response messages?
> 
Let's discuss this today. In general, I don't see the need to do schema validation (as opposed to other types of validation) during request/response handling.

What type of validation are you proposing, and would that be handled by EDC code or an external library?

> Dominik Pinsel [dominik.pinsel@daimler.com](mailto:dominik.pinsel@daimler.com), Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by ticapix** [comment]
Hello,

Is there a plan to provide Gaia-X conformant EDC Self-Descriptions ? (ie, be able to validate Self-Description against Gaia-X schema with SHACL)

Thank you,
Pierre

**Comment by bmaier** [comment]
... consider GAIA-X Self-Description (SD) follows the [W3C VC Spec](https://www.w3.org/TR/vc-data-model/) specifications and Json-LD schema definitions.
Therefore an asset Self-Description can be viewed as a composition of many independent VerifiableCredential and presented as VerifiablePresentation - it not one big file.

**Comment by stefan-ettl** [comment]
@ticapix: Yes we're planning to implement a Self-Description that will be GAIA-X compliant in the outlook.
