### ISSUE TITLE
[WIP] DPF: support high throughput event streaming

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#1255]
**THIS ISSUE IS STILL WORK IN PROGRESS**

# Feature Request

In #903, a first approach was proposed to share events through the Data Plane (DPF). Main advantage of this approach was that it required minimal development efforts as it was directly leveraging on the `DataSource`/`DataSink` paradigm of the DPF. On the other hand, this approach has important limitations, especially: 
- it puts pressure on the provider system for sending the events, which has to block a dedicated thread for sending event to each consumer,
- no delivery/ordering guarantee,

In the current issue, we investigate a production compliant implementation for sharing event streams with potentially large number of consumers and high throughput (several messages per second). The main concept behind this approach should to not reinvent the wheel, and leverage as much as possible on existing streaming standards, such as Apache Kafka.

## Which Areas Would Be Affected?

- DPF
- Control plane (potentially)

## Why Is the Feature Desired?
Streaming support is a must for a lot of partners.

## Solution Proposal
Proposed solution is to use the DPF as an orchestrator for public event broker hosted by the Provider. For each new data consumer, the provider Data Plane:

- requests for the creation of a new topic dedicated to this provider on the public event broker,
- adds the data consumer to the ACL of the public event broker and obtain credentials,
- pass these credentials to the consumer along with relevant info for connecting to the public broker (bootstrap servers, topic name…). TODO: how?
- finally it requests the event transfer start from the actual event source (which can be a different broker technology as the public event broker) to the newly created topic. Note that usage policies must be evaluated during the transfer (TODO: how?) so that the topic is only populated with events compliant with the usage policies, i.e. we do not duplicate the origin topic to the public event broker topic.

Once consumer receives credentials from the provider, it can use them to connect to the public broker of the provider. 

A tentative sequence diagram is depicted below:

![streaming_high_throughput drawio](https://user-images.githubusercontent.com/88310985/166480759-0efc1226-a3e7-481e-a72a-8ff59eb4d136.png)

Ideally we would like to support at least three techno for the public event broker:

- an industry standard: Kafka, 
- a cloud managed service, e.g. Azure Event Grid…
- an open source solution, eg NATS.io?

## Type of Issue
Improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
@bscholtes1A With this approach, couldn't we just implement it using the DataFlowController API on the provider side and avoid the hop to the DPF? In this sense, Kafka becomes a DPF implementation.

**Comment by bscholtes1A** [comment]
> @bscholtes1A With this approach, couldn't we just implement it using the DataFlowController API on the provider side and avoid the hop to the DPF? In this sense, Kafka becomes a DPF implementation.

Hi @jimmarino , 
yeap, that's a possible way to do. Let's discuss it during next workshop on this topic which is planned beg of next week.
