### ISSUE TITLE
No data flow controller found

### ISSUE THREAD

**Issue by dilipdhankecha2530** [eclipse-dataspaceconnector/DataSpaceConnector#1268]
SEVERE 2022-05-09T12:21:27.305925 Fatal error processing transfer request: a3cc00b8-acf3-471a-b5b7-b2d12e36df27. Error details: Unable to process data request a3cc00b8-acf3-471a-b5b7-b2d12e36df27. No data flow controller found

**Comment by florianrusch-zf** [comment]
@dilipdhankecha07 thanks for you error message. But to help you we need a lot more informations what you are trying and how your current setup looks like.

**Comment by dilipdhankecha07** [comment]
@florianrusch-zf 
We are added new sample in samples module named as "[smart-sense-edc](https://github.com/dilipdhankecha07/edc/tree/main/samples/smart-sense-edc)".

We are trying to connect EDC with postgres database, we are able to create asset, policy and contract.
But while transfer the data from provider to consumer, we are not able to exchange the data and we got the above mentioned issue.

**Comment by dilipdhankecha07** [comment]
@florianrusch-zf 
Any suggestion from your end?

**Comment by ndr-brt** [comment]
@dilipdhankecha2530 you miss the `data-plane-transfer-*` modules. Please add them and try again.
Take a look at `system-tests/e2e-transfer-test`, there is a fully end to end transfer example.
