### ISSUE TITLE
Bugfix: let Cosmos handle `IN` expressions properly

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1282]
# Bug Report

## Describe the Bug
Currently Cosmos requires that `IN` expressions are formulated in a particular way, i.e. `key IN ('value1', 'value2')` which is very error prone and is vulnerable to SQL injection.

### Expected Behavior
Interpret the right-hand operand and use prepared statements.

**Comment by DominikPinsel** [comment]
Is this a duplicated issue from #1002?

**Comment by paullatzelsperger** [comment]
> Is this a duplicated issue from #1002?

not sure if it's a 1:1 duplicate, but it sounds like it would solve #1002 as well. I'll link it.
