### ISSUE TITLE
Transfer process: Provider-side transfer remains IN_PROGRESS after completion

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1287]
# Bug Report

## Describe the Bug
When a transfer completes (e.g. transfer between Azure storage accounts), the transfer remains in IN_PROGRESS state.

The transfer process manager does not further process transfers on the Provider side that are IN_PROGRESS.
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/9436ebff2ba194c67ed4fc1f4dd0b98a07b3cf19/core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java#L332

### Expected Behavior
Transfers should progress to COMPLETED / ERROR state.

**Comment by paullatzelsperger** [comment]
I see two ways to solve this:
1. have the DPF access the `TransferProcessStore` and update the TP's state (which would have to use the `CommandQueue` if they're in the same runtime)
2. have the DPF signal back to the ControlPlane somehow that the TP has finished.

@jimmarino do you have an opinion on this?

**Comment by paullatzelsperger** [comment]
Turns out that this particular situation should be handled by what we will henceforth call "callbacks". @ndr-brt linking you since this ties into the discussion about events.

**Comment by schoenenberg** [comment]
Please reopen. It seems this is blocking every further Transfer.

**Comment by ndr-brt** [comment]
Completed by: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/2116

**Comment by ndr-brt** [comment]
> @ndr-brt It seems to me that the issue is still persisting. I am using the connector **milestone 8** image (so after this issue was fixed & closed) and I am facing the same situation where the transfer process is done, but the provider transfer process state is still `IN PROGESS`

This issue was referring to the "provider push" method, for the "consumer pull" in fact the transfer won't complete until the contract is valid or until one part explicitly terminates it, because once the consumer once starts the transfer, it can get the data how many times he needs to.
the "IN PROGRESS" status could be misleading, within the new specificiation it will become "STARTED"
