### ISSUE TITLE
Connector should not log "start transfer" when it's actually not starting any transfer

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1289]
# Bug Report

## Describe the Bug
The EDC logs pretty early that is starting a transfer. In combination with the missing exception logging, the whole log of a failed transfer start might look like this

```bash
[2022-05-12 08:57:27] [FINE   ] Starting transfer for asset
```

### Expected Behavior
- start transfer should only be logged if a transfer is actually started

### Observed Behavior
- connector logs that it started the transfer without actually starting anything.

## Steps to Reproduce
1. Make it somehow that the transfer process cannot be persisted (easy with external SQL storage)
2. `service.initiateTransfer` will throw an unlogged exception and no transfer started

## Context Information

```java

    @POST
    @Override
    public TransferId initiateTransfer(@Valid TransferRequestDto transferRequest) {
        var dataRequest = Optional.ofNullable(transformerRegistry.transform(transferRequest, DataRequest.class))
                .filter(AbstractResult::succeeded).map(AbstractResult::getContent);
        if (dataRequest.isEmpty()) {
            throw new IllegalArgumentException("Error during transforming TransferRequestDto into DataRequest");
        }
        monitor.debug("Starting transfer for asset " + transferRequest.getAssetId());

        var result = service.initiateTransfer(dataRequest.get());
        if (result.succeeded()) {
            monitor.debug(format("Transfer process initialised %s", result.getContent()));
            return new TransferId(result.getContent());
        } else {
            String message = format("Error during initiating the transfer with assetId: %s",
                    transferRequest.getAssetId());
            monitor.severe(message);
            throw new EdcException(message);
        }
    }
```

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by jimmarino** [comment]
We should break this issue down:

1. The debug message is correctly emitted at the current point in the transfer process. It could be clarified to "Initiating..." instead of "Starting..." but those terms are largely synonymous.

2. The EdcApiExceptionMapper should log the exception. However, the client will receive an error, which is correct.

I've changed this issue to an enhancement request.
