### ISSUE TITLE
PolicyStore does not save generated policies during negotiation

### ISSUE THREAD

**Issue by dcandas** [eclipse-dataspaceconnector/DataSpaceConnector#1292]
# Bug Report

## Describe the Bug
Policy store does not save generated policies during negotiation on provider's side, and consumer's identical policy does not carry the policy id over IDS messaging when sending the contract offer.

### Expected Behavior
After a negotiation, a transfer process using provision manager should succeed. The transfer process should not be blocked due to policies that were negotiated between the connectors.

### Observed Behavior
The transfer process cannot continue due to missing policy.

## Steps to Reproduce
1. In the provider, save an asset, policy and contract definition
2. Ensure that your provider does some sort of provisioning (that's when we get this error)
3. Start the negotiation from the consumer side and try to get the asset from the provider
4. The policyArchive.findPolicyForContract function returns null, which causes following lines to fail

## Context Information
- Used version: Hash 0da15e194d553178676f4fa6845c876bc9d7a2ad
- OS: Windows

## Possible Implementation
Please look into our change [here](https://github.com/dcandas/DataSpaceConnector/tree/edc-fork)

**Comment by paullatzelsperger** [comment]
Which `PolicyStore` are you using? Could you please also provide the exact line where `policyArchive.findPolicyForContract` returns null? There are four usages in the `TransferProcessManagerImpl`.

**Comment by dcandas** [comment]
InMemory PolicyStore. Line 250 for version 0da15e194d553178676f4fa6845c876bc9d7a2ad

**Comment by ndr-brt** [comment]
@dcandas could you try to replicate this against the latest commit of `main` branch (or the latest snapshot release)? I feel like it could have been solved

**Comment by dcandas** [comment]
Hello @ndr-brt, this seems to be currently solved. Thank you!
