### ISSUE TITLE
Serve openapi documentation

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1322]
# Feature Request

Would be useful for documentation purposes to have the openapi documentation rendered and accessible by everyone

## Which Areas Would Be Affected?
documentation

## Why Is the Feature Desired?
-

## Solution Proposal
_If possible, provide a (brief!) solution proposal._

## Type of Issue
_i.e., new feature, improvement, cleanup, etc._

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
One comment, this probably should only be available to clients with appropriate permissions.

**Comment by paullatzelsperger** [comment]
one option would be to serve this using Github Pages (a quick Google revealed [this](https://github.com/peter-evans/swagger-github-pages).

**Comment by paullatzelsperger** [comment]
removed the `stale` label - i'd love to tackle this in Milestone 5
