### ISSUE TITLE
Deprovisioning does not work (Cannot be called without a checker)

### ISSUE THREAD

**Issue by dcandas** [eclipse-dataspaceconnector/DataSpaceConnector#1324]
# Bug Report

## Describe the Bug
If there is no checker, the consumer ends immediately and deprovisioning is not called. Also, transfer does not complete on the provider side.

### Expected Behavior
A checker is not a requirement for a transfer to reach all states (since it can also be disabled).

### Observed Behavior
Consumer completes the transfer on its side immediately and the provider is stuck in a previous state (in progress?)

## Steps to Reproduce
Initiate a transfer, that has a deprovisioning phase, without a checker. Deprovisioning state is never called.

## Context Information
- Used version: 0da15e194d553178676f4fa6845c876bc9d7a2ad
- OS: Windows

## Additional Information
We could not find an explanation on what the checker is, which configurations it requires, and how to create a checker (except implementations) for our use case, which is creating a custom http flow controller.

**Comment by jimmarino** [comment]
I've removed the bug label as this may not be a bug.

Can you please describe the use case a bit further, e.g. what type of data is being transferred, over what protocol, and when is the transfer terminated?

**Comment by dcandas** [comment]
We are running a custom extension of the HttpDataFlowController which can use arbitrary sources and destinations. The data is being streamed over HTTP; a request is made to an internal endpoint and then pushed to the endpoint provided by the consumer.

Currently we are transferring json files and using pipelineServices, as dataplanemanager had missing endpoints and we could not get the checker+verifier working for the data push scenario.

When we debug the system, we see that the consumer completes immediately, and the provider is stuck in progress. The controller's initiate flow is called, a success is returned by the controller, but the state machine does not move forward to the next stage. So the transfer is never terminated at the provider's side and it also never reaches deprovisioning. When we modify the code and move the states ourselves, the process completes.

**Comment by dcandas** [comment]
Hello, I wanted to shortly report that updating from commit 63e45965d26180b797e75f9a09dcd8ab8aa7b06a to d23de1648090991dd6fd4a9c154c697093c1dc04 solved our problem. I assume that the fix came from this PR: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1427
