### ISSUE TITLE
Show error message if Policy could not be deleted

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-dataspaceconnector/DataSpaceConnector#1332]
# Bug Report

## Describe the Bug
If a `Policy` is still used within a `ContractDefinition` and the user tries to delete the `Policy` he receives a response with the statuscode 409 without any information why there is a conflict.

### Expected Behavior
It would be nice if the user could see this either in the response body or at least in the logs. I think this was already planned (that's why the issue was labeled as a bug) because e.g. in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/97e2fbe46aa758f36773d49946d7e084647335ca/extensions/api/data-management/policydefinition/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/policy/service/PolicyServiceImpl.java#L69 an error message was already given.

### Observed Behavior
Nothing happend. Just the 409 response and a log line with this text: `Attempting to delete policy with id ...`

## Steps to Reproduce
1. Create an `Asset`, `Policy` and a `ContractDefinition`
2. Delete the `Policy`

## Additional informations

Maybe this is also relevant for the other endpoints. I haven't checked that so far.

**Comment by paullatzelsperger** [comment]
This is something that should be documented using OpenAPI, not returned as response body. There is already an issue to improve the documentation #1122. Removing the bug label.

**Comment by florianrusch-zf** [comment]
> Why don't have the `Result` messages reported in the response body?

Do we already had any kind of decision which would point in this direction? If not we should discuss this and decide how we want to proceed here. Maybe we could introduce a specific error response object we want to use. Should we start a discussion for that?

**Comment by florianrusch-zf** [comment]
@ndr-brt is this already implemented within #1479? Or do we still need one of the other issues you have opened (#1490, #1492)?

**Comment by ndr-brt** [comment]
@florianrusch-zf In my opinion it's resolved, the other issues I opened is to improve this, but did #1479 fulfill your needs?

**Comment by florianrusch-zf** [comment]
I haven't checked it in details until now. Will do it and if yes I will close this issue.
