### ISSUE TITLE
Allow deletion of Asset only if no ContractDefinition or Policy is referring to it

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-dataspaceconnector/DataSpaceConnector#1333]
# Bug Report

## Describe the Bug
You can delete an asset even if a `ContractDefinition` or a `Policy` is still referring to it.

### Expected Behavior
Throw a 409 and show somewhere (e.g. response body & log; see #1332) an error message.

### Observed Behavior
Nothing happend - got a 204.

## Steps to Reproduce
1. Create a `Asset`, `Policy` and `ContractDefinition` 
2. Delete the `Asset`

**Comment by paullatzelsperger** [comment]
First of all, a `Policy` does not refer to an `Asset`. Both are referenced by a `ContractDefinition`. Deleting assets that are referenced by a `ContractDefinition`'s `AssetSelectorExpression` should be possible, and was implemented thus by design. Removing the `bug` label.
