### ISSUE TITLE
Cannot build on MacBook M1

### ISSUE THREAD

**Issue by oxisto** [eclipse-dataspaceconnector/DataSpaceConnector#134]
It seems, it is not possible to build the connector on an arm64 Mac platform.

To reproduce (on mac/arm64):

`./gradlew clean build`

```
* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > Unable to download toolchain matching these requirements: {languageVersion=11, vendor=any, implementation=vendor-specific}
         > Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
            > Could not read 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/mac/aarch64/jdk/hotspot/normal/adoptopenjdk' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Is it possible to circumvent the download of an extra toolchain? It's not really needed as I have already an arm64 java toolchain installed.

**Comment by ndr-brt** [comment]
It does: 
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/034b193612c2e4b76b8e3eeba4374dfbcc0e0b7b/README.md?plain=1#L28

**Comment by oxisto** [comment]
> It does:
> https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/034b193612c2e4b76b8e3eeba4374dfbcc0e0b7b/README.md?plain=1#L28

I did not mean in the README, but in the gradle toolchain.

**Comment by ndr-brt** [comment]
can you provide a PR for this?

**Comment by oxisto** [comment]
It seems that it somehow has fixed itself, so this issue can stay closed then.
