### ISSUE TITLE
Use data-plane on sample 05

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1341]
# Feature Request

Currently, sample-05 uses the deprecated `InlineDataFlowController`, when it should use the data plane framework.

## Which Areas Would Be Affected?
samples

## Why Is the Feature Desired?
Cleanup

## Solution Proposal
-

## Type of Issue
cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by schoenenberg** [comment]
I would like to work on this issue, as this is a good way on getting more into the DPF. Can you lead me into a direction, what to use instead of the `InlineDataFlowController`?

**Comment by ndr-brt** [comment]
The best approach would be to take a look at the sample-04, since it already uses the data-plane, though it's a "custom" version (that implements custom `DataSourceFactory` and `DataSinkFactory`).
In theory would be enough to include `aws/data-plane-s3` and `azure/data-plane/storage` as dependencies of the `sample-05/transfer-file` module and remove the other currently used. 
This need to be tested following the `sample-05/README.md` guide
