### ISSUE TITLE
Add validation to avoid `ContractDefinition` id to contain `:`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1347]
# Feature Request

Creating a `ContractDefinition` with a `:` contained in the string would cause this error:
```
ContractRejectionHandler: Received contract rejection to message null. Negotiation process: 67abd883-b5b5-4e57-bf71-f5844f012a29. Rejection Reason: "Invalid id: urn:1edcc7c0-4796-46bc-bafd-87bd440cc68a:8d9e7ac4-770c-431c-9e2f-2e575c870e9a"
```

Would be good to have a validation on the `contractdefinition` api, to avoid this possibility.
Another way could be to have the "contract id parser" being able to permit the use of `:` inside the contract definition id, but seems to be more convoluted.

## Which Areas Would Be Affected?
data management api

## Why Is the Feature Desired?
To avoid exceptions

## Solution Proposal
-

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
The should be a GUID (not URN) so +1 on adding validation in the API. Additional validation could also be added in ContractDefinition itself to catch other places.
