### ISSUE TITLE
Clean up IDS modules

### ISSUE THREAD

**Issue by juliapampus** [eclipse-dataspaceconnector/DataSpaceConnector#1351]
# Feature Request

I took a look at the current IDS capabilities and the module seems like a mess. We have to remove unused code (considered to stay unused), address open TODOs, and stabilize the IDS messaging (serializer usage, validation, properties etc.).

## Which Areas Would Be Affected?
mainly `:data-protocols:ids`

## Why Is the Feature Desired?
Keep the code lean and working

## Solution Proposal
I would propose to derive several issues from this. _(Feel free to extend the list)_
- [x] #1466
- [x] #1471
- [x] Remove unused package `descriptor` from `ids-spi` and `ids-core`
- [x] Restructure existing `spi` directory structure (group `identifier`, `protocols`)
- [x] #1473
- [x] #1600
- [x] #1610 
- [x] #236 
- [x] Clean up `ids` modules (e.g. some multipart-related classes are located in the core module)
- [x] #1152 
- [x] #1474
- [x] #918
- [x] #1727
- [x] Clean up transformers
- [x] #2022 

## Type of Issue
improvement, cleanup, ids

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ronjaquensel** [comment]
All story items have been completed.
