### ISSUE TITLE
Flaky Test:  Data Plane Azure Data Factory Test

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1359]
# Bug Report

## Describe the Bug
There seems to be some sort of race condition in the ADF-related tests, for example:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6587724195?check_suite_focus=true#step:6:201

### Expected Behavior
_A clear and concise description of what you expected to happen._

### Observed Behavior
Deleting cloud resources seems to not work sometimes, when they're already being deleted.

## Steps to Reproduce
1. Run CI/CD Pipeline in GitHub

## Detailed Description
It seems that a SAS Token that is being used for the test is deleted, which fails, because it's already being deleted.

## Possible Implementation
add defensive checks

**Comment by paullatzelsperger** [comment]
@cpeeyush maybe you could take a look?

**Comment by cpeeyush** [comment]
> @cpeeyush maybe you could take a look?

@paullatzelsperger PR is open for fix : https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1394 Thank you.
