### ISSUE TITLE
Core: Add timestamp to entities

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1370]
Add timestamp to track entity creation and update in a uniform manner as in #1350.

See also #1364

_Originally posted by @ndr-brt in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1350#pullrequestreview-988906511_

**Comment by diegogomez-zf** [comment]
@algattik can i still work on this issue? I can take a look at it.

**Comment by paullatzelsperger** [comment]
@diegogomez-zf this issue will touch on code at the very core of EDC, so it is important to have a written technical proposal before writing any code. 

Please provide this proposal as separate PR in the form of a decision record document (cf.
 `docs/developer/decision-records`). It should include at least the following sections:
- Decision: _what_ is done
- Rationale: _why_ it is done
- Approach: _how_ it is going to be implemented

Please also outline what extensions this is going to impact, and how.

**Comment by paullatzelsperger** [comment]
will work on this
