### ISSUE TITLE
Cosmos DB doesn't support ordering by invalid fields

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1377]
# Bug Report

## Describe the Bug

These integration tests are failing on our fork:
- findAll_verifySortingInvalidSortField
- queryAgreements_verifySorting_invalidProperty

I can also reproduce this 100% of the time running those tests locally against an Azure Cosmos DB instance (not emulator, which I haven't tried).

[ The default indexing policy won't allow for the retrieval of the documents where the sort property is undefined](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-order-by#remarks). The integration tests were built on a legacy version of Cosmos DB where that restriction was in place.

## Detailed Description

When sorting a query by a field that doesn't exist, we observe in our instance that the data is not returned.

I can reproduce this in Azure portal.

Sorting by a field that exists:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/22099722/171138261-d663242b-87e4-4967-9506-e8268da716f7.png">

Sorting by a field that does not exist:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/22099722/171138353-36d42337-2f50-4cb8-9a0d-5399f928faea.png">

In upstream EDC, the tests are currently passing. Presumably, legacy deployments of Cosmos DB had different restrictions on indexing and sorting.

**Comment by paullatzelsperger** [comment]
we need to adapt the tests, and re-create the CosmosDB instance that we use for upstream integration tests.
I'll add creating the CosmosDB to the terraform scripts in `resources/azure/testing` to maintain consistency.

**Comment by paullatzelsperger** [comment]
FYI the tests mentioned in the description are correct IMO, as they expect an empty list when sorting on a non-existent field.
However, the linked PR #1414 adds CosmosDB as resource when setting up a fork.

**Comment by algattik** [comment]
> FYI the tests mentioned in the description are correct IMO, as they expect an empty list when sorting on a non-existent field.

I agree
