### ISSUE TITLE
Filter asset not working properly for certain values

### ISSUE THREAD

**Issue by Tintoiu-Anca** [eclipse-dataspaceconnector/DataSpaceConnector#1380]
# Bug Report

## Describe the Bug
If the value provided to filter an asset has "=" inside, EDC splits it based on the equals sign and takes only the first half.

When trying to filter assets based on their properties, the following occurs:
- let's consider having the folllowing Asset:

```
[
    {
        "properties": {
            "additionalProp1": "a/b=c/d",
        }
    }
]
```

- when filtering by `additionalProp1` having the value  `a/b=c/d` using the request` GET assets?filter=additionalProp1=a/b=c/d` EDC takes as an input only `a/b` ignoring everything that comes after the sign "="

### Expected Behavior
EDC should take as an input the entire value and filter properly based on it.

### Observed Behavior
The call described above returns `[]` and 200 status code.
I've tried encoding the equals sign as well as the entire input, but nothing worked.

## Steps to Reproduce
1. Create an asset and populate a property with a value containing "="
2. Filter the assets based on the property and using the value having "=" inside it

## Context Information
- OS: [Windows]

## Logs
DEBUG 2022-05-31T13:41:10.1428741 get all Assets from QuerySpec{offset=0, pageSize=50, filterExpression=[asset:prop:p1 = a/b], sortOrder=null, sortField=null}

**Comment by paullatzelsperger** [comment]
I'll take a look at this. Probably an easy fix.

**Comment by paullatzelsperger** [comment]
I submitted fix for this. This fix also includes a change that allows the right-hand operand to contain spaces, for example `"additionalProp1=some value"`.

**Comment by Tintoiu-Anca** [comment]
@paullatzelsperger  thank you!
