### ISSUE TITLE
Bug: running Minikube tests locally fails with a NPE

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1397]
# Bug Report

## Describe the Bug
When running the minikube tests locally, the test report indicates a NPE (see image below).

### Expected Behavior
Test should run without exception.

### Observed Behavior
The Gatling Test report indicates a Nullpointer exception, unfortunately without a stacktrace

## Steps to Reproduce
1. start minkube
2. follow the steps in `system-tests/minikube/README.md`

## Context Information
- Used version e6702540beca1624bcc194f912a86c18bc8ee21b
- OS: (Arch) Linux

## Detailed Description
![minikube](https://user-images.githubusercontent.com/43503240/171602912-5d9237a8-a157-46b2-a0c4-40c5d00d770e.png)

Attached is also a zip file containing the Gatling report.

[filetransferasclientsimulation-20220602094836736.zip](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/files/8822668/filetransferasclientsimulation-20220602094836736.zip)

**Comment by iwasakims** [comment]
I could not reproduce the issue today.

Used version: main 3aa192a80d4c92503c3a6a32fbb3e5d0fe4002de
OS: Ubuntu 22.04.1 LTS
minikube version: v1.26.1
