### ISSUE TITLE
Chore: Remove dead code

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#1456]
There are numerous examples of dead code that need to be removed. This issue will serve to track those.

Checklist
[ ] Remove inline data flow, including migration of any remaining samples that use it.

**Comment by ndr-brt** [comment]
Should the stuff into `samples/others` to be considered dead code? If a sample is relevant should stay in the `samples` folder directly
- [ ] custom-runtime
- [ ] run-from-junit
