### ISSUE TITLE
IDS is incompatible with our Policy-Model

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#146]
Hello everyone,

at the time of writing EDC policy model is not map-able to the IDS contract model. Currently, the only use case we are
mapping is the "everything allowed" policy. This special case is map-able. But as soon as there are any contract details
specified, both models clash. As the contract will probably be persistent at some point in the future, it would be nice to have a
working policy model by then.

**Mapping Clashes**

Correct me if I'm wrong, but as far as I see the two models clash at least the following points (maybe more):

- **Constraints**
    - The EDC policy model knows the following constraints: `AndConstraint`, `AtomicConstraint`, `XoneConstraint`
      , `OrConstraint`. The IDS policy model only knows `AtomicConstraint`s
- **Operands**
    - While the left and right `Operand`s of the Policy Model are generic (currently only Strings), IDS has an `Enum` as
      left operand and an `RdfResource` as right `Operand`, which theoretically would be applicable to strings but would
      erase context.
- **Operator**
    - The EDC policy model knows of 7 operators. The IDS policy model knows of 46 operators. Both models rarely
      intersect.
- **Duty**
    - The EDC `Permission` has a list of `Dutie`s. The IDS `Permission` has a list of pre- and post-`Duty`s. While the
      IDS `Permission` objects could be mapped to EDC `Permission`s, mapping vice versa is impossible.

Hopefully the problem is clear. If IDS uses unknown `Operator`s it's impossible to construct EDC contracts. Analogous if
the EDC uses a `XoneConstraint` its impossible to describe this policy in IDS.

**Requirements for the new policy model**

Assuming these requirements have to be met:

- The EDC model must be able to be **persisted**
- The EDC model must be **transformable** to IDS (and vice versa)
- The persisted state **must survive schema evolution** of the EDC model
- The persisted state **must survive schema evolution** of the IDS Information Model

**Possible Solutions**

I must say, that I don't know how a good solution might look like. My opinion is, that we don't need an abstraction from
IDS, as probably only IDS uses ORDL like rules. This would make a lot of things easier. I tried to spark a discussion [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/132), but it didn't work :)

So maybe someone from the community has an idea how the current policy-model could change or new requirements.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by mspiekermann** [comment]
This issue is further discussed in #132. Closing this issue to merge streams of discussion of this important topic.
