### ISSUE TITLE
Core: base classes for entities and in-memory store

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1463]
# Feature Request

Developing an extension that introduces a custom entity with `state-machine-lib` requires writing boilerplate code that is already duplicated between `TransferProcess` and `ContractNegotiation`, as well as their store implementations (presumably this will apply to `DataFlowRequest` as well, when persistence for it is developed). There is an opportunity to introduce extensibility and reduce technical debt instead.

The code in question is primarily associated with state code and associated timestamps.

To reduce code duplication, we could develop:
- Generic base class for entities with associated state.
- Generic base class for in-memory entity store.
- Adapt `TransferProcess` and `ContractNegotiation` and their in-memory stores to use the base classes.

As follow-up work, generic base classes for Cosmos DB and PostgreSQL entity stores could be developed.

The interfaces and behavior would not change.

Note: `InMemoryTransferProcessStore` uses an additional caching layer and custom locking mechanism. Given this class is only meant to use for testing, it seems reasonable to remove this additional layer and use a simple `ConcurrentHashMap` for storage in the new generic in-memory store to reduce complexity.

## Which Areas Would Be Affected?

Core

## Solution Proposal

```java

public abstract class StateMachineEntity<T> implements TraceCarrier {

    protected String id;
    protected long createdTimestamp;
    protected int state;
    protected int stateCount;
    protected long stateTimestamp;
    protected Map<String, String> traceContext = new HashMap<>();
    protected String errorDetail;
    protected Clock clock;

   protected abstract static class Builder<T extends StateMachineEntity, B extends Builder<T, B>> {
   /...
}

public class TransferProcess extends StateMachineEntity<TransferProcess> {
}
```

```java
public class InMemoryEntityStore<T extends StateMachineEntity<T>> implements StateEntityStore<T> {
    T find(String id);
    void create(T entity);
    void update(T entity);
    void delete(String processId);
    Stream<T> findAll(QuerySpec querySpec);
    List<T> nextForState(int state, int max);
}
```

## Type of Issue

Technical debt refactoring

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
This would be a great improvement to have for M5!
