### ISSUE TITLE
Unnecessary credential exposure to consumer using data-plane-http

### ISSUE THREAD

**Issue by lholthof** [eclipse-dataspaceconnector/DataSpaceConnector#1469]
Dear community,

I have spend some time to understand the end-to-end communication flow Catena-X assets are going to take using the data-plane-http. If I understand correctly Provider EDC and Consumer EDC perform an IDS based contract negotiation and as a result the consumer receives and EndpointDataReference (EDR). This EDR will be used by the consumer-data-plane to call the provider-data-plane as it contains the endpoint url as well as a JWT Token (DAPS) to authenticate against provider-data-plane. This DAPS JWT Token again contains an authCode which will be used for authentication between provider-data-plane and the backend (data-source).

Why is the credential to be used between provider-data-plane and the backend exposed to the consumer? The consumer does not require this information at all and in case the consumer gets compromised the credential is leaked. In addition the secret is exposed in case of "JWT reuse" and "JWT leak" attack (see https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1176) as well.

Can anyone confirm my understanding or am I not getting it right? 

## Which Areas Would Be Affected?
control-plane and data-plane (especially data-plane-http)

## Why Is the Feature Desired?
Share as least information as possible. Comply with corporate security standards.

## Solution Proposal
I can think of a mechanism where the endpoint credential is replaced by a pointer to an entry inside the vault. The vault is accessible by control and data plane, hence the control plane might add a secret on asset registration and reference it in the dataAddress. Then a EDR would just contain this pointer to the vault and the data plane might consume (cached) from the vault after successful DAPS authentication.

**Comment by bscholtes1A** [comment]
I think there was some misunderstanding here. 

The `EndpointDataReference` never contain DAPS token. It contains tokens used to access the public API of the DataPlane. These token are built out of band of the `IdentityService`, meaning that they do not depend on how identity management is configured in your EDC instance (DID, Daps...).

A good start point for understanding the process would be: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/data-plane-transfer/data-plane-transfer-sync/src/main/java/org/eclipse/dataspaceconnector/transfer/dataplane/sync/DataPlaneTransferSyncExtension.java

**Comment by lholthof** [comment]
Thanks for your response. Yes you are right, my wording was incorrect. There is no DAPS token used for Authentication in public API of the DataPlane. If I do understand it right now, the injected control plane's keypair is being used to create a JWT which is passed to the consumer for data plane to data plane authentication.

But anyways, this token contains the information of the asset's backend including credentials. Or is there a way to prevent this?
If I remember correctly then it is processed as properties in: [DataPlanePublicApiController.java#L135](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/data-plane/data-plane-api/src/main/java/org/eclipse/dataspaceconnector/dataplane/api/controller/DataPlanePublicApiController.java#L135)

**Comment by bscholtes1A** [comment]
Backend properties are encrypted (not in current implementation as for now there is a NO-OP `DataEncrypter`, but will be implemented). So they wont be readible by the consumer. 

Also for the credentials, Asset can be defined so that we pass the secret name, and not directly the secret itself. 
In that case the secret value will be retrieved from the vault, which brings another level of security on top of the encryption.

**Comment by jimmarino** [comment]
This would likely be implemented using a caching strategy when we schedule it for a milestone.
