### ISSUE TITLE
Move `IdsProtocol` from `ids-transform`

### ISSUE THREAD

**Issue by juliapampus** [eclipse-dataspaceconnector/DataSpaceConnector#1473]
# Feature Request

The `IdsProtocol` is a class that is not only used within the `:ids:ids-transform` module. On top of that, the naming may not be that appropriate as it contains one constant representing an IDS Infomodel version.

## Which Areas Would Be Affected?
ids

## Why Is the Feature Desired?
Prevent circular and unnecessary dependencies between modules.

## Solution Proposal
tbw. Either just moving the file or merging it into another existing class. Do we want to support multiple Information Models? Do we need a list of versions? Then, an enum would fit.

## Type of Issue
cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
I think we don't want to support multiple info models in the same runtime. This can be achieved by using separate runtimes and URL routing via K8S.
