### ISSUE TITLE
Document the Azure Key Vault Extension

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1499]
# Feature Request

At the time of writing the Azure Key Vault Extensions is not documented ([link](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/azure/vault)).

Things that could be added to the README.md
- Link to the official Microsoft Documentation, for people that are not familiar with the Azure Key Vault
- Settings and where to get the values from

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by jimmarino** [comment]
Closing as this will be addressed in #1494
