### ISSUE TITLE
Document the DAPS Extension

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1500]
# Feature Request

At the time of writing the DAPS Documentation only says something about Omejdn and Integration Tests, but nothing about the extension itself ([link](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/iam/daps)).

Things that could be added to the README.md
- Required Configuration and where to get the values from
- Mentioning of the dependency to the [OAuth Core Extension](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/iam/oauth2/oauth2-core) (or SPI, but the SPI is missing documentation as well)

# Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by jimmarino** [comment]
Closing as this will be addressed in #1494
