### ISSUE TITLE
Add OpenAPI spec of IDS endpoint

### ISSUE THREAD

**Issue by iwasakims** [eclipse-dataspaceconnector/DataSpaceConnector#1563]
# Feature Request

openapi.yaml should be cover the API of IDS endpoint

## Which Areas Would Be Affected?

OpenAPI spec

## Why Is the Feature Desired?

for improving documentaiton

## Solution Proposal

adding swagger-gradle-plugin to build.gradle and additional information by Tag annotation

## Type of Issue

improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
from my PR comment: 
> the IDS endpoint is not an API consumable by clients, but rather facilitates connector-to-connector communication. Simply having it documented in OpenAPI will not help because it won't document the message flow.

> In order to do that, we're currently working on documentation and specification of the entire IDS protocol and message flow, which will surface soon. This PR will therefore be closed.

**Comment by iwasakims** [comment]
@paullatzelsperger Thanks for the comment. It makes sense to me. Is #1085 related? Let me help to improve the docs in the follow-up issues.
