### ISSUE TITLE
Dataplane http Additional headers uses colon which collides with http spec

### ISSUE THREAD

**Issue by lucian-torje-siemens** [eclipse-dataspaceconnector/DataSpaceConnector#1573]
# Bug Report

## Describe the Bug
Dataplane http headers use colon which collides with http spec - replace with underscore

### Expected Behavior
The header is in the right format

### Observed Behavior
It does not comply with RFC2616 - message-header = field-name ":" [ field-value ]

## Context Information
_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

## Detailed Description
see https://www.rfc-editor.org/rfc/rfc2616

## Possible Implementation
Replace with underscore

**Comment by ndr-brt** [comment]
As I specified in the related PR this doesn't collide with the http spec, it cannot be considered a bug.

**Comment by lucian-torje-siemens** [comment]
not a bug
