### ISSUE TITLE
Remove BouncyCastle Dependency

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1598]
# Feature Request

The Eclipse Dataspace Connector should not have a dependency to the BouncyCastle library

> Please see comments about removing Bouncycastle and aligning with Azure vault

[decision by jim](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1534#pullrequestreview-1026841699)

## Which Areas Would Be Affected?

- identity-did-crypto extension
- dummy-credentials-verifier extension
- data-plane-transfer-sync extension
- azure-data-factory extension
- core-base extension
 

## Why Is the Feature Desired?

- 

## Solution Proposal

Commiters, that added the dependency, should be responsible to remove them again

@jimmarino Please remove the dependency from the following extension
- identity-did-crypto extension ([commit](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/cc05b797708f5037c6f913b0fa76cb089e7c56d8#diff-3f646d63fea149d37a44c7d09a9feec4c797ac25ebff8c104df587a8e1c48b31))

@paullatzelsperger Please remove the dependency from the following extensions
- dummy-credentials-verifier extension ([commit](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/8a5df66d62b430662901dcb102cea5f8b464444f#diff-5d9dd5a45754efc86ff3a456046aef6afb54ceacd71f238991ccb1dc0fda2e7c))
- azure-data-factory extension ([commit](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/679409d3c8754e3ce1d2e4c6f0e28b97d65056e9))

@ndr-brt Please remove the dependency from the following extension
- data-plane-transfer-sync extension ([commit](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/3c60347fac2de307cd1ec8331b08b67e51df1a97))
- core-base extension ([commit](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/047a5a9310c677b74ffaded6ba98d7ff1df20fd3))

## Type of Issue

- improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
Most of these were a vestige of support for ION. This can be done in a single PR.

**Comment by paullatzelsperger** [comment]
No BC cannot be removed because Nimbus still depends on it. We use Nimbus for JWS/JWT handling.
