### ISSUE TITLE
ids: CatalogQueryController should return list of Assets instead of list of String

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#160]

**Comment by mspiekermann** [comment]
@bscholtes1A is this one still relevant or fixed with the merge of #159 ?

**Comment by bscholtes1A** [comment]
> @bscholtes1A is this one still relevant or fixed with the merge of #159 ?

@mspiekermann yeap this one should be closed
