### ISSUE TITLE
Remove `pre-`methods from the `ContractNegotiationListener`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1649]
# Feature Request

Seems like the `pre-` methods in the `ContractNegotiationListener` are not used by anyone, and they have been replaced by the "post" ones.
Based on the discussion in the pull #1609 , they could be removed then.

## Which Areas Would Be Affected?
contract negotiation listener

## Why Is the Feature Desired?
cleanup

## Solution Proposal
Remove these methods from `ContractNegotiationListener:
```java
default void preRequesting(ContractNegotiation negotiation)
default void preRequested(ContractNegotiation negotiation)
default void preProviderOffering(ContractNegotiation negotiation)
default void preProviderOffered(ContractNegotiation negotiation)
default void preConsumerOffering(ContractNegotiation negotiation)
default void preConsumerOffered(ContractNegotiation negotiation)
default void preConsumerApproving(ContractNegotiation negotiation)
default void preConsumerApproved(ContractNegotiation negotiation)
default void preDeclining(ContractNegotiation negotiation)
default void preDeclined(ContractNegotiation negotiation)
default void preConfirming(ContractNegotiation negotiation)
default void preConfirmed(ContractNegotiation negotiation)
default void preError(ContractNegotiation negotiation)
```

## Type of Issue
cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
Quick question before we remove these: How will the event system achieve transactional atomicity with state changes if the dispatch is asynchronous?

**Comment by ndr-brt** [comment]
> Quick question for @ndr-brt and @paullatzelsperger before we remove these: How will the event system achieve transactional atomicity with state changes if the dispatch is asynchronous?

@jimmarino At the moment it can't achieve it, an event system needs persistence of the events to reach transactional atomicity, is something that at this point is not hard to implement (I would like to propose it for M6).
This issue/PR was proposed because these `pre-` methods are not used by anyone apparently.

**Comment by paullatzelsperger** [comment]
@jimmarino @ndr-brt ATM we only use a few of the `TransferProcessListener`'s pre-methods.
