### ISSUE TITLE
FsVault - Add Parsers to resolve keys as PrivateKeyWrapper class

### ISSUE THREAD

**Issue by cpeeyush** [eclipse-dataspaceconnector/DataSpaceConnector#1658]
## Description

[FsPrivateKeyResolver](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/9085e5e71e07b1e1eef05248dbff2c8d6b911e27/extensions/filesystem/vault-fs/src/main/java/org/eclipse/dataspaceconnector/core/security/fs/FsPrivateKeyResolver.java#L45) is missing parsers, which are necessary if we want to resolve private keys in different formats. 

## Why it is needed

This change helps in resolving private keys in different formats when using File System Vault by providing appropriate parsers.  For instance, in MVD when we use FileSystemVault for testing purpose there [IdentityDidCoreExtension](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/9085e5e71e07b1e1eef05248dbff2c8d6b911e27/extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/IdentityDidCoreExtension.java#L82) generates an exception as `FsPrivateKeyResolver.resolvePrivateKey` is not able to parse a ECKey from keystore to PrivateKeyWrapper.class

## Possible Fix
Add parsers implementation in FsVault.

**Comment by bscholtes1A** [comment]
Hi @cpeeyush 
this is the same issue as https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1618 

It is actually more complex I think, as the parser are basically converting a PEM into a key, while FSPrivateKeyResolver directly decodes PrivateKey from the keystore.

**Comment by cpeeyush** [comment]
Hi @bscholtes1A,

Yes, I did an initial implementation here https://github.com/agera-edc/DataSpaceConnector/pull/322. Take a look and feedback is welcome. We can improve it further if you see something. Thanks.

**Comment by bscholtes1A** [comment]
I tried something very similar here: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1644
but for some reason, it did not work at all when booting a real connector with the DID extension. For info I was creating the keystore like this:

~~~
openssl ecparam -name prime256v1 -genkey -noout -out key.pem
openssl ec -in key.pem -pubout -out key.public.pem
docker run -i danedmunds/pem-to-jwk:1.2.1 --public --pretty < key.public.pem > key.public.jwk
openssl.exe req -new -x509 -key key.pem -out cert.pem -subj "//C=$COUNTRY_CODE" -days 360
openssl.exe pkcs12 -export -inkey key.pem -in cert.pem -out cert.pfx -passout pass:eonaxdev -name "$PRIVATE_KEY_NAME"
~~~

Did you try to boot a connector with your code? If yes, could you please share how you built the keystore?
