### ISSUE TITLE
cleanup: remove unused `Asset` methods

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1694]
# Feature Request

Currently, the `Asset` class, that is composed by a set of properties, has some methods that describe some properties that are used only by tests and that could be removed, as, aside `id`, they are specific to use cases.
- `getName`
- `getVersion`
- `getContentType`

I have a doubt about the `getDescription` one as it is used by the `AssetToIdsResourceTransformer` to create an IDS `Resource`, but I'm not sure the knowledge about the name of the field should stay inside the `Asset` class, as this is strictly dependent to the IDS protocol.

## Which Areas Would Be Affected?
asset, core

## Why Is the Feature Desired?
to cleanup our domain classes

## Solution Proposal
remove the methods

## Type of Issue
cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
Version we don't need but name and content type we do, particularly for display in a UI.

**Comment by paullatzelsperger** [comment]
The `getDescription` should never have been used to create the IDS resource. However, it might still come in handy for UI purposes.

**Comment by ndr-brt** [comment]
Since the `properties` map is free-hand there are no limits on define new fields by the users, but I can't see why they should be in the `Asset` class as for our core domain model these properties are not useful, they are dependent from the context, so I would remove them and let them be handled e.g. by a UI.

> The `getDescription` should never have been used to create the IDS resource.
what should be the alternative in this case?

**Comment by jimmarino** [comment]
I'm fine with requiring the use of extensible properties. However, I believe IDS mandates a name and description. @juliapampus is that the case?

**Comment by juliapampus** [comment]
To the best of my knowledge, the `description` is not mandatory (? @PHochmann). However, it is an attribute that could be mapped from `Asset` to `ids:Resource`

**Comment by PHochmann** [comment]
dct:title and dct:description are not mandatory [1].
[1]: https://github.com/International-Data-Spaces-Association/InformationModel/blob/15e6d2fff83ba49ebdb7a1cd77418cd19ab28d26/testing/shared/DescribedShape.ttl#L43

**Comment by ndr-brt** [comment]
Just to recap:
- `id`: it is mandatory as used to reference the asset
- `name`: not mandatory but it should be mapped to ids "dct:title" (currently it's not)
- `description`: not mandatory but it should be mapped to ids "dct:description"
- `contentType`: needed to display in a UI
- `version`: not needed at all

Looking to the `ids:Resource` type I feel like we added these fields to provide a mapping between EDC and IDS, but since there's the IDS review goin' on, I would say to postpone this discussion. I close this issue for the moment
