### ISSUE TITLE
PolicyDefinition Is Created With Random ID 

### ISSUE THREAD

**Issue by zeier** [eclipse-dataspaceconnector/DataSpaceConnector#1698]
# Bug Report

## Describe the Bug

When creating a new policy using the `DataManagementAPI` (POST /policydefinitions), the policy is created with a random ID instead of the ID provided.

### Expected Behavior

The ID provided in the payload should be used to create the policy definition.

### Observed Behavior

A new random ID is generated, the ID provided in the payload is not used.

## Steps to Reproduce

1. Create a new policy using the `/policydefinitions` API and provide a policy ID in the payload.
2. Get all policies using the `/policydefinitions` GET API.
3. A new policy definition is created, which contains a different ID than the one provided in step 1.

## Context Information

Tested using the EDC openAPI definition and Postman as well as via the MVD DataDashboard on MVD instance: http://mvd145-company1-mvd.northeurope.azurecontainer.io/.

**Comment by ndr-brt** [comment]
Could you provide an example of the call? The identifier field on `PolicyDefinition` is `uid`, not `id` (that's probably not really crisp)

**Comment by jimmarino** [comment]
> Could you provide an example of the call? The identifier field on `PolicyDefinition` is `uid`, not `id` (that's probably not really crisp)

UID is for alignment with ODRL. We can change it to ID if it's clearer.

**Comment by jimmarino** [comment]
I think the EDC should determine the id, not the client (it's also POST). It also seems the result of the operation should return the ID of the created definition.

What is the case for allowing the client to decide the id?

**Comment by zeier** [comment]
> Could you provide an example of the call? The identifier field on `PolicyDefinition` is `uid`, not `id` (that's probably not really crisp)

This is the payload when we create a policy definition using the MVD (which uses the `DataDashboard`), the `uid` is set to `test-id`.

`{
    "policyDefinition": {
        "policy": {
            "type": "SET",
            "permissions": [
                {
                    "edctype": "dataspaceconnector:permission",
                    "uid": null,
                    "target": null,
                    "action": {
                        "type": "USE",
                        "includedIn": null,
                        "constraint": null
                    },
                    "assignee": null,
                    "assigner": null,
                    "constraints": [],
                    "duties": []
                }
            ],
            "prohibitions": [],
            "obligations": []
        },
        "uid": "test-id"
    },
    "policy": {
        "type": "SET",
        "permissions": [
            {
                "edctype": "dataspaceconnector:permission",
                "uid": null,
                "target": null,
                "action": {
                    "type": "USE",
                    "includedIn": null,
                    "constraint": null
                },
                "assignee": null,
                "assigner": null,
                "constraints": [],
                "duties": []
            }
        ],
        "prohibitions": [],
        "obligations": []
    }
}`

**Comment by ndr-brt** [comment]
> > Could you provide an example of the call? The identifier field on `PolicyDefinition` is `uid`, not `id` (that's probably not really crisp)
> 
> This is the payload when we create a policy definition using the MVD (which uses the `DataDashboard`), the `uid` is set to `test-id`.
> 
> `{ "policyDefinition": { "policy": { "type": "SET", "permissions": [ { "edctype": "dataspaceconnector:permission", "uid": null, "target": null, "action": { "type": "USE", "includedIn": null, "constraint": null }, "assignee": null, "assigner": null, "constraints": [], "duties": [] } ], "prohibitions": [], "obligations": [] }, "uid": "test-id" }, "policy": { "type": "SET", "permissions": [ { "edctype": "dataspaceconnector:permission", "uid": null, "target": null, "action": { "type": "USE", "includedIn": null, "constraint": null }, "assignee": null, "assigner": null, "constraints": [], "duties": [] } ], "prohibitions": [], "obligations": [] } }`

I think you are confusing `PolicyDefinition` uid (that's not set in this json) and the policy/permission/etc.. uid (that's set for the permissions in this json).


> I think the EDC should determine the id, not the client (it's also POST). It also seems the result of the operation should return the ID of the created definition.
> 
> What is the case for allowing the client to decide the id?

I pretty much agree with this, but having the possibility to "override" with a custom one is acceptable too and probably desired from a lot of companies

**Comment by zeier** [comment]
The payload is malformed, it contains a superfluous `policyDefinition`.

With a payload as the following one it works as expected (if the uid is provided, it is used, otherwise a uid is generated):

`{
    "policy": {
        "type":"SET",
        "permissions":[],
        "prohibitions":[],
        "obligations":[]
    },
    "uid":"test-policy22"
}`
