### ISSUE TITLE
Remove DataEntry class

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#170]
As discussed in #159 , the `DataEntry` class and `DataCatalogEntry` can be removed since are replaced by `Asset` and `DataAddress` respectively.
This should be done after #159 gets merged

**Comment by paullatzelsperger** [comment]
Totatlly agree with doing this, though I highly recommend doing this when there are only few other PRs open as the potential for a "merge hell" is quite high due to the widespread use of `DataEntry` :)
