### ISSUE TITLE
Replace `java-faker` dependency with `datafaker`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1709]
# Feature Request

Seems like `java-faker` it's not maintained anymore, according to the number of opened PRs on the repository:
https://github.com/DiUS/java-faker/pulls (currently 118)

and this comment on an issue on it:
https://github.com/DiUS/java-faker/issues/327#issuecomment-1170002244

The last release was on 2020.

We could replace it with datafaker:
https://github.com/datafaker-net/datafaker/
it's distributed under [apache license 2.0](https://github.com/datafaker-net/datafaker/blob/master/LICENSE)

## Which Areas Would Be Affected?
tests

## Why Is the Feature Desired?
avoid unmaintained libraries

## Solution Proposal
-

## Type of Issue
cleanup

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
> do we even need that faker lib? I mean, does it provide value other than generate randomized strings? In which case I would prefer having some internal `RandomStringUtils` lib

I'm not a fan of it but it is used pretty widely, an eventual deletion should be addressed by another issue, I proposed this as java-faker is currently blocking the upgrade of swagger dependencies

**Comment by jimmarino** [comment]
I'm not a fan of it either. Would it be a problem to just rip it out now? If so, maybe we can sub it using datafaker and create a new issue for the next milestone to remove it?

**Comment by paullatzelsperger** [comment]
> I'm not a fan of it but it is used pretty widely, an eventual deletion should be addressed by another issue, I proposed this as java-faker is currently blocking the upgrade of swagger dependencies

Ah I see. Ok then, let's temporarily sub it with data faker and remove it altogether in m6. Sound good?
