### ISSUE TITLE
DID: VerifiableCredentialFactory class name

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#1714]
# Feature Request

The class  has the doc *Convenience/helper class to generate, verify and deserialize verifiable credentials, which are, in fact, Signed JSON Web Tokens (JWTs).*

In fact the implementation is only based on DID and JWT, and does not contain any claims from the verifiable credentials data model. It is used for generating and validating short-lived authentication tokens in synchronous HTTP requests - and not for managing verifiable credentials, which will be done in other components (IdentityHub, MVD).

For clarity the class should be renamed to something like `DidJwtUtils`. The methods could be made non-static for better testability of dependent classes.

Trying to extend the class to also support the verifiable credential data model wouldn't seem to be a good idea, since there are specifics to usage as a web request token (audience, expiration, etc.)

## Which Areas Would Be Affected?
Identity DID

## Type of Issue
improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
+1 on renaming to JwtUtils (it also does not really pertain to DIDs). we could also move it directly next to the DecentralizedIdentityService, because that's the only class using it.
