### ISSUE TITLE
Remove `CHANGELOG.md`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1719]
# Feature Request

With the ability to auto-generate changelogs during a release in Github, and the usage of conventional commits, we don't need to manually create and update a Changelog anymore.
Thus, the `CHANGELOG.md` file can be deleted, and the related workflow to check the changelog can go away too.

## Which Areas Would Be Affected?
Build

## Why Is the Feature Desired?
Avoids pesky merge conflicts on almost _every_ commit.

## Solution Proposal
- delete `CHANGELOG.md`
- delete the `check-for-changelog-modifications` job in the `scan-pull-request.yaml` workflow
- delete the "added relevant details...." section from `PULL_REQUEST_TEMPLATE.md`
- remove the relevant section from `CONTRIBUTING.md`

## Type of Issue
improvement

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
Also the `added relevant details to the changelog? (skip with label no-changelog)` check should be deleted from the `PULL_REQUEST_TEMPLATE.md`

**Comment by paullatzelsperger** [comment]
> Also the `added relevant details to the changelog? (skip with label no-changelog)` check should be deleted from the `PULL_REQUEST_TEMPLATE.md`

you're right, i updated the description. thanks!

**Comment by juliapampus** [comment]
I think the Contributing.md has also a section about the changelog that should be removed @paullatzelsperger

**Comment by paullatzelsperger** [comment]
> I think the Contributing.md has also a section about the changelog that should be removed @paullatzelsperger

thanks, updated the description!
