### ISSUE TITLE
api: clearly separate "expected" exceptions from "unexpected" ones

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1730]
# Feature Request

Currently, the `EdcApiExceptionMapper`, it's the gateway to handle exceptions raised in the `jersey` context.
The mapper handles `EdcApiException`s and also other `java.lang.*` exceptions as:
- `IllegalArgumentException`
- `NullPointerException`
- `UnsupportedOperationException`

making them (at least the first 2) return a 4xx error code, that's, by definition, a "client error", so something that has been caused by the client, but, a NPE it's not a client fault, it's a server fault.

We need to clearly separate them and make all the `java.lang` "unexpected" exception return a 5xx error.

## Which Areas Would Be Affected?
api

## Why Is the Feature Desired?
To improve error handling and reporting

## Solution Proposal
Make all the `java.lang` exceptions return a 5xx error, maybe printing a `severe` log, to permit developers to signal the behavior as a bug.
The `IllegalArgumentException` should not be thrown in the api context, a more detailed `EdcApiException` should be used, that will make the server return an error detail that could be better interpreted by the client.

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
+1 on the distinction between "expected" and "unexpected" exceptions. That could have multiple `catch-throw` cascades as a consequence: for example a service would not need to know about an API exception - in its context an `IllegalArgumentException` or a `NullpointerException` are completely valid. We either have to use `(Service-)Result`s everywhere, or controllers need to wrap them in an `EdcApiException`
