### ISSUE TITLE
Custom validator for specific `AssetEntryDto` fields

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1736]
# Feature Request

Currently, on the `POST /assets` call, the validation act on the `data-management/asset` relies on the `jakarta-validation` annotations set on the `AssetEntryDto` class.
Since the `Asset` entity is composed by a free-form dictionary, it would be useful to have a way to extend a custom dataspace-specific validation (e.g. for a specific dataspace a certain information should be mandatory or have a particular format).

## Which Areas Would Be Affected?
data-management api

## Why Is the Feature Desired?
To give the possibility to specify a dataspace-specific validation for the `Asset` properties

## Solution Proposal
The simplest implementation could be to introduce a new `AssetEntryDtoValidator` service that would have a "no-op" default implementation and that it could be overrode by an implementation provided by extension.
This validator would be called on the controller before the `transformation` call, and return a 400 error if the validation returned a `failed` result.
This concept could be extended to the other api endpoints as well, but I would address this to other issues.

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
reopened - it was accidentally closed by the linke decision-record PR
