### ISSUE TITLE
Filtering assests fails with status code 400

### ISSUE THREAD

**Issue by Tintoiu-Anca** [eclipse-dataspaceconnector/DataSpaceConnector#1758]
# Bug Report

## Describe the Bug
When filtering the list of assets by a custom property added by myself I get 400.

### Expected Behavior
The request should return a 200 with the proper response (an asset or an empty list) regardless of the property used to filter and whether or not that property is present or not in the assets.

## Steps to Reproduce
1. Create an asset with the following property: "asset:prop:path": "/file" using the POST request http://localhost:8182/api/v1/data/assets
`{
    "asset": {
        "properties": {
            "asset:prop:id": "5",
            "asset:prop:path": "/file"
        }
    },
    "dataAddress": {
        "properties": {
            "type": "http",
            "url": "test.url"
        }
    }
}`
3. Now the list looks as follow: 
``   [{
        "properties": {
            "asset:prop:id": "5",
            "asset:prop:path": "/file"
        }
    }, 
    {
        "properties": {
            "asset:prop:id": "4"
        }
    }
] ``
4. Filter the list of assets based on that property like this: http://localhost:8182/api/v1/data/assets?filter=asset:prop:path=/file
5. See that the response is 400
`{
    "servlet": "EDC-data",
    "message": "Bad Request",
    "url": "/api/v1/data/assets",
    "status": "400"
}`

## Logs
This is the log from EDC:
DEBUG 2022-07-29T08:37:17.8330792 get all Assets from QuerySpec{offset=0, pageSize=50, filterExpression=[asset:prop:path = /file], sortOrder=null, sortField=null}

**Comment by ndr-brt** [comment]
currently only a set of "known properties" are permitted:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/501883cc32f7d390b1c3bbad562c551210dbfa88/extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetQueryValidator.java#L26-L32

this was done to avoid sql injections in the left part of the expression (ref. #1605)

currently custom validation of the query is not possible, but it can be implemented I'd say.

(ps: you can get the error detail in the response body)
