### ISSUE TITLE
sql: ContractNegotiation fails to retrieve the correct type

### ISSUE THREAD

**Issue by schoenenberg** [eclipse-dataspaceconnector/DataSpaceConnector#1766]
# Bug Report

## Describe the Bug

The behaviour is happening on EDCs with SQL extension. A saved ContractNegotiation will always return as of a `CONSUMER`-type.

The following snippet is failing to map the `ContractNegotiation.type` correctly:

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/2d4e89881aa7a867db3e1127771d619ad1b1a776/extensions/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractnegotiation/store/SqlContractNegotiationStore.java#L323-L340

### Expected Behavior

Reading a `ContractNegotiation` from the database matches the previously saved version.

### Observed Behavior

A `ContractNegotiation` is always from type `CONSUMER`

## Steps to Reproduce

1. Setup a connector with SQL extension
2. Do the necessary steps to get to a ContractAgreement
3. Query all ContractAgreements

## Context Information

- Used version: 2d4e89881aa7a867db3e1127771d619ad1b1a776

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation
_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

Adding this line to the above mentioned mapping function above is a quick fix, but does not check the value range: `.type(ContractNegotiation.Type.values()[resultSet.getInt(statements.getTypeColumn())])`

**Comment by paullatzelsperger** [comment]
thanks @schoenenberg. your solution is good, because any exception would bubble up the stack anyways.
