### ISSUE TITLE
Extend AssetIndex for Pagination/Cursoring

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#178]
Hello, everyone,

I assume the content AssetIndex might be too big to be used in one piece. If we make it accessible via IDS or another protocol it's necessary to limit the amount of processed assets per request.

I would therefore like to suggest:

- Create an **AssetIndexQuery** class with a **expression**, **limit** and a **cursor** property.
- Create an **AssetIndexResult**. That returns an **Cursor**, to continue the query, additionally to the returned **Assets**.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
Hello everyone,
sorry for the late reply. How about this:
- We change the parameter of the `AssetIndex` to `AssetIndexQuery`.
- `AssetIndexQuery` contains the `AssetSelectorExpression`,  a `Limit` of type *long* and a `Cursor` of type Cursor.
  - The `Limit` indicates the max. number of assets to return
  - The `Cursor` is uses for continuation
- Instead of a `Stream` the `AssetIndex` returns a `AssetIndexResult`.
- The `AssetIndexResult` inherits from `Iterable<Asset>` and may contain a `Cursor` for continuation.

**Comment by DominikPinsel** [comment]
I created a draft pull request
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/218

**Comment by jimmarino** [comment]
This has already been implemented
