### ISSUE TITLE
transfer process stopped working after update

### ISSUE THREAD

**Issue by kedorlaomer** [eclipse-dataspaceconnector/DataSpaceConnector#1781]
# Bug Report

## Describe the Bug
The commit [988215e7094778495938ff79e6bbfc038b9e8981](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/988215e7094778495938ff79e6bbfc038b9e8981) broke our usage of the API endpoints `/api/v1/data/transferprocess` and `/api/v1/data/catalog`.

### Expected Behavior
Afterwards, the endpoint `/api/v1/data/catalog` returns 200/OK and a benevolent JSON in its body.

### Observed Behavior
The endpoint returns 500/Internal Server Error and a HTML body stating Internal Server Error

## Steps to Reproduce
1. Start negotiation in order to get agreement and register asset (works)
2. Transfer process via `/api/v1/data/transferprocess` (which returns 200/OK)
3. Look for asset in catalog via `/api/v1/data/catalog`.

## Context Information

- Used version: 988215e7094778495938ff79e6bbfc038b9e8981 (also happens for as-of-now current 3ff940b720f44826df28e893fb31344eb6faacef)
- OS: Windows 10

## Detailed Description
The log gives stack trace  
> org.eclipse.dataspaceconnector.spi.EdcException: Received unexpected response type.
>	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.IdsMultipartSender.checkResponseType(IdsMultipartSender.java:332)
>	at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.IdsMultipartSender.lambda$send$0(IdsMultipartSender.java:210)
>	at org.eclipse.dataspaceconnector.ids.core.message.FutureCallback.onResponse(FutureCallback.java:45)

This error message is thrown already after `/api/v1/data/transferprocess`; the 500 of `/api/v1/data/catalog` is likely only a consequence.

**Comment by juliapampus** [comment]
I cannot reproduce the exception. I used sample 4.0 to test the negotiation and transfer and thought that it may be because the IDS object mapper is used for payload de/serialization in `MultipartEndpointDataReferenceRequestSender` but not in `EndpointDataReferenceHandler`. However, this seems not to be the issue.

As with commit [c38d744](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/c38d7443922b93f5fb099d8586cef60cd263a3c8) the response type check was introduced, the connector now does not handle `RejectionMessages` as "okay", as it did before. In this course, we also recognized some failing tests etc. that checked for a response, but not for a successful one. @bscholtes1A Any other idea why the transfer could fail? I guess the "unexpected response type" is a `RejectionMessage`. 

I propose to open up a PR that resets the `ObjectMapper` in the `MultipartEndpointDataReferenceRequestSender` and detail the "Received unexpected response type." log message. But I am not sure that this will help.

**Comment by juliapampus** [comment]
@kedorlaomer Can you maybe provide some more information about what DPF and transfer protocol you are using?

**Comment by kedorlaomer** [comment]
It is a `RejectionMessage`. I don't know yet where it originates.

**Comment by kedorlaomer** [comment]
I can send you a recording of our use of these endpoints:

[rejected-flow.txt](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/files/9348439/rejected-flow.txt)
[negotiation-flow.txt](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/files/9348440/negotiation-flow.txt)

The communication in the file seems OK, although I'm a bit concerned about the POST request to `/api/v1/data/transferprocess`: Why does `dataDestination` have an empty `"type"`? Do you think this is to be blamed?

In any case, we can see that it is a `RejectionMessage` by the `connector`.

**Comment by kedorlaomer** [comment]
I think, I can pinpoint the problem quite clearly: The consumer POSTs to `/api/v1/ids/data` something like

        {
          "ids:recipientConnector": [
            {
              "@id": "http://localhost:8282/api/v1/ids/data"
            }
          ],
          "ids:modelVersion": "4.1.3",
          "ids:issued": {
            "@value": "2022-08-16T11:16:13.104+02:00",
            "@type": "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
          }, ...

and receives a HTTP/200 with a multipart response encapsulating a `DescriptionResponseMessage` and a `ConnectorEndpoint` statement:

        {
          "ids:hasDefaultEndpoint": {
            "@type": "ids:ConnectorEndpoint",
            "@id": "https://w3id.org/idsa/autogen/connectorEndpoint/41b9999c-0257-4739-9029-1a3aafd9e194",
            "ids:accessURL": {
              "@id": "https://example.com"
            }
          },
          "ids:securityProfile": {
            "@id": "https://w3id.org/idsa/code/BASE_SECURITY_PROFILE" ...

This object has a field  `"ids:resourceCatalog"` which contains a `"ids:offeredResource"` list. That list does not have a `"@type"` field. The JSON parser does not find the `"@type"` and therefore does not know which object type to generate. This yields a stack trace such as

        org.eclipse.dataspaceconnector.spi.EdcException: Could not deserialize connector self-description: Could not resolve subtype of [simple type, class de.fraunhofer.iais.eis.Resource]: missing type id property '@type' (for POJO property 'ids:offeredResource')
         at [Source: (byte[])"{"ids:hasDefaultEndpoint":{"@type":"ids:ConnectorEndpoint","@id":"https://w3id.org/idsa/autogen/connectorEndpoint/41b9999c-0257-4739-9029-1a3aafd9e194","ids:accessURL":{"@id":"https://example.com"}},"ids:securityProfile":{"@id":"https://w3id.org/idsa/code/BASE_SECURITY_PROFILE"},"ids:resourceCatalog":[{"ids:offeredResource":{"objectList":[{"ids:contractOffer":[{"ids:permission":[{"ids:target":{"@id":"urn:artifact:asset-for-asset-management"},"ids:action":[{"@id":"https://w3id.org/idsa/code/USE","[truncated 2388 bytes]; line: 1, column: 2869] (through reference chain: de.fraunhofer.iais.eis.BaseConnectorImpl["ids:resourceCatalog"]->java.util.ArrayList[0]->de.fraunhofer.iais.eis.ResourceCatalogImpl["ids:offeredResource"]->java.lang.Object[0])
                at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartCatalogDescriptionRequestSender.getBaseConnector(MultipartCatalogDescriptionRequestSender.java:146)
                at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.MultipartCatalogDescriptionRequestSender.getResponseContent(MultipartCatalogDescriptionRequestSender.java:114)
                at org.eclipse.dataspaceconnector.ids.api.multipart.dispatcher.sender.IdsMultipartSender.lambda$send$0(IdsMultipartSender.java:205)
                at org.eclipse.dataspaceconnector.ids.core.message.FutureCallback.onResponse(FutureCallback.java:45)
                at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by kedorlaomer** [comment]
This can be reproduced in an even simpler way:

1. Start two connectors
2. Call the catalog endpoint via
            curl -v 'http://localhost:9192/api/v1/data/catalog/?providerUrl=http://localhost:8282/api/v1/ids/data'
   where localhost:9192 is the IDS endpoint and localhost:8282 is the data endpoint

**Comment by kedorlaomer** [comment]
I tried [PR 1790](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1790/commits/eb4fea4228919202d1a9d3265bac90fd8f44d905) and it did not solve the problem.

I found the following: When `JsonLdSerializer` tries to serialise a `de.fraunhofer.iais.eis.BaseConnector`, it correctly adds a `@type` annotation. But when recursing down to serialise the `de.fraunhofer.iais.eis.ResourceCatalog`, it uses a `BeanSerializer` instead of the correct `JsonLdSerializer` (which knows how to add the `@type`/`@context` annotation) which does not add `@type` annotations to its children (e. g. the `ids:offeredResource` where the error occurs). I did not dig further into how the serialiser is being passed down the chain, but I'm convinced the error is in that area.

**Comment by kedorlaomer** [comment]
After a lot of debugging, the reason was found to be incompatible versions of Fraunhofer's infomodel. This led to a `ResourceCatalog` which contained values that the new serialiser was not equipped to serialise. Therefore, the more generic `BeanSerializer` was used instead, leading to the observed `RejectionMessage`. We solved this by adapting our own version of the infomodel. Thank you, @juliapampus for your help!
