### ISSUE TITLE
Missing next tutorial link in tutorials

### ISSUE THREAD

**Issue by egekorkan** [eclipse-dataspaceconnector/DataSpaceConnector#1822]
The tutorial under samples (e.g. https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/samples/03-configuration/README.md) do not link to the next tutorial. So I have to go back to https://eclipse-dataspaceconnector.github.io/DataSpaceConnector/#/overview/hands-on or navigate the repo to find the next one. It would be nice to simply link next tutorial from each readme.

I can follow it up with a PR if you agree it would be nice.

Note: I am aware that this is a bit of nitpick issue

**Comment by mspiekermann** [comment]
hey @egekorkan sounds good to me!

**Comment by juliapampus** [comment]
We restructured the documentation. Should be easier to navigate through the samples now: https://eclipse-dataspaceconnector.github.io/docs/#/submodule/Connector/samples/ @egekorkan

**Comment by egekorkan** [comment]
Sorry for not doing a PR already, I am just back from vacation. 

@juliapampus inclusion into a proper docs template is indeed nicer. However, there are still no "next" links and the sidebar menu does not actually follow the tutorials? It stays at `Connector` which is actually not the current page. 

![image](https://user-images.githubusercontent.com/20195407/188941436-c37a1418-057b-4f93-87f2-e4703baca186.png)

I am guessing that this is a bug and I can open a separate issue for it. I am using Firefox btw.
