### ISSUE TITLE
Project structure: introduce `token-spi` module

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1834]
# Feature Request

As reported in #1832 , `common/token-generation-lib` and `common/token-validation-lib` contain interfaces that are actually implemented by extensions, so probably they deserve to be put in an `spi` module.

This new `token-spi` module will contain:
- `JwtDecorator`
- `JwtDecoratorRegistry`
- `TokenValidationRule`

As these 3 interfaces are being implemented by different modules

## Which Areas Would Be Affected?
common, spi

## Why Is the Feature Desired?
cleanup

## Solution Proposal
-

## Type of Issue
cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by bscholtes1A** [comment]
maybe should be more generic than `token-spi`. 

I would see instead a `security-spi`, containing a subfolder `token-spi`.

As detailed in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1357 there are some duplicated stuff between the token validation/generation libs and what some code in DID identity core (key wrappers,...)

Thus this would be a good opportunity to later put this common stuff into this `security-spi` module.

**Comment by ndr-brt** [comment]
@bscholtes1A I'm on this but to me is not that clear what should be the right design to follow. I will create a PR to accomplish this specific issue, better relate to the other for the refactoring you proposed.
