### ISSUE TITLE
Contributors don't have permissions enough to add labels to PRs

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1843]
@ndr-brt looks like I don't have permission to apply a label..

_Originally posted by @iwasakims in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1830#issuecomment-1218033986_

Since now it's mandatory to add labels to the PR would be good if everyone could do it

**Comment by mspiekermann** [comment]
Some permissions require adding contributors to the EF project (see list below): https://projects.eclipse.org/projects/technology.dataspaceconnector. Unfortunately, this has to be done manually and requires that people have an active EF account (where I need some additional information than the GH name). This obviously didn't happen for @iwasakims, so I will take care of it asap next week (I'll be ooo next days).

**Comment by iwasakims** [comment]
I can apply labels to issues/PRs now. Assigning issues to myself works too. Thanks, @mspiekermann and @ndr-brt.
