### ISSUE TITLE
explore how relation between feature and service can be expressed

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#186]
We'd like to make it more obvious which services get registered as part of an extension / a feature.
So far we have the rough idea that an annotation at services can help to express the related feature name.
Feature names can then be used to express "provides" and "requires" sets.

<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
I think this has been completed as part of the refactoring work. I'll close out. If there are remaining items, we can open specific issues for them.
