### ISSUE TITLE
OAuth2ServiceImpl: check fingerprinting against DAPS endpoint

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#187]
In the current `OAuth2ServiceImpl` a fingerprint is created, because that's required by Active Directory Endpoints. 
We should make sure that this fingerprint doesn't pose a problem for the DAPS endpoint, or if DAPS requires another fingerprint.

One way to do this is to implement an IntegrationTest that issues the request against the DAPS dev endpoint:
```properties
daps.token.url=https://daps.aisec.fraunhofer.de/v2/token
```
let's just be careful not to spam that endpoint with requests :)

**Comment by jimmarino** [comment]
@paullatzelsperger has this been resolved?

**Comment by paullatzelsperger** [comment]
Yup I think so.

**Comment by bscholtes1A** [comment]
> @paullatzelsperger has this been resolved?

Yeap and an integration test has shown it was working fine.

Thus is can be closed.
