### ISSUE TITLE
Project structure: Move `common/*` modules to `core/common/` folder

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1884]
# Feature Request

`util` and `state-manchine-lib` are `common` libraries, but they are also `core` modules, and probably we don't need that `common` folder anymore.
Since `state-machine-lib` is the only `-lib` module, I would remove that suffix.

## Which Areas Would Be Affected?
common, core

## Why Is the Feature Desired?
project structure review

## Solution Proposal
-

## Type of Issue
cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by juliapampus** [comment]
The `ids-jsonld-serdes` has the `-lib` suffix as well. I think we can get rid of this anyways, also for the serdes module.
