### ISSUE TITLE
Data Plane Transfer Sync: Update behavior for missing `edc.transfer.proxy.token.verifier.publickey.alias` setting

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1889]
# Bug Report

## Describe the Bug

If the user does not of the existence of the setting `edc.transfer.proxy.token.verifier.publickey.alias`, therefore has not prepared something for its default value in the vault, the EDC will log:

```
`SEVERE: Error booting runtime
java.lang.NullPointerException: Failed to resolve public key secret with alias: null
    at java.base/java.util.Objects.requireNonNull(Objects.java:233)
    at
<more stacktrace>
```

Without looking at the code the user has no idea that went wrong.

### Expected Behavior

- if a setting is missing or something can not be found in the vault the user should know this by looking at the logs

### Observed Behavior
- logged message does not indicate which setting or vault alias is missing

## Steps to Reproduce
1. Do not configure `edc.transfer.proxy.token.verifier.publickey.alias`
2. Set `edc.transfer.proxy.token.signer.privatekey.alias` to 'foo-private'
3. Put a private key in the values with alias `foo-private`
4. Do not put a public key in the vault with alias `foo-private-pub`
5. Start the EDC

## Detailed Description

Logging comes from this method

```java
private KeyPair createKeyPair(ServiceExtensionContext context) {
        var config = context.getConfig();

        var privateKeyAlias = config.getString(TOKEN_SIGNER_PRIVATE_KEY_ALIAS);
        var privateKey = privateKeyResolver.resolvePrivateKey(privateKeyAlias, PrivateKey.class);
        Objects.requireNonNull(privateKey, "Failed to resolve private key with alias: " + privateKeyAlias);

        var publicKeyAlias = config.getString(TOKEN_VERIFIER_PUBLIC_KEY_ALIAS, privateKeyAlias + "-pub");
        var publicKeyPem = vault.resolveSecret(publicKeyAlias);
        Objects.requireNonNull(publicKeyPem, "Failed to resolve public key secret with alias: " + publicKeyPem);
        var publicKey = PublicKeyParser.from(publicKeyPem);
        return new KeyPair(publicKey, privateKey);
    }
```

## Possible Implementation

Solution 1:

Just fix the error message by replacing `publicKeyPem` with `publicKeyAlias` to fix the error message.

Solution 2:

Remove the default value and let the user always configure the setting.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
Personally I would go for solution 2, since the private key alias must be explicit, I don't see any reason against having to be explicit on the public one too.
