### ISSUE TITLE
Core: Connector not starting, OAuth2Extension cannot resolve certificates

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1892]
# Bug Report

## Describe the Bug

When starting the EDC the `OAuth2Extension.getEncodedClientCertificate` always throws an `org.eclipse.dataspaceconnector.spi.EdcException: Public certificate not found` exception.

### Expected Behavior
- Connector starting and resolving certificates from vault

### Observed Behavior
- Connector not starting

## Steps to Reproduce
1. Start IDS Connector

## Context Information
_Add any other context about the problem here._

- Used version 0.0.1-20220818-SNAPSHOT

## Detailed Description

- Extension is always using the `NoopCertificateResolver`

## Possible Implementation

- Probably the `DefaultCertificateResolver` should be used instead

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
If you use a vault custom extension you need to explicitly register the `VaultCertificateResolver`.
For an example, look at the `hashicorp-vault` extension:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/common/vault/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultExtension.java#L75

**Comment by DominikPinsel** [comment]
> If you use a vault custom extension you need to explicitly register the `VaultCertificateResolver`.
> For an example, look at the `hashicorp-vault` extension:
> https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/common/vault/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorpvault/HashicorpVaultExtension.java#L75

With our custom extension everything works fine. Our problem occurs with the Azure Vault extension from this repository, but I assume the HashiCorp vault extension from this repository has this problem, too.
But I just saw that you fixed this issue 7 days ago in PR #1842  -> will close this issue.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>
