### ISSUE TITLE
test: enable integration tests against real S3

### ISSUE THREAD

**Issue by iwasakims** [eclipse-dataspaceconnector/DataSpaceConnector#1899]
# Feature Request

Integration based on AbstractS3Test are assuming `http://localhost:9000` (provided by minio) as endpoint. It would be nice if we can run integration tests against real S3 endpoint based on test time configuration.

## Which Areas Would Be Affected?

test, S3

## Why Is the Feature Desired?

bugs related to specific S3 settings/regions could be found by running tests against real S3.

## Solution Proposal

switching endpoint URI based on the environment variables.

## Type of Issue

improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
We've asked our friends at AWS to do this but have not had much traction.

**Comment by iwasakims** [comment]
I submitted PR #1951 for running tests against S3 using my own AWS credential from my local environment.
