### ISSUE TITLE
Integrate Google Cloud Storage

### ISSUE THREAD

**Issue by benjamin-fleischmann** [eclipse-dataspaceconnector/DataSpaceConnector#1908]
# Feature Request
Add extension to support Google Cloud Storage (GCS)

## Which Areas Would Be Affected?
new extension (DPF)

## Why Is the Feature Desired?
Google Cloud Storage (GCS) is the object storage on Google Cloud Platform. This will enable users of Google Cloud to participate in data spaces.

## Solution Proposal
GCS specific implementations for the DPF (provisioner, sink, source)

## Type of Issue
new feature

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
@jimmarino is this completed? It seems that only the DR was provided, but actually we miss the implementation

**Comment by benjamin-fleischmann** [comment]
Hi, the implementation will follow. We are working on it.

**Comment by ndr-brt** [comment]
ok, so I will open the issue again
