### ISSUE TITLE
Feature: Remove cache from `Cosmos*Store`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#1953]
# Feature Request

The `CosmosContractDefinitionStore` and the `CosmosPolicyDefinitionStore` currently uses an in-mem cache for CRUD operations and querying. this was originally implemented to have an easy way to execute queries, because they were simply converted into `Predicate`s. Back then, we didn't have a native Cosmos/SQL query framework. Now, that that's been implemented (cf. `CosmosContractNegotiationStore#queryNegotiations`), we should use that.

Also, if we need caching at all, we should do so in a generic, configurable and re-usable way, as proposed in #1173.

## Which Areas Would Be Affected?
Cosmos*Store + Test

## Why Is the Feature Desired?
Executing queries against the cache has limitations compared to the actual Cosmos backend, because it cannot handle collection types, only scalars. Also, we're not expecting high-volume traffic against that store, so the cache really is not needed anymore.

## Solution Proposal
Simply rip out the cache, and let every request hit the Cosmos API directly.

## Type of Issue
Cleanup

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
edit: include `CosmosPolicyDefinitionStore`

**Comment by wolf4ood** [comment]
I guess this one can be closed since the two sub tasks #1965 and #1964 are completed
