### ISSUE TITLE
BaseRuntime.boot() print boot error details 

### ISSUE THREAD

**Issue by ma3u** [eclipse-dataspaceconnector/DataSpaceConnector#1960]
# Bug Report for the EDC MVD boot process

## Describe the Bug
Install the MVD locally. Followed the [Local Development Setup](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace#local-development-setup) and [Local Test Execution](https://github.com/eclipse-dataspaceconnector/MinimumViableDataspace/blob/main/system-tests/README.md#local-test-execution) instructions.

Command `docker-compose -f system-tests/docker-compose.yml up --build` failed, after azurite, did-server, did-server started successfully because fail to start company1,2,3 with the error `SEVERE: Error booting runtime`

`org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.boot(boolean addShutdownHook)` print the very general message in the log in the function `onError(e)`.  

### Expected Behavior

The EDC operator need the full error message in the log file. 

### Observed Behavior

Today the EDC operator doesn't know the reason, why  the EDC didn't start, when the addShutdownHook is true. He needs more information like missing extensions or failed healthchecks. 

A developer locally needs to debug the EDC installation to get the full error message. It's nearly impossible to start the debugging, because the docker container shutdown under 1s. 

During the debugging the BaseRuntime.boot() method throw  `org.eclipse.dataspacecopnnector.core.security.azure.AzureVaultException: Either 'edc.vault.certificate' or 'edc.vault.client' ...`

## Steps to Reproduce

Missing java lib Gradle extension. or wrong enviroment variable `DuseFsVault` during the gradlew build.  

Same result in in OSX, Windows11, Ubuntu 22.04 on WSL, after cleaning the local build cache. 

## Possible Implementation

 `org.eclipse.dataspaceconnector.boot.system.runtime.BaseRuntime.onError(Exception e) ` need to print out the origin error message to the logs

It's nearly impossible to start the debugging, because the docker container shutdown under 1s.  Need a delay of 5s before `System.exit(-1)`

**Comment by jimmarino** [comment]
A couple of things:

1. Did you check the console log of the Docker container? Can you post that?
2. If you want to debug remotely against a Java container, use the suspend option when launching the JVM in the container and you won't need to worry about the container shutting down before you can attach the debugger
3. It's not possible to determine if an extension is "missing". The dependency resolver should list any missing dependencies. Where you missing a depency?

**Comment by ma3u** [comment]
the reason was a missing space. 


`docker container logs <containerid>`

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2022-09-13 16:33:07.516Z ERROR c.m.applicationinsights.agent -
*************************
ApplicationInsights Java Agent 3.2.11 failed to start (PID 1)
*************************

Description:
No connection string or instrumentation key provided

Action:
Please provide connection string or instrumentation key.

Listening for transport dt_socket at address: 5005
2022-09-13 16:33:07 WARNING : Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring.
2022-09-13 16:33:07 INFO : Initialized FS Configuration
2022-09-13 16:33:07 SEVERE : Error booting runtime
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2022-09-13 18:01:02.595Z ERROR c.m.applicationinsights.agent -
*************************
ApplicationInsights Java Agent 3.2.11 failed to start (PID 1)
*************************

Description:
No connection string or instrumentation key provided

Action:
Please provide connection string or instrumentation key.

Listening for transport dt_socket at address: 5005
2022-09-13 18:01:02 WARNING : Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring.
2022-09-13 18:01:02 INFO : Initialized FS Configuration
2022-09-13 18:01:03 SEVERE : Error booting runtime
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2022-09-16 05:37:26.065Z ERROR c.m.applicationinsights.agent -
*************************
ApplicationInsights Java Agent 3.2.11 failed to start (PID 1)
*************************

Description:
No connection string or instrumentation key provided

Action:
Please provide connection string or instrumentation key.

Listening for transport dt_socket at address: 5005
2022-09-16 05:37:26 WARNING : Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring.
2022-09-16 05:37:26 INFO : Initialized FS Configuration
2022-09-16 05:37:26 SEVERE : Error booting runtime
