### ISSUE TITLE
Contract Requestor validates contract content against contract provider

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1975]
# Bug Report

## Describe the Bug

The contract requestor makes a policy validation of the contract content against the contract provider. If the contract provider does not pass it's own policies it is not possible to successfully negotiate a contract with it.

For example this makes it impossible to create policies that limit the number of connectors using a policy, if it would not pass it's own policy. 

Possible Workarounds:
- add these kinds of policy only to the AccessPolicy in the ContractDefinition, but not the the ContractDefinition
- ~create contract policies in a way, that a contract providing connector is able to pass it's own policy, too.~ <small>not possible anymore, see #2026</small>

### Expected Behavior

- there is no policy check from the contract consumer against the contract provider

### Observed Behavior

- contract consumer checks whether contract provider passes it's own policies

## Steps to Reproduce

Create the following policy:

```bash

curl -X POST "$CONTRACT_PROVIDER/data/policydefinitions" \
    --header 'X-Api-Key: password' \
    --header 'Content-Type: application/json' \
    --data '{
               "id": "1",
                "policy": {
                    \"uid\": \"1\",
                    \"prohibitions\": [],
                    \"obligations\": [],
                    \"permissions\": [
                        {
                            \"edctype\": \"dataspaceconnector:permission\",
                            \"action\": { \"type\": \"USE\" },
                            \"target\": \"1\",
                            \"constraints\": [
                                {
                                    \"edctype\": \"AtomicConstraint\",
                                    \"leftExpression\": {
                                    \"edctype\": \"dataspaceconnector:literalexpression\",
                                    \"value\": \"OnlyForConnectorWithId\"
                                    },
                                    \"rightExpression\": {
                                    \"edctype\": \"dataspaceconnector:literalexpression\",
                                    \"value\": \"FooConnectorId\"
                                    },
                                    \"operator\": \"EQ\"
                                }
                            ]
                        }
                    ]
                }
            }' \
    -s -o /dev/null -w 'Response Code: %{http_code}\n'

```

Initiate the contract negotiation

```bash
curl -X POST "$CONTRACT_CONSUMER/data/contractnegotiations" \
        --header "X-Api-Key: password" \
        --header "Content-Type: application/json" \
        --data "{ \
                    \"connectorId\": \"foo\",
                    \"connectorAddress\": \"$CONTRACT_PRIVIDER/api/v1/ids/data\",
                    \"offer\": {
                        \"offerId\": \"1:foo\",
                        \"assetId\": \"1\",
                        \"policy\": {
                            \"uid\": \"1\",
                            \"prohibitions\": [],
                            \"obligations\": [],
                            \"permissions\": [
                                {
                                    \"edctype\": \"dataspaceconnector:permission\",
                                    \"action\": { \"type\": \"USE\" },
                                    \"target\": \"1\",
                                    \"constraints\": [
                                         {
                                          \"edctype\": \"AtomicConstraint\",
                                          \"leftExpression\": {
                                          \"edctype\": \"dataspaceconnector:literalexpression\",
                                          \"value\": \"OnlyForConnectorWithId\"
                                          },
                                          \"rightExpression\": {
                                          \"edctype\": \"dataspaceconnector:literalexpression\",
                                          \"value\": \"FooConnectorId\"
                                          },
                                          \"operator\": \"EQ\"
                                      }
                                    ]
                                }
                            ]
                        }
                    }
                }" \
    -s | jq 
```

## Context Information

Used commit `‹658c5e31a›`, but bug should also exist on the main branch.

## Detailed Description

From `ConsumerContractNegotiationManagerImpl.java`:

```java
/**
     * Tells this manager that a previously sent contract offer has been confirmed by the provider. Validates the
     * contract agreement sent by the provider against the last contract offer and transitions the corresponding
     * {@link ContractNegotiation} to state CONFIRMED or DECLINING.
     *
     * @param token         Claim token of the consumer that send the contract request.
     * @param negotiationId Id of the ContractNegotiation.
     * @param agreement     Agreement sent by provider.
     * @param policy        the policy
     * @return a {@link StatusResult}: FATAL_ERROR, if no match found for Id or no last offer found for negotiation; OK otherwise
     */
    @WithSpan
    @Override
    public StatusResult<ContractNegotiation> confirmed(ClaimToken token, String negotiationId, ContractAgreement agreement, Policy policy) {
        
        // skipped code

        var result = validationService.validate(token, agreement, latestOffer);

        // more skipped code

        return StatusResult.success(negotiation);
    }
```

From `ContractValidationServiceImpl.java`

```
@Override
    public boolean validate(ClaimToken token, ContractAgreement agreement, ContractOffer latestOffer) {
        // TODO implement validation against latest offer within the negotiation
        var contractIdTokens = parseContractId(agreement.getId());
        if (contractIdTokens.length != 2) {
            return false; // not a valid id
        }

        var agent = agentService.createFor(token);
        return policyEngine.evaluate(NEGOTIATION_SCOPE, agreement.getPolicy(), agent).succeeded();
    }
```

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
I think the consumer validation shouldn't be removed, as the provider could have changed it, and should result in a counter-offer.

Could be a solution to use the "IN" operator and add both the provider and the consumer ids in the right value?

**Comment by DominikPinsel** [comment]
> I think the consumer validation shouldn't be removed, as the provider could have changed it, and should result in a counter-offer.
> 
> Could be a solution to use the "IN" operator and add both the provider and the consumer ids in the right value?

Hm.. I think the problem is that the contract is intended for the consumer. So the idea is that the consumer is able to fulfill the conditions of the contract.
I would assume that it is not required, that the provider fulfills the same conditions, too.

**Comment by ndr-brt** [comment]
So the proposal would be to remove the validation on the consumer side since the policy was defined by the provider and it needs to be verified only by the provider against the consumer and not other way around.

I guess the equality validation has to <s>kept in place</s> added as the consumer needs to verify that no changes have been applied by the provider on the policy (otherwise it would be like a counter-offer. 

Does this make sense?

**Comment by DominikPinsel** [comment]
> So the proposal would be to remove the validation on the consumer side since the policy was defined by the provider and it needs to be verified only by the provider against the consumer and not other way around.
> 
> I guess the equality validation has to kept in place added as the consumer needs to verify that no changes have been applied by the provider on the policy (otherwise it would be like a counter-offer.
> 
> Does this make any sense?

Yes :) This does make sense.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>
