### ISSUE TITLE
Feature: make all the DataManagementApi POST resource return id of the created resource

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#1984]
# Feature Request

Currently, the POST resources of `/transferprocess` and `/contractnegotiations` return the `id` of the created resource.
This should be done also on `/assets`, `contractnegotiations` and `/policydefinitions`, as the id could be created by the connector if not provided in the request

## Which Areas Would Be Affected?
data management api

## Why Is the Feature Desired?
improve api

## Solution Proposal
-

## Type of Issue
enhancement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by haseeb-xd** [comment]
I have started my work on this. Will make a PR.
