### ISSUE TITLE
Catalog: Single invalid ContractDefinition breaks whole Catalog

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1985]
# Bug Report

## Describe the Bug

A single invalid contract definition breaks the whole catalog. The catalog providing connector will always answer with a 500 Internal Server Error response.

### Expected Behavior

- Connector logs invalid contract definition, but still returns offers for all valid contract definitions

### Observed Behavior

- Catalog functionality breaks with invalid contract definition

## Steps to Reproduce

1. Create invalid contract definition (for example by using old criteria syntax)

```bash
curl -X POST "${CONNECTOR}/data/contractdefinitions" \
    --header "X-Api-Key: password" \
    --header "Content-Type: application/json" \
    --data '{
                "id": "1",
                "criteria": [
                    {
                        "left": "asset:prop:id",
                        "op": "=",
                        "right": "1"
                    }
                ],
                "accessPolicyId": "1",
                "contractPolicyId": "1"
            }'
```

2. Request Catalog

## Context Information

Used commit `‹658c5e31a›`, but issue should also exist on the main branch.

## Detailed Description

-

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

**Comment by ndr-brt** [comment]
The issue could be fixed improving the `ContractDefinitionRequestDto` input validation, since now it's not checking that the criteria is actually correctly valued.
