### ISSUE TITLE
refactor: remove unused parameters from dispatcher interfaces

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-dataspaceconnector/DataSpaceConnector#1986]
# Feature Request

The `send` methods in the interfaces `RemoteMessageDispatcher` and `RemoteMessageDispatcherRegistry` have 3 parameters (a class representing the response type, a `RemoteMessage` and a `MessageContext`). Currently, both interfaces are only implemented for the IDS multipart protocol and these implementations only use the `RemoteMessage`. Therefore, the other two parameters should be removed from both interfaces.

## Which Areas Would Be Affected?
spi, ids, tests using a fake implementation of either interface

## Why Is the Feature Desired?
to not have unused parameters

## Type of Issue
cleanup

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
@ronjaquensel Can we leave those in, as I have plans to implement an alternative messaging protocol?

**Comment by ronjaquensel** [comment]
@jimmarino sure, then I'll close this issue
