### ISSUE TITLE
[Eclipse] Include LICENSE and NOTICE file in every jar

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#20]
Suggest to include those file in every jar, even if we just distribute those as part of the fat jar inside the docker container.
see https://www.eclipse.org/projects/handbook/#legaldoc-distribution
 
something like that inside build.gradle allprojects section should solve it:

```
tasks.jar {
            metaInf {
                from("${rootProject.projectDir.path}/LICENSE")
            }
        }
```

<sub> Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
@paullatzelsperger is this handled by #314, and if so, can we close it?

**Comment by paullatzelsperger** [comment]
Yup it is.
