### ISSUE TITLE
Connector blocks negotiation every time when constraint contains an array

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#2026]
# Bug Report

## Describe the Bug

When the right expression of a constraint contains multiple elements, the connector will reject the contract offer every time.

### Expected Behavior

- Connector does not reject contract offer for constraints that contain multiple elements every time.

### Observed Behavior

- Connector does reject contract offer for constraints that contain multiple elements every time.

## Steps to Reproduce

1. Create a policy with an array as right expression

```sh
curl -X POST "${CONNECTOR_URL}/data/policydefinitions" \
    --header 'X-Api-Key: password' \
    --header 'Content-Type: application/json' \
    --data '{
               "id": "3",
                "policy": {
                    "prohibitions": [],
                    "obligations": [],
                    "permissions": [
                        {
                            "edctype": "dataspaceconnector:permission",
                            "action": { "type": "USE" },
                            "constraints": [
                                {
                                "edctype": "AtomicConstraint",
                                "leftExpression": {
                                    "edctype": "dataspaceconnector:literalexpression",
                                    "value": "RegionPolicy"
                                },
                                "rightExpression": {
                                    "edctype": "dataspaceconnector:literalexpression",
                                    "value": [ "de", "it" ]
                                },
                                "operator": "IN"
                                }
                            ]
                        }
                    ]
                }
            }' \
    -s -o /dev/null -w 'Response Code: %{http_code}\n'
```

2. Create all the other objects so that its possible to negotiate a contract for the policy
3. Initiate a contract negotiation that should pass / contains the exact same policy

## Context Information

Commit `740c100ac162bc41b1968c232ad81f7d739aefa9`

```
commit 740c100ac162bc41b1968c232ad81f7d739aefa9 (HEAD -> main)
Author: Ronja Quensel <72978761+ronjaquensel@users.noreply.github.com>
Date:   Fri Sep 23 11:42:59 2022 +0200

    feat: add toBuilder for resource definitions (#1992)
    
    * feature: add toBuilder for resource definitions
    
    * chore: set builder properties in declaring classes
    
    * refactor: refactor toBuilder methods
    
    * chore: add toBuilder to new test definition
```

## Detailed Description

It looks like the issue is in the PolicyEquality.java class, that treats the value of the rightExpression one time as array type and one time as string type. In comparison they are then always different.

```java
    @Override
    public boolean test(Policy one, Policy two) {
        var oneTree = mapper.<ObjectNode>valueToTree(one);
        var twoTree = mapper.<ObjectNode>valueToTree(two);
        // TODO: target is excluded from the equality as it's not possible to map it to the current IDS implementation: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1791
        oneTree.remove("target");
        twoTree.remove("target");
        return oneTree.equals(twoTree);
    }
```

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

**Comment by DominikPinsel** [comment]
> Hi @DominikPinsel
> 
> i did a debug session, and it's not an equality issue but more that the information about the right expression being an array is lost when going through the ids protocol consumer -> provider.
> 
> Let me check if i can find a way to fix this
> 
> Thanks

Perfect :) Thanks a lot!

**Comment by ndr-brt** [comment]
I would say that "literal expression" is meant to represent literal expressions, so arrays are not going to work.
Currently there's no support for "array/list" expressions, and this support is missing from the IDS InfoModel as well, so I would say that this is not actually a bug but a missing feature, that will likely be implementable with the new IDS protocol.
Am I correct @jimmarino ?

To have this issue completed the proposal could be to have a validation that ensures the value field of a literal expression to be a `String`.

**Comment by jimmarino** [comment]
Sorry I should have seen this earlier. Taking a look at this, I agree with @ndr-brt, a literal should be a string. @DominikPinsel you should be able to achieve what you want using an OrContraint that composes AtomicContraints with literal expressions.

**Comment by DominikPinsel** [comment]
@jimmarino @ndr-brt Alright :) Thanks for the support. Then I will close this issue

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>
