### ISSUE TITLE
Sample 04-file-transfer references hard-coded local path

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#203]
Running the sample results in
```
SEVERE 2021-11-03T06:33:46.678772 Fatal error processing transfer request: 9870b389-c037-4420-b5a4-769e1a45bd07. Error details: source file /home/paul/Documents/test-document.txt does not exist!
```

This is caused by:

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/e03a38582b7865444680eb99a2d0473a69dc7fc8/samples/04-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java#L57

**Comment by paullatzelsperger** [comment]
The docs clearly state that this needs to be changed to fit your local dev environment.

**Comment by DominikPinsel** [comment]
Maybe it would be an idea to throw an exception in case no path was set. Just to support the documentation and to prevent confusion in case someone didn't read it.

**Comment by algattik** [comment]
How about having the path as configuration? Then we could pass it via command line, the doc and usage would be clearer
