### ISSUE TITLE
`ContractOffer.assetId` field is not used

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#2030]
# Feature Request

the `assetId` field of the `ContractOffer` class is not used by anyone, nor read nor wrote. 
Actually that information is kept into the `asset` field.
The proposal is to remove the `assetId` field to avoid misunderstanding (I tried more than once to get the id from that field... failing miserably!)

## Which Areas Would Be Affected?
spi

## Why Is the Feature Desired?
cleanup

## Solution Proposal
-

## Type of Issue
-

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by jimmarino** [comment]
Can we keep this for now as this may change with the new IDS protocol work?

**Comment by ndr-brt** [comment]
> Can we keep this for now as this may change with the new IDS protocol work?

Since it may change in a way that we are not really aware of, I would remove it in the meantime, as we aren't really aware of how the new protocol will be, furthermore `ContractOffer` is not a transport class but is part of our domain so at the end it is independent from the protocol.

**Comment by jimmarino** [comment]
This is an area I am actively looking into now with IDS, but no problem to remove it for the time being since we can add it back in once the IDS protocol is simplified.
