### ISSUE TITLE
Provide a default `DataSourceRegistry`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#2032]
# Feature Request

Currently it's mandatory to add a `transaction-*` dependency when a `sql` database implementation is used, since the `DataSourceRegistry` is registered only by those extensions.
Since we have a `NoopTransactionContext` that's being registered by default when no other implementations are provided, we should have the same for the `DataSourceRegistry`, without having to force the user to introduce a transaction manager (e.g. in test environment)

## Which Areas Would Be Affected?
default services

## Why Is the Feature Desired?
improve developer experience

## Solution Proposal
-

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by wolf4ood** [comment]
Hi @ndr-brt i could work on this, just a quick question

where would you put the default impl for `DataSourceRegistry`?

i was thinking in `common-sql` but i may be wrong

Thanks

**Comment by ndr-brt** [comment]
@wolf4ood yes, I was thinking about that, the only issue that I'm seeing is that there would be the need to move all the `transaction-local` related stuff to `common-sql` as well, or an alternative could be to make `common-sql` to define `transaction-local` as dependency and make the latter provide `TransactionContext` and `DataSourceRegistry` by default, so they could eventually be replaced by another implementation (e.g. atomikos) if needed.

**Comment by wolf4ood** [comment]
@ndr-brt  by default  you mean by marking `isDefault` 
`TransactionContext` and `DataSourceRegistry` of `transaction-local`?
