### ISSUE TITLE
Fix first interaction workflow

### ISSUE THREAD

**Issue by juliapampus** [eclipse-dataspaceconnector/DataSpaceConnector#2054]
# Bug Report

## Describe the Bug
The first interaction workflow recently causes errors. The bug seems to be known and documented in [this issue](https://github.com/actions/first-interaction/issues/101).

### Expected Behavior
Not fail.

### Observed Behavior
Fails, see [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/runs/3196538241) for an example.

## Possible Implementation
Deactivate action and wait for a new release. If this cannot be expected in the long term, we could replace the action by [another one](https://github.com/TylerLeonhardt/first-interaction-pwsh).

**Comment by juliapampus** [comment]
Current status:

![image](https://user-images.githubusercontent.com/72392527/194313523-c3b74dea-7d82-4895-b146-16e3cfe021a2.png)

**Comment by ndr-brt** [comment]
It seems that the fix was released yesterday: https://github.com/actions/first-interaction/issues/101#issuecomment-1270291422

**Comment by juliapampus** [comment]
@ndr-brt Let's wait for Dependabot on monday, it should detect the update.
