### ISSUE TITLE
Wrong maven artifactId for dataaddress-resolver-memory

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#207]
This seems to be a copy-paste error. As it generates a duplicate artifact it causes a conflict on maven publish.

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/56a6bc1f62bf316d9414980605ee0bf938333293/extensions/in-memory/dataaddress-resolver-memory/build.gradle.kts#L25

**Comment by jimmarino** [comment]
Hey @algattik would you be able to submit a PR for this?

**Comment by paullatzelsperger** [comment]
i think this has become obsolete since #199 is already merged.
