### ISSUE TITLE
Datamanagement API: implement `POST` endpoints for query

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#2072]
# Feature Request

Currently many endpoints of the DataManagement API use `GET` endpoints to obtain collections of items, for example `GET /assets`. 
These endpoints accept the properties of a `QuerySpecDto` as query parameters using the `@BeanParam` deserialization feature.

We should switch over to using endpoints that follow the `POST /<resource>/request` pattern, and accept the `QuerySpecDto` as request body.

## Which Areas Would Be Affected?
Data Management API

## Why Is the Feature Desired?
Currently the `QuerySpecDto#filter` field is only capable of handling _one_ filter expression, whereas the `QuerySpec` is able to handle multiple. 
Transmitting a JSON string as query param is cumbersome - it is easier to just transmit it via request body.

## Solution Proposal
- deprecate the current `GET /<resource>` endpoints
- add new endpoint `POST /<resource>/request` 
- add a `List<Criterion> filterExpression` field to `QuerySpecDto` and deprecate `QuerySpecDto#filter`
- transmit the `QuerySpecDto` as request body
- `CatalogApi` only: A `POST` endpoint was already introduced in #2060, so in order to stay consistent we only need to revert to having the `providerUrl` as query parameter and put only the  `QuerySpecDto` in the body 

## Type of Issue
refactoring

## Subtasks
- [ ] `AssetApi`
- [ ] `CatalogApi`
- [ ] `ContractAgreementApi`
- [ ] `ContractDefinitionApi`
- [ ] `ContractNegotiationApi`
- [ ] `PolicyDefinitionApi`
- [ ] `TransferProcessApi`

_[edit] as this is very similar work for all the APIs, I would do all of it in one PR_

## Checklist

- [ ] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by florianrusch-zf** [comment]
Which benefits would we get from this? As far as I can remember, all requests to "fetch" a resource from an API were GET calls. 🤔 Do you have maybe examples, where this requests are POST calls?

**Comment by paullatzelsperger** [comment]
I think the PR description clearly outlines the reasons: currently the filter expression can only be _one_ `key=value` string, due to how the mapping is done from the `QuerySpecDto` -> `QuerySpec`. Encoding multiple of these filter expressions, or a JSON string in a query param is error prone and cumbersome and it could potentially leak information. There's a better solution available, which is transmitting a `List<Criterion>` in the request body.

As the [HTTP Protocol Specification Section 9.3](https://www.rfc-editor.org/rfc/rfc2616#section-9.3) states, GET requests can have a body, but cannot be used to influence the response:

> The GET method means retrieve whatever information ([...]) is identified by the Request-URI.

 Thus, `POST` is the way to go, if we want the API and IDS to have feature parity with regards to query capabilities, which it should IMO.

**Comment by florianrusch-cluetec** [comment]
Thanks for the detailed explanation! :-) That makes things a little clearer for me.

**Comment by florianrusch-zf** [comment]
Thanks for the detailed explanation! :-) That makes things a little clearer for me.
