### ISSUE TITLE
Persistent DataPlaneInstanceStore

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#2073]
# Feature Request

Support for persistent DataPlaneInstanceStore.

## Which Areas Would Be Affected?
Data Plane Selector.

## Why Is the Feature Desired?
Currently the DataPlaneSelector only supports an in memory version of DataPlaneInstanceStore. As a consequence, whenever a selector is restarted, all stored DataPlaneInstances are lost.

## Solution Proposal
As done for most stores in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector, two extensions will be provided:

- one for SQL databases,
- one for CosmosDB.

## Type of Issue
Improvement.

## Checklist

- [ ] #2074
- [x] #2075

**Comment by wolf4ood** [comment]
Closing this since both sub-issues are done
