### ISSUE TITLE
Refactor and better document `ContractValidationService`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#2077]
# Feature Request

I propose the following changes in the `ContractValidationService`:

- rename `Result<ContractOffer> validate(ClaimToken token, ContractOffer offer);` --> `Result<ContractOffer> validateInitialOffer(ClaimToken token, ContractOffer offer);` and document clearly that is intended to be used on provider side, when the first offer arrives
- rename `boolean validate(ClaimToken token, ContractAgreement agreement);` --> `Result<Void> validateAgreement(ClaimToken token, ContractAgreement agreement);` and document clearly that it is intended to be used on provider side, upon receiving a transfer request. 
- Also document, which side the `ClaimToken` represents
- Further explain, what "sanitized" means in this context. To that end, I would add a `@return` javadoc item that states, that in fact a newly created `ContractOffer` is to be returned instead of the original one, and why that is necessary.

## Which Areas Would Be Affected?
contract negotiation

## Why Is the Feature Desired?
Currently the `ContractValidationService` has multiple overloads for `validate`. In addition to having different return types and arguments (which is OK for overloads), but they also have different semantics. These are not obvious from either the method name nor are they documented clearly, which makes it difficult to understand.

## Type of Issue
refactoring, cleanup, documentation

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
Totally agree, it could also be refactored to a composite pattern, this will make it more clear and modulable.
