### ISSUE TITLE
Strip whitespaces from property settings and environment variables

### ISSUE THREAD

**Issue by domreuter** [eclipse-dataspaceconnector/DataSpaceConnector#2101]
# Feature Request

The current implementation of the configuration regarding the properties or environment variables also allows trailing or ending whitespaces, that could end up in malformed behaviour or crashing the connector at all.

## Which Areas Would Be Affected?
core-util

## Why Is the Feature Desired?
Some properties including whitespaces could lead to malformed behaviour of several extensions, others are just throwing exceptions during startup.

**Examples: (\*indicates a whitespace)**

Whitespaces in url properties
Will end up in a java.lang.IllegalArgumentException trying to map to an URI
edc.oauth.token.url=https://daps1.int.demo.catena-x.net/token****

Whitespaces in privateKey name property 
Will end up in a java.lang.NullPointerException: privateKey is marked non-null but is null
edc.oauth.private.key.alias=daps_key.pkcs8***

If the related property belongs to a specific extension the error will occur when the respective property will be addressed within the extension during runtime. 

If the property belongs to a base component inside the connector the error will prevent the connector from a proper boot up.

Please feel free to reproduce the behaviour on your own by inserting some whitespaces to some properties.

## Solution Proposal
To prevent that and keep the originated pattern, eg. key=value, i suggest to get rid of trailing or ending whitespaces at his point.

## Type of Issue
feature / improvement

**Comment by ndr-brt** [comment]
Hi, could you better detail the issue reporting the stacktrace?
In my opinion changing the configuration settings at runtime it's not a good practice, as, in the case that a leading/trailing whitespace is actually required by some extension, this would be a problem.

To fix the issue, to avoid such exception when a token is required, I suggest to add a URL validation for the `edc.oauth.private.key.alias` setting at the extension initialization, so if that's not a correct URL the EDC shouldn't start, because it would be an user error that's not meant to be fixed by EDC.

**Comment by domreuter** [comment]
It is quite hard to bring up a specific stacktrace at this point, cause whitespaces in different properties will lead to different stacktraces. Therefore I mentioned two examples in the description. 

If i get you right there is the need of an additional "validation" process for each extension required. During initialization the extension needs to provide a kind of input validation regarding the needed properties and their respective types.

Lets assume we have such an additional step by hand, what would be the default behaviour in case of an invalid configuration? Preventing to boot up the connector with a respective error message?

**Comment by ndr-brt** [comment]
> It is quite hard to bring up a specific stacktrace at this point, cause whitespaces in different properties will lead to different stacktraces. Therefore I mentioned two examples in the description.
> 
> If i get you right there is the need of an additional "validation" process for each extension required. During initialization the extension needs to provide a kind of input validation regarding the needed properties and their respective types.
> 
> Lets assume we have such an additional step by hand, what would be the default behaviour in case of an invalid configuration? Preventing to boot up the connector with a respective error message?

In fact a lot of extensions already validates the configuration (e.g. `IdsMultipartApiServiceExtension` with the connectorId setting), so it's up to every extension to ensure that the settings provided are valid. 
No need of an "additional" validation layer, just a check in the extension `initialize` phase.
In case of invalid configuration, the connector won't start, requiring to fix the error in the settings.

In fact I never used any application that cleaned up my settings, they are pretty much failing at start or, at worst, lazily

**Comment by domreuter** [comment]
Okay, then it would be nice to see some of these principles in place.

Most of the extensions are not doing any kind of validation atm, but following the principles they need to.

How can we ensure that extensions are doing a validation on their intialize phase? Ideas welcome :-)
