### ISSUE TITLE
ExceptionMappersIntegrationTest fails when building from newest version

### ISSUE THREAD

**Issue by abazatte** [eclipse-dataspaceconnector/DataSpaceConnector#2141]
# Bug Report

## Describe the Bug
i cloned the repository and ran the gradlew.bat clean build and got 1 failed test. 

ExceptionMappersIntegrationTest
shouldListJakartaValidationMessageInResponseBody()

I have attached the full errormessage.

[Exception.txt](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/files/9870974/Exception.txt)

**Comment by abazatte** [comment]
Hi @wolf4ood 

thanks for your reply.

do u know how i could change it so its not localized anymore and in english?

**Comment by wolf4ood** [comment]
@abazatte  could you try to append this parameters in the build command?

```
-Duser.language=en
```

**Comment by abazatte** [comment]
thank you the build worked.

**Comment by ndr-brt** [comment]
thanks for reporting, something that could be fixed but definitely not a bug, labeled this as `flaky test`. 
Could you provide a PR to address this?
