### ISSUE TITLE
Add `canGenerate` method on `Consumer`/`Provider` `ResourceDefinitionGenerator`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#2143]
# Feature Request

Currently it's up to the implementation of the `ResourceDefinitionGenerator` decide if the `ResourceDefinition` needs to be generated.
This could be handled in a different way, like it has been done on the `Provider` interface: adding a method that states if a certain request needs to have a resource generated or not. This will make the API and the implementation breezier.

## Which Areas Would Be Affected?
transfer

## Why Is the Feature Desired?
refactoring

## Solution Proposal
Add a method with this interface to the generator
```java
boolean canGenerate(DataRequest dataRequest, Policy policy);
```

Then on the `ResourceManifestGenerator` it will be used to filter out the generators:
```java
var definitions = consumerGenerators.stream()
                .filter(generator -> generator.canGenerate(dataRequest, policy))
                .map(generator -> generator.generate(dataRequest, policy))
                .collect(Collectors.toList());
```

## Type of Issue
refactoring

**Comment by jimmarino** [comment]
+1 we should be careful to note that an explicit design is to allow multiple resource generates to be engaged as opposed to just one (as is the case with other canXXX() methods).
