### ISSUE TITLE
Move custom JUnit annotations

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-dataspaceconnector/DataSpaceConnector#2157]
# Feature Request

Currently we have custom junit annotations as testFixture in `core:common:util`. Since we have a specific module for JUnit stuff
in `extensions:common:junit` it could make sense to move those annotations there,  instead of `core:common:util`

## Which Areas Would Be Affected?

All tests using custom annotations

## Why Is the Feature Desired?

To centralize all JUnit related extensions

## Solution Proposal

Create a package `org.eclipse.edc.junit.annotations` in `extensions:common:junit` and move all the annotations  currently located in the package `org.eclipse.edc.util.testfixtures.annotations` in the testFixtures of `core:common:utils`.

It would make sense also to move the entire module `extensions:common:junit` in `core:common:junit` since a lot of core modules depend on it.

## Type of Issue
improvement, cleanup

**Comment by wolf4ood** [comment]
@ndr-brt @paullatzelsperger 

wdyt about moving `extensions:common:junit` in `core:common:junit`  ?

**Comment by ndr-brt** [comment]
> @ndr-brt @paullatzelsperger
> 
> wdyt about moving `extensions:common:junit` in `core:common:junit` ?

I'm in
