### ISSUE TITLE
Provide clear coding guidelines

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#2160]
# Feature Request

We should provide a document in which we clearly outline the most important Java coding guidelines that contributors must adhere to.
By that I mean things that cannot be enforced through a checkstyle check or an IntelliJ style. As a starting point for a discussion I would propose

- General Code Style
  - use `var` instead of explicit types (helps clarity)
  - avoid `final` in method args and local variables
  - use `final` in field declarations
  - avoid `static` fields except in constants or when absolutely necessary. (you should be able to provide a reason).
  - use `interfaces` as containers for constants
  - use "minimally required types" (or "smallest possible API"), e.g. use `ObjectMapper` instead of `TypeManager`, `String` instead of an object containing the String, etc.
  - use either `public` members, which are documented and tested, or `private` members.
  - avoid package-private members if only needed for testing
  - avoid `protected` members unless they're intended to be overridden.
  - use package-private classes if they're not needed outside the package, e.g. implementation classes
  - avoid using `enum`s for anything other than named integer enumerations.
  - avoid using static classes as much as possible. Exceptions to this are helper functions and test utils, etc.
  - avoid any kind of variable prefixes, no underscores, no `m_` for members, etc.
  - avoid unnecessary `this.` (exception: in builders)
  - use static imports, as long as it is still clear what's being done. For example, use `of(item1, item2).map(it -> it.someOperation)...` instead of `Stream.of(item1, item2)`, or `format("...",arg1)` instead of `String.format("...", arg1)`. Helps with clarity and readability.
  - avoid `Optional` as method return type or method argument. 
  - avoid cryptic variable names, especially in long methods. Instead, try to write them out, at least to a reasonable extent.
  
- Testing
  - avoid testing multiple things in a single test methods, unless they're really simple, like SerDes.
  - use `[METHOD]_when[CONDITION]_should[EXPECTATION]` naming scheme for test methods, e.g. `verifyInput_whenNull_shouldThrowNpe()`
  - use test functions classes to provide common helper methods, e.g. to instantiate an object
  

- Builders:
   - use the Builder pattern when:
     1. there are any number of optional constructor args
     2. there are more than 3 constructor args
     3. the object should be serializable
     4. inheriting from an object that fulfills any of the above. In this case use derived builders as well.
   - Builders are to be named just `Builder` and should be static nested classes.
   - create a `public static Builder newInstance(){ ... }` method, which is used to instantiate the builder.
   - use single-field builders: a `Builder` instantiates the object it builds in its constructor, and sets the properties in its builder methods. The `build()` method then only performs verification [optional] and returns the instance.
   - use `private` constructors for the objects that the Builder builds
   - use Jackson annotations on Builders only

## Which Areas Would Be Affected?
Documentation

## Why Is the Feature Desired?
Having a clearly defined coding guideline will help us in keeping a homogenous and consistent code base. 

## Solution Proposal
Create a documentation item, that is referenced from the contribution guidelines.

## Type of Issue
documentation

**Comment by ndr-brt** [comment]
>   * use static imports, as long as it is still clear what's being done. For example, use `of(item1, item2).map(it -> it.someOperation)...` instead of `Stream.of(item1, item2)`, or `format("...",arg1)` instead of `String.format("...", arg1)`. Helps with clarity and readability.

As I stated in the other PR, I think this could actually make everything less clear, totally ok on using static imports for something that's really explicit (e.g. `Assertions.assertThat` -> `assertThat`), but `Stream.of` it should remain explicit, also because then no other `of` method could be imported statically in the same class (e.g. `Optional.of`, `Pair.of`).

I think there are some code guidelines also in this document that could be moved under the same page: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/developer/architecture/architecture-principles.md
