### ISSUE TITLE
Remove "Type of issue" from feature request template

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#2196]
# Feature Request

Remove the "Type of issue" part from the `feature_request.md` issue template, as this is something that should be addressed to the issue labels

## Which Areas Would Be Affected?
ci

## Why Is the Feature Desired?
Simplify the template

## Solution Proposal
-

## Type of Issue
:)

**Comment by MaverickDe** [comment]
Hi , can i get assigned to this issue

**Comment by ndr-brt** [comment]
@MaverickDe hi, I already opened a PR #2199
