### ISSUE TITLE
[Build] Define Java version in Gradle

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#22]
We should set a fixed java language version. Best would be to stick to latest LTS, i.e. java11.
Applies for gradle builds and docker file creation.

<sub> Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
Hi @DominikPinsel, I assigned you to this, I hope that is OK :-)
