### ISSUE TITLE
Mocking framework choice

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#220]
This is more like a question. There are valid reasons why we are using EasyMock as mocking framework?
I think it should be replaced for those reasons:
* every mock needs the call of the `replay` method
* `void` methods require that `expectLastCall()` that's not that easy to read at first (it tooks me some time to get it)
* the behaviour setting and the behavior verification are made in the same place (at `expect`), and that makes the tests less readable.

I used [Mockito](https://github.com/mockito/mockito) a lot, and it resolves all these points I listed in a more clever way than other mocking frameworks I used.

**Comment by DominikPinsel** [comment]
+1

**Comment by jimmarino** [comment]
The reason we use EasyMock is that it is a popular framework that gets the job done. Mockito is another good framework, but given all of the other work on our plate and the issues you outline are stylistic preferences, I don't see a need to burn cycles on this.

**Comment by ndr-brt** [comment]
Seems like other committers agree with my point of view, this substitution could happen step by step with small PRs, one for every extension, that can be implemented when we have some half hours waiting for code reviews, I would not spare on simple refactorings that help the team to working better, actually I think that a better mocking framework could motivate developers to write more (and better) tests.

**Comment by jimmarino** [comment]
I don't have a preference for which mock framework to use. My concern is a practical one: switching mocking frameworks will require a significant change to many areas of the codebase and it will require the people who are familiar with the tests to review and verify all of those changes. Having a piece-by-piece solution will likely lead to the changeover never being completed, resulting in multiple approaches to testing.

Do we have time for this in the near term?  If not, maybe we can revisit this issue at some point in the future?
