### ISSUE TITLE
Fix flaky integration tests

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#221]
Hello everyone,

the integration tests are failing fairly often during the PullRequests builds. It would be nice of someone could have a look at them.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
Related to #54

**Comment by paullatzelsperger** [comment]
I have a sneaking suspicion that many of them either:
- do not use randomized strings (f. buckets, containers, etc.) 
- employ sufficiently defensive measures (timeouts, etc.) 

I can take this issue since I wrote most of the I-tests.

**Comment by paullatzelsperger** [comment]
There are a few issues and PRs linked to this: 
- Issue #360 that resulted in #389 (BlobStore) and #377 (AWS S3)
- Issue #398: small typo
Let's revisit this issue once the above mentioned stuff gets merged and perhaps close it

**Comment by ndr-brt** [comment]
New error on the Daps test side:
```
Command failed: rm -rf "/home/runner/work/DataSpaceConnector/DataSpaceConnector/extensions"
rm: cannot remove '/home/runner/work/DataSpaceConnector/DataSpaceConnector/extensions/iam/daps/src/test/resources/config': Permission denied
rm: cannot remove '/home/runner/work/DataSpaceConnector/DataSpaceConnector/extensions/iam/daps/src/test/resources/keys': Permission denied
```

I found this: https://github.com/actions/checkout/issues/211
I will open a PR accordingly (PS: seems like the `${{ github.workspace }}` binding works, so I will include it)

**Comment by ndr-brt** [comment]
the reset permission fix worked, now we have another error:
```
org.eclipse.dataspaceconnector.spi.EdcException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:4567
```
this is strange because the daps server seems to start but seems not reachable

**Comment by paullatzelsperger** [comment]
Did you try running the test in a container (as opposed to: directly in the runner) and accessing daps through the hostname provided by docker networking?
