### ISSUE TITLE
Milestone 7 in Maven Central depends on local snapshot of GradlePlugins

### ISSUE THREAD

**Issue by kedorlaomer** [eclipse-dataspaceconnector/DataSpaceConnector#2227]
# Bug Report

## Describe the Bug
EDC's release 0.0.1-milestone-7 in Maven Central depends on `runtime-metamodel` in a `SNAPSHOT` version. This cannot be resolved and therefore, the library cannot be used without a local build of GradlePlugins.

### Expected Behavior
The library should build from Maven Central.

### Observed Behavior
Consider the module `asset-index-sql`. According to its [.pom](https://search.maven.org/remotecontent\?filepath\=org/eclipse/edc/asset-index-sql/0.0.1-milestone-7/asset-index-sql-0.0.1-milestone-7.pom), it declares a dependency

```xml
    <dependency>
      <groupId>org.eclipse.edc</groupId>
      <artifactId>runtime-metamodel</artifactId>
      <version>0.0.1-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
```

This can only build if there is a local snapshot build of `runtime-metamodel`. Maven Central does not have the `runtime-metamodel` (yet).

## Steps to Reproduce

Try to build EDC on a system with a clean local maven repository. Observe how many modules (not just `asset-index-sql`) fail due to an unmet dependency.

## Context Information

- Used version: 0.0.1-milestone-7
- OS: Windows 10

## Detailed Description

A build without a locally built `runtime-metamodel` results in the following (slightly edited) log:

```
 > Could not find org.eclipse.edc:runtime-metamodel:0.0.1-SNAPSHOT.
     Searched in the following locations:
       - file:$HOME/.m2/repository/org/eclipse/edc/runtime-metamodel/0.0.1-SNAPSHOT/maven-metadata.xml
       - file:$HOME/.m2/repository/org/eclipse/edc/runtime-metamodel/0.0.1-SNAPSHOT/runtime-metamodel-0.0.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/eclipse/edc/runtime-metamodel/0.0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/eclipse/edc/runtime-metamodel/0.0.1-SNAPSHOT/runtime-metamodel-0.0.1-SNAPSHOT.pom
       - https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/org/eclipse/edc/runtime-metamodel/0.0.1-SNAPSHOT/maven-metadata.xml
       - https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/org/eclipse/edc/runtime-metamodel/0.0.1-SNAPSHOT/runtime-metamodel-0.0.1-SNAPSHOT.pom
     Required by:
         project :provider > org.eclipse.edc:iam-mock:0.0.1-milestone-7
         project :provider > org.eclipse.edc:control-plane-core:0.0.1-milestone-7
         project :provider > org.eclipse.edc:catalog-api:0.0.1-milestone-7
         project :provider > org.eclipse.edc:contract-spi:0.0.1-milestone-7
         [snip ... most of EDC]
```

## Possible Implementation

There is two possible solutions:

1. Publish a version of GradlePlugins containing a recent `runtime-metamodel` on Maven Central
2. Change EDC's published dependencies to point to some other place which contains a recent `runtime-metamodel`.

**Comment by paullatzelsperger** [comment]
the root `build.gradle.kts` adds the Sonatype Snapshot repo to all subprojects.
```kotlin
//line 60:
val snapshotUrl = "https://oss.sonatype.org/content/repositories/snapshots/"

//line 128:
allprojects {
    repositories {
        mavenLocal()
        maven {
            url = uri(snapshotUrl)
        }
        mavenCentral()
        maven {
            url = uri("https://maven.iais.fraunhofer.de/artifactory/eis-ids-public/")
        }
    }
    // ...
}
```

I just verified that it can be resolved just fine. You can look at the snapshot repo [directly](https://oss.sonatype.org/#nexus-search;gav~org.eclipse.edc~runtime-metamodel~~~~kw,versionexpand).

I would advise to clear the local maven cache and gradle cache, and then rebuild your project with the `--refresh-dependencies` flag.
