### ISSUE TITLE
Replace `VerificationResult` with `Principle` to evaluate claims

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#228]
Hello everyone,

currently the `VerificationResult` is passed after creation to other classes, so that these classes may evaluate the containing claims. It would be better if the passed data only contains the claims, as the `VerificationResult` contains more information.
Therefore this issue includes the creation of a `Principal` class, that contains the claims, and replace the `VerificationResult` with it.

Some classes where the `VerificationResult` needs to be replaced:
- [ContractOfferFrameworkQuery](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/6435207156e2a07f7a93a1916396dfa893c3dd94/spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/ContractOfferFrameworkQuery.java#L24)
- [ContractOfferQuery](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/6435207156e2a07f7a93a1916396dfa893c3dd94/spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/ContractOfferQuery.java#L30)
- [IDS Handler](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/6435207156e2a07f7a93a1916396dfa893c3dd94/data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/handler/Handler.java#L39)
- [Connector Service](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/6435207156e2a07f7a93a1916396dfa893c3dd94/data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/ConnectorService.java#L33)
- [Data Catalog Service](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/6435207156e2a07f7a93a1916396dfa893c3dd94/data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/service/DataCatalogService.java#L18)

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by jimmarino** [comment]
FYI, I will handle this in #227 with ParticipantAgent except for the IDS Handler. What does the IDS Handler require?

**Comment by DominikPinsel** [comment]
It just needs the claims from the request, to pass them through to classes like the `ContractOfferFramework`.

**Comment by jimmarino** [comment]
OK, let's discuss in the context of #227. The ClaimsToken can be passed to ContractOfferService, which in turn will delegate to create a ParticipantAgent.
