### ISSUE TITLE
Create EDC `Contract` domain object

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#229]
Hello everyone,

we are currently missing a `Contract` domain object. This object should represent a `ContractOffer` two parties have agreed upon. 

I'd like to use this issue to discuss how an initial implementation could look like and then create the corresponding PR for it.

What do you think about this?

```java
public interface Contract {
    @NotNull String getId();

    @NotNull URI getProvider();

    @NotNull URI getConsumer();

    @NotNull ZonedDateTime getContractSigningDate();

    @NotNull ZonedDateTime getContractStartDate();

    @NotNull ZonedDateTime getContractEndDate();

    @NotNull List<Asset> getAssets();

    @Nullable Policy getPolicy();

    @Nullable ContractDocument getContractDocument();
}

```

The `Policy` represents contract details in ODRL, whereas the `ContractDocument` may contain the text of a human readable contract document. I assume both properties are optional, but a correct contract should contain at least one of them.

---
Current State:

```java
public class Contract {
    @NotNull String getId();

    @NotNull URI getProvider();

    @NotNull URI getConsumer();

    @NotNull ZonedDateTime getContractSigningDate();

    @NotNull ZonedDateTime getContractStartDate();

    @NotNull ZonedDateTime getContractEndDate();

    @NotNull List<Asset> getAssets();

    @Nullable Policy getPolicy();
}

```

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
> related to #230

**Comment by jimmarino** [comment]
Can we use UTC epoch long for dates? I think that is fairly common practice for APIs and it will make things easier for serialization since we won't have to concern ourselves with making sure we enforce ISO formatting for that.

**Comment by jimmarino** [comment]
One other question: what is a ContractDocument?

**Comment by jimmarino** [comment]
Sorry, one final comment, why is this an interface, I think it should be a class?

**Comment by DominikPinsel** [comment]
Thanks for your feedback.

- the ContractDocument would contain the plain text of a real world contract. Just in case someone doesn't want to use ODRL
- changed the interface to class

I'm not sure about the dates as long. Serializing a date object for a domain object seems fine for me.

**Comment by jimmarino** [comment]
> Thanks for your feedback.
> 
> * the ContractDocument would contain the plain text of a real world contract. Just in case someone doesn't want to use ODRL
> * changed the interface to class
> 

Can we keep this out for now? I think we should discuss whether this is really required and what such a ContractDocument would contain. As a start, does IDS support this?

> I'm not sure about the dates as long. Serializing a date object for a domain object seems fine for me.

Let's discuss this. It's standard practice to use longs and it makes things a lot easier.

**Comment by DominikPinsel** [comment]
> Can we keep this out for now? I think we should discuss whether this is really required and what such a ContractDocument would contain. As a start, does IDS support this?

IDS supports it, but I'm not sure whether anyone uses it. I removed it for now.

> Let's discuss this. It's standard practice to use longs and it makes things a lot easier.

I've got the feeling, that writing a string as date is how everyone does it. I wasn't able find a long vs string discussion in the internet, to find some pro and con arguments. The only thing could I find is this StackOverflow comment https://stackoverflow.com/a/47037409

**Comment by jimmarino** [comment]
> > Can we keep this out for now? I think we should discuss whether this is really required and what such a ContractDocument would contain. As a start, does IDS support this?
> 
> IDS supports it, but I'm not sure whether anyone uses it. I removed it for now.
> 
> > Let's discuss this. It's standard practice to use longs and it makes things a lot easier.
> 
> I've got the feeling, that writing a string as date is how everyone does it. I wasn't able find a long vs string discussion in the internet, to find some pro and con arguments. The only thing could I find is this StackOverflow comment https://stackoverflow.com/a/47037409

We need to standardize dates on UTC and not leave it open. Using epoch-based timestamps is very common, for example, see the description of the NumericDate type in the JWT specification (it uses epoch seconds instead of millis, but the concept is the same):

https://datatracker.ietf.org/doc/html/rfc7519

This will make dealing with dates and timestamps throughout the codebase much easier and less error-prone.

**Comment by DominikPinsel** [comment]
Then let's use long 👍

**Comment by DominikPinsel** [comment]
Created PR #241

**Comment by jimmarino** [comment]
Closing as this was merged.
