### ISSUE TITLE
`ClientControlAPI`: Initiate Data Transfer

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#232]
Hello everyone,

this issue is about creating a `ClientControlAPI` extension (if it isn't already created) and adding a new REST Endpoint to initiate a data transfer. This API is just an initial draft of an API, so that a user can try out the EDC. It doesn't has to be perfect.

- (optional) create a new `ClientControlAPI`extension
- (optional) create a simple `ClientController` to the extension
- add a new REST endpoint to the `ClientController` that initiates a data transfer
  - the REST endpoint gets the `Connector URL` (asset provider) and the `Asset Id`
  - the REST endpoint creates a new `TransferProcess` in the `TransferProcessStore`([link](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/src/main/java/org/eclipse/dataspaceconnector/spi/transfer/store/TransferProcessStore.java)) 
  - the REST endpoint should configure the `TransferProcess` so, that it uses IDS multipart messages

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
The `control-api` module was introduced some time ago so I guess it could be closed @DominikPinsel ?
