### ISSUE TITLE
RemoteMessageDispatcher and MessageSender for retrieving IDS descriptions

### ISSUE THREAD

**Issue by denisneuling** [eclipse-dataspaceconnector/DataSpaceConnector#233]
For the purpose of enabling communication of one connector to another using the IDS multipart protocol another [RemoteMessageDispatcher](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/src/main/java/org/eclipse/dataspaceconnector/spi/message/RemoteMessageDispatcher.java) implementation is needed. Furthermore this component needs to be enabled to issue IDS [DescriptionRequestMessage](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#DescriptionRequestMessage)s for retrieving (self)descriptions of

* the [Connector](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Connector)
* the [Catalog](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Catalog)
* an Asset's [Resource](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Resource)s
* an Asset's [Artifact](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Artifact)s
* an Asset's [Representation](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Representation)s

Anologuous to the [ids-api-multipart-endpoint-v1](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/data-protocols/ids/ids-api-multipart-endpoint-v1) another gradle module underneath the [data-protocols/ids ](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/data-protocols/ids) tree must be created. This module then can utilize the [object transformation infrastructure](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/data-protocols/ids/ids-transform-v1) to map between IDS objects and EDC domain objects.

This issue is related but not dependent to #234.

<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by DominikPinsel** [comment]
@ronjaquensel Are you interested in working on that?

**Comment by ronjaquensel** [comment]
Hi @DominikPinsel, sure, I've already started looking at this topic. Will just self-assign the issue.
