### ISSUE TITLE
Extend IDS-EDC Domain Object Transformation infrastructure

### ISSUE THREAD

**Issue by denisneuling** [eclipse-dataspaceconnector/DataSpaceConnector#234]
At the time of writing there is just one way covered for mapping data from the EDC domain model to IDS objects using our  [object transformation infrastructure](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/data-protocols/ids/ids-transform-v1). 

For the purpose of enabling communication of one connector to another using the IDS multipart protocol the [set of transformers](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/data-protocols/ids/ids-transform-v1/src/main/java/org/eclipse/dataspaceconnector/ids/transform) needs to be extended to be capable of vice versa transformation. 

Following transformers are (possibly) needed

* [(IDS) Action](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Action) to [(EDC) Action](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Action.java)
* [(IDS) Artifact](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Artifact) to [(EDC) Asset](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/asset/Asset.java)
* [(IDS) Representation](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Representation) to [(EDC) Asset](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/asset/Asset.java)
* [(IDS) Resource](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Resource) to [(EDC) Asset](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/asset/Asset.java)
* [(IDS) Constraint](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Constraint) to [(EDC) Constraint](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Constraint.java)
* [(IDS) ContractOffer](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#ContractOffer) to [(EDC) ContractOffer](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/ContractOffer.java)
* [(IDS) Duty](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Duty) to [(EDC) Duty](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Duty.java)
* [(IDS) LeftOperand](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#LeftOperand) to [(EDC) Expression](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Duty.java)
* IDS RdfResource to [(EDC) Expression](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Expression.java) - whereas RdfResource to [LiteralExpression](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/LiteralExpression.java) is sufficient for the first version
* [(IDS) BinaryOperator](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#BinaryOperator) to [(EDC) Operator](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Operator.java)
* [(IDS) Permission](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Permission) to [(EDC) Permission](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Permission.java)
* [(IDS) Prohibition](https://international-data-spaces-association.github.io/InformationModel/docs/index.html#Prohibition) to [(EDC) Prohibition](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Prohibition.java)

Since the transformers can be conveniently worked on in a disjointed manner one Pull Request can be filed per transformer.

<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by jimmarino** [comment]
@denisneuling Can we skip the RdfResource one? Does anyone have an idea of what that is?

**Comment by denisneuling** [comment]
@jimmarino Sure, IMO for a first version we can skip this until we know how whether it is really used and how to express this. Will cross it out.

**Comment by DominikPinsel** [comment]
I assume we need the `RdfResource` to create a contract, that limits the usage of the data to a specific purpose. Without `RdfResource` we won't be able to create a `Constraint`.
This would make the following transformer unnecessary, too
- Constraint
- LeftOperand
- BinaryOperator

**Comment by jimmarino** [comment]
> I assume we need the `RdfResource` to create a contract, that limits the usage of the data to a specific purpose. Without `RdfResource` we won't be able to create a `Constraint`. This would make the following transformer unnecessary, too
> 
> * Constraint
> * LeftOperand
> * BinaryOperator

@DominikPinsel I'm not sure I follow. Why can't a transformer just support TypedLiteral with an XML Schema string to set the right operand of a Constraint? 

This is probably another thing IDS needs to fix/specify if they want interoperability.

**Comment by DominikPinsel** [comment]
> @DominikPinsel I'm not sure I follow. Why can't a transformer just support TypedLiteral with an XML Schema string to set the right operand of a Constraint?
> 
> This is probably another thing IDS needs to fix/specify if they want interoperability.

@jimmarino Yea, the problem here is that in IDS the right operand is always an `RdfResource`. It looks like this

```java

/**
 * The class of Constraints that restrict a Rule.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "@type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = ConstraintImpl.class)
})
public interface Constraint extends AbstractConstraint {

    @NotNull
    @JsonProperty("ids:leftOperand")
    LeftOperand getLeftOperand();


    @NotNull
    @JsonProperty("ids:operator")
    BinaryOperator getOperator();

    @JsonProperty("ids:rightOperand")
    RdfResource getRightOperand();

   // more code

}
```

**Comment by denisneuling** [comment]
If we really need it, I think it is sufficient to assume a `RdfResource` is directly representable as a [`LiteralExpression`](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/LiteralExpression.java) for now. All other more complex cases should yield some error messages to the `TransformerContext` and should lead to retruning a nulled [`Expression`](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Expression.java). 

This is a compromise between completely leaving the `RdfResource` out and fully implement it's transformation to `Expression`.
Will add the `RdfResource` back to the list together with some comments.

**Comment by jimmarino** [comment]
> If we really need it, I think it is sufficient to assume a `RdfResource` is directly representable as a [`LiteralExpression`](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/LiteralExpression.java) for now. All other more complex cases should lead to some error messages passed to the `TransformerContext` and should yield a nulled [`Expression`](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/policy/policy-model/src/main/java/org/eclipse/dataspaceconnector/policy/model/Expression.java).
> 
> This is a compromise between completely leaving the `RdfResource` out and fully implement it's transformation to `Expression`. Will add the `RdfResource` back to the list together with some comments.

+1. I think we can check for the subtype TypedLiteral and support that since it is declared as an XML Schema string type, which would be valid to do. Otherwise, an error sounds good.

**Comment by jimmarino** [comment]
@denisneuling also looping in @ronjaquensel and @juliapampus  on this...

When deserializing policy expressions, we need to also account for complex types in the right operands of atomic constraint expressions.

For example:

`"ids:constraint": [{    
	"@type":"ids:Constraint",  
	"ids:leftOperand": { "@id": "idsc:CONNECTOR"},  
	"ids:operator": { "@id": "idsc:IN"},  
	"ids:rightOperand": [{ 
		"@value": "?connector1URI", 
		"@type": "xsd:AnyURI"
	},{ 
		"@value": "?connector2URI", 
		"@type": "xsd:AnyURI"
	}], 
	....... omitted .....
}]`

This comes from: https://github.com/International-Data-Spaces-Association/IDS-G-pre/tree/usage-control-terms/UsageControl/contract

In the above, the right operand contains JSON-LD metadata in a serialized JSON array that defines element types using XML Schema string types. The policy engine supports complex types for operand literals, so that is fine. However, I don't think we need to push the complexity of interpreting JSON-LD metadata onto policy functions that evaluate those literals. Instead, we should define a set of types we want to handle out-of-the-box with IDS (users can always add support for more). For example, we would support deserialization into strings or arrays of strings. That way, type complexity is not pushed down to lower levels of the EDC.

So my initial questions are:

1. How are *policy expressions* (not the entire message) currently deserialized from the multipart messages? Are they strings or complex types? The transformation from initial form to the limited type set can be done in the transformer (and vice versa) 

2. Does IDS now declare that policy expressions be JSON-LD types? Or, is it open?
 
Let's discuss.

**Comment by jimmarino** [comment]
I should have added that the use of JSON-LD partly explains why right operands can be RdfResource. However, JSON-LD extends RDF and the RdfResource InfoModel type looks like it may be incorrectly implemented since property values can only be Strings and JSON-LD allows for native JSON types and tagged strings.

As I mentioned, I think these structures should be unwrapped and the corresponding Java types instantiated by the transformers on ingress; Likewise, on egress, the opposite transformation from Java types to JSON-LD can happen in the transformers.

**Comment by DominikPinsel** [comment]
FYI: I will start working on this issue
