### ISSUE TITLE
Policy negotiation flow

### ISSUE THREAD

**Issue by juliapampus** [eclipse-dataspaceconnector/DataSpaceConnector#239]
As discussed last week, @ronjaquensel and I want to share our thoughts about a possible contract negotiation flow containing states - similar to our current transfer process. 

`.puml` files: [edc-negotiation.zip](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/files/7538410/edc-negotiation.zip)

We tried to keep the number of states as small as possible. States on both sides express the same behaviour and, therefore, trigger the same action.
* `REQUESTED` (prov, cons): A contract request or counter offer has been initiated. The connector sends an appropriate message to the recipient. The state is changed to `REQUEST_ACK` as soon as the request or a response to a request has been received.
* `REQUEST_ACK` (prov, cons): The connector has sent a contract request/offer. The connector (on e.g. consumer side) that initiated the request/offer is waiting for a response. The connector that approved the receipt of a request/offer is switching to the next state.
* `VALIDATING` (prov, cons): Depending on the input (contract request/offer/agreement), the connector validates the contract by comparing it with the contract of the last state. E.g. request - offer, offer - offer, agreement - offer, agreement - request, agreement - agreement. Optionally, the user or another system is being involved in the negotiation process.
* `APPROVED` (prov, cons): As soon, as the contract's content is approved by the connector, a user, or an external system, the connector builds an appropriate contract agreement. This is stored in a dedicated location. As soon as the initial sender of an agreement has not received a matching contract agreement, the stored one is marked as `not confirmed`. Next, a message containing the agreement is sent. The status changes to `PENDING`.
* `DECLINED` (prov, cons): If a contract is malformed or invalid, or a user wants to abort the negotiation process, the state changes to `DECLINED`. Thereupon, a contract rejection is sent (and the process gets removed). If necessary, the rejection is logged on both sides and propagated involved users or systems.
* `PENDING` (prov, cons): This state implies that an agreement has been sent and the connector is waiting for confirmation. This can happen both on provider and consumer side, depending on the one that first agreed.
* `CONFIRMED` (prov, cons): If the validation of an agreement is successful, the state changes to `CONFIRMED`. As a result, the stored agreement is marked as confirmed and persisted permanently. Thus, it can be used for later access and usage control.
* `ENDED` (prov, cons): This is the final state that marks the negotiation process as ended. No further action is required.

![negotiation-states](https://user-images.githubusercontent.com/72392527/141776774-afe8270f-cc5c-4a70-a9dc-12fa00b8ee47.png)

Below, you can see a possible negotiation process that is based on the one that has been created some time ago (see [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/diagrams/negotiation-process.png)). Please note that the validation process within the negotiation phase was shortened for readability purpose. On top of that, not everything may be necessary for the "happy flow".

![contract-negotiation](https://user-images.githubusercontent.com/72392527/141776840-ab1748c9-89ea-4dc9-94d5-e824ea99a107.png)

Since agreements can expire or be revoked, they have different states - as indicated above.
* `INITIATED`: not confirmed by the assignee yet
* `CONFIRMED`: valid contract that can be used for access and usage control
* `EXPIRED`: the end date has been reached, nevertheless the contract can be extended
* `REVOKED`: the contract has been ended by e.g. a user with appropriate rights

![agreement-states](https://user-images.githubusercontent.com/72392527/141776961-65bace5e-52df-46c6-9aa5-b5cc7923a8ba.png)

**Comment by jimmarino** [comment]
Hi @juliapampus @ronjaquensel 

Really thorough! I need to digest this a bit but should there also be an error state from contract negotiation?

**Comment by jimmarino** [comment]
@juliapampus @ronjaquensel 

Although we will not implement this in the first go, have you thought about states for counter-offers? Should those be modelled as specific states? I think there could be two possibilities

1. They are not modelled separate from validating - My initial thought is this would not be good
2. The are are modelled as two distinct states: COUNTER_OFFER_CLIENT, COUNTER_OFFER_PROVIDER to indicate which side is currently generating a counter-offer

Maybe there is another approach?

If there are numerous counter offers we probably need at least two things:

1. An ordered list of the contract versions as counter offers are added to this ContractNegotiationProcess. The head of the list points to the current offer
2. An indication of which side (consumer, provider) generated the contract on each Contract instance (version) in the ordered list.  

Note that it would be possible for a consumer to send to contract counter offers and have those appear in the version list sequentially. That would model the case where the consumer changed its mind or there was an out-of-band discussion and offer update.

**Comment by jimmarino** [comment]
@juliapampus @ronjaquensel

Separate issue, should we also think about the security implications of how comparison is done? For now, the provider always throws away the contract offer sent by the client and generates a new copy? This would avoid an "injection" attack.

**Comment by jimmarino** [comment]
@juliapampus @ronjaquensel

Another comment: if the contract is malformed, I would tend to model that as an error state as opposed to declined. What do you think?

**Comment by jimmarino** [comment]
@juliapampus @ronjaquensel

Can we also start to create a state diagram that maps out all the legal state transitions? For example, is it possible to transition from DECLINED back to VALIDATING? One use case I am thinking about is a negotiation where two parties go back-and-forth for a number of iterations. There may need to be a REJECTED state where either party can end the back-and-forth and permanently.

**Comment by DominikPinsel** [comment]
@jimmarino @juliapampus @ronjaquensel
I'm also not sure whether a state model is the best solution in case. I think for audibility it might be interesting to have all these state changes in the contract. So maybe we should collect these events somewhere in the contract.
The state would would be read from the contract
- if endDate > now -> `expired`
- if revokedEvent -> `revoked`
- if confirmedEvent -> `confirmed`
- else `initiated`

Also in theory, it would be possible to go from `initiated` to `expired` when the other party just doesn't confirm the contract. And I'd assume a contract could be `revoked` and `expired` at the same time. This may be important if we get a use case to do something with all `expired` or `revoked` contracts.

**Comment by jimmarino** [comment]
# Contract Negotiation

This document outlines an implementation for the contract negotiation process based on the specification created by @juliapampus @ronjaquensel.

# Architectural Considerations

The contract negotiation subsystem will be modelled as a state machine, which aligns with the existing design of the transfer process subsystem. This state-machine design is necessary to support the key requirements of asynchronous and reliable operation. 

A contract negotiation is conducted between two `PariticipantAgents`. There will be correlated, persistent state-machines representing a contract negotiation on the client and provider connectors. The `ContractNegotition` will be a serializable (via JSON) representation of the state machine.  


## Asynchronous, Reliable Operation

As outlined by the state charts, a `ContractNegotiation` will transition to various states in the `ParticipantAgent` runtimes in response to messages. Transitions may be prompted by the participant runtime that contains the negotiation, or by a message received from the counter-party.

The `ContractNegotiation` will be managed by a `ContractNegotiationManager`. This service will have subtypes for managing the negotiation state machine on the client and provider. The base `ContractNegotiation Manager` will define operations common to both sides (these operations are a rough sketch and not complete):

```
public interface ContractNegotiationManager {

    /**
     * A counter offer was made by the counter-party represented by the claim token.
     */
    NegotiationResponse counterOfferReceived(ClaimToken token, String negotiationId, ContractOffer offer);

    /**
     * Approves the latest contract offer of a negotiation.
     */
    NegotiationResponse approve(String negotiationId);

    /**
     * A negotiation was approved by the counter-party.
     */
    NegotiationResponse approved(ClaimToken token, String negotiationId);

    /**
     * Declines the negotiation; the counter-party will be notified.
     */
    NegotiationResponse decline(String negotiationId);

    /**
     * A negotiation was declined by the counter-party.
     */
    NegotiationResponse declined(ClaimToken token, String negotiationId);
}
```

The client and provider subtypes will define the following operations respectively (these operations are a rough sketch and not complete):

```
public interface ClientContractNegotiationManager extends ContractNegotiationManager {

    /**
     * Initiates a contract negotiation for the given provider offer. The offer will have be obtained from a previous contract offer request sent to the provider.
     */
    NegotiationResponse initiate(ContractOffer offer);

    /**
     * An offer was received from the provider.
     */
    NegotiationResponse offerReceived(ClaimToken token, String negotiationId, ContractOffer contractOffer);

    /**
     * The negotiation has been confirmed by the provider and the final contract received.
     */
    NegotiationResponse confirmed(ClaimToken token, String negotiationId, Object contract);
}
```

and (these operations are a rough sketch and not complete):

```
public interface ProviderContractNegotiationManager extends ContractNegotiationManager {

    /**
     * A contract negotiation has been initiated by the client represented with the given claims.
     */
    NegotiationResponse initiated(ClaimToken token, String correlationId, ContractOffer offer);

    /**
     * Confirms a contract negotiation after it has been approved by both counter-parties. A final contract will be sent to the client.
     */
    NegotiationResponse confirm(String negotiationId);
    
}
```

All operations will be idempotent and return immediately. However, side effects of those operations will be run on a separate timer thread. For example, a provider may confirm a negotiation. This operation will transactionally update a backing persistent store with the state transition. However, sending a notification and finalized `Contract` to the client will be handled on another thread. Each manager implementation will contain a scheduled thread that periodically ticks over to handle these transitions. 
                                                                                                                                                        
This design is the same as the `TransferProcessManager` and enables reliability, failure recovery, and the ability to support asynchronous workflows such as human approval.

## Auditability

All metadata associated with a negotiation process will be persisted as part of the `ContractNegotiation` POJO. This class will contain a list (ordered) of `ContractOffers` that were made during the negotiation processes. The last `ContractOffer` in the list is the current. When a `ContractNegotiation` is confirmed, a `Contract` will be added that represents the in-force usage contract. Note that only references to `Assets` will be held by `ContractNegotiation`. 

The `ContractNegotiation` type will provide a mechanism for adding auditing in the future. It will also have a GUID that can be used for further correlation.

## Non-Repudiation

Non-repudiation (the ability for each party to prove the contents of a `ContractNegotiation`) will not be implemented in this iteration.
    
# PR Descriptions

@jimmarino will provide the follow PRs.

### Part 1: Introduce types and service interfaces 

This PR will introduce the basic type and service definitions for `ContractNegotiation` and `ContractNegotiationManager`. These will be mostly skeleton implementations and their definitions will likely evolve over time. In addition, `ContractOfferService` will be updated to add a validation and sanitization method for contract offers received from a client
during contract negotiation. This in turn will require and update to `ContractOfferFramework`to return a sanitized `ContractOffer` based on a previous copy. Finally,  a method will be added to `AssetIndex`to return a set of assets for a given collection of `Criteria`. This method is the same as needed for Part 3 of the policy PR.

### Part 2: ContractNegotiationManager implementation

This PR will implement the skeletons introduced in Part 1. Note that the `ContractNegotiationManager` implementations will require additional state definitions. For example, COMPLETING and COMPLETED will be necessary to denote the start and endpoints of a transition.
