### ISSUE TITLE
Rename client to consumer

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#24]
Suggest to replace "client" by "consumer" in the extensions code as this term is used in IDS and Gaia-X documents.
Also feels more natural to have the pair "provider & consumer" instead of "provider & client".

<sub> Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by beardyinc** [comment]
can we close this, as PR #40 was already merged?

**Comment by MoritzKeppler** [comment]
PR merged
