### ISSUE TITLE
Update asset and contract docs

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#245]
[Diagrams ](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/docs/diagrams) and [terminologoy ](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/Terminology.md) need to get aligned with the changes described in #227 
Would be great to have the javadocs in the header of the corresponding classes as source of truth for the definitions. 
Maybe we can just link or autocreate the markdown from javadoc.
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
@MoritzKeppler is this something you can look into for the release? I can help if there are questions.
