### ISSUE TITLE
Update IDS Infomodel dependency

### ISSUE THREAD

**Issue by juliapampus** [eclipse-dataspaceconnector/DataSpaceConnector#247]
The edc currently uses the Infomodel library v4.0.0. The latest release is v4.2.7 (see [here](https://maven.iais.fraunhofer.de/ui/native/eis-ids-public/de/fraunhofer/iais/eis/ids/infomodel/java/)). As this not only coveres some ontology extensions but especially technical/implementation changes and improvements, we should update the dependency. Maybe this will also fix some issues when using builder classes and mapping objects etc.

**Comment by denisneuling** [comment]
Thx @juliapampus for reporting this. Will update the dependency's version and fix incompatibilities with its integration.
