### ISSUE TITLE
Add various secrets to the repo settings

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#25]
In order for the CI build to run through, we need to add the following repository secrets:
- `AZ_STORAGE_KEY`: for tests against Azure Storage accounts
- `AZ_STORAGE_SAS`: for tests against Azure Storage accounts
- `COSMOS_KEY`: for tests against Azure CosmosDB
- `S3_ACCESS_KEY_ID`: for tests involving an S3 Bucket
- `S3_SECRET_ACCESS_KEY`: for tests involving an S3 Bucket
- `RUN_INTEGRATION_TEST`: this is just `true` or `false` to determine, whether to run i-tests or not.

_Note_: only repo owners can add secrets.

**Comment by mspiekermann** [comment]
AZ_STORAGE_KEY: for tests against Azure Storage accounts
AZ_STORAGE_SAS: for tests against Azure Storage accounts
COSMOS_KEY: for tests against Azure CosmosDB
S3_ACCESS_KEY_ID: for tests involving an S3 Bucket
S3_SECRET_ACCESS_KEY: for tests involving an S3 Bucket

are added to the repository
