### ISSUE TITLE
Remove PolicyId from Asset

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#251]
Hello everyone,

the `Asset` currently has a `PolicyId` property. As far as I understand the policies of an `Asset` are described in the corresponding `Contract` or `ContractOffer` class. Therefore I'd remove the `PolicyId` from the `Asset` again.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
Also there is an `Asset` in the `DataRequest`. I assume this was added there to get the corresponding `Policy` from the request, what doesn't work. Maybe this can be removed, too.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
It still has it but it's unused, guess it can be fixed with a simple PR?

**Comment by paullatzelsperger** [comment]
should be simple to remove. would you mind doing it?
