### ISSUE TITLE
rename module policy-model to policy-evaluator

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#253]

**Comment by mohitsaxenaknoldus** [comment]
Can I raise a PR for this?

**Comment by jimmarino** [comment]
Hi @mohitsaxenaknoldus, sorry for the delay, I didn't see your question. Sure. We have a bit of churn right now in the codebase due to Milestone 1 we want to release on Friday. Would you be able to work on this next week once things calm down a bit? We could always do the change this week if you have time, but please message me so that I can take a look and merge it quickly so it does not go stale due to the number of changes we are merging for the release.

**Comment by mohitsaxenaknoldus** [comment]
No problem! Let's do this next week.

**Comment by ndr-brt** [comment]
Talking about this, should the classes/interfaces contained in `policy-model` being moved to `spi`?
I noticed that at the moment, `policy-model` is a dependency of `spi`, but I think `spi` should be at the root of the dependency diagram and not depending by any extensions, neither the core ones.

**Comment by mohitsaxenaknoldus** [comment]
@jimmarino PR: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/450
