### ISSUE TITLE
Eliminate request to external DAPS from within integration test

### ISSUE THREAD

**Issue by denisneuling** [eclipse-dataspaceconnector/DataSpaceConnector#256]
The [DapsIntegrationTest](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/daps/src/test/java/org/eclipse/dataspaceconnector/iam/daps/DapsIntegrationTest.java#L67) issues real requests to the external DAPS instance hosted by Fraunhofer AISEC. 
Although it's working, IMO it's bad practice and also obliges external conditions we cannot influence.

There is a pre-built docker image of the [DAPS omejdn-server](https://github.com/Fraunhofer-AISEC/omejdn-server/pkgs/container/omejdn-server). 
It'd be nice to have some volatile DAPS instance running during integration tests - possibly by using [testcontainers](https://www.testcontainers.org/quickstart/junit_5_quickstart/) from within the integration test itself.

<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by jimmarino** [comment]
Is this something @ndr-brt you could look at?

**Comment by gbrost** [comment]
Cool to see you are on track here. If you need any support by us (AISEC, the DAPS guys), please let us know.
