### ISSUE TITLE
Missing synchronisation in FsVault

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#268]
`deleteSecret` method is missing synchronisation. (How about backing the class with a `ConcurrentHashMap`?)

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/84bb9597b4ed18ad177fe82e475661a53000d762/extensions/filesystem/vault-fs/src/main/java/org/eclipse/dataspaceconnector/security/fs/FsVault.java#L80

**Comment by jimmarino** [comment]
Thanks for reporting the issue! It looks like the method is missing the synchronized keyword, since there is also a file write operation that needs to be taken care of. Are you interested in creating a PR?

**Comment by ndr-brt** [comment]
Could we use a lock instead? Otherwise we should document the cases where `synchronized` would be preferred.

**Comment by jimmarino** [comment]
I think the answer is whatever is easier for the given situation. In this case, we don't need r/w locks (the FS Vault is not intended to be performant or used in production).

**Comment by algattik** [comment]
Why not use the FS Vault in production? Is this documented?

On the Provider side we are using it only for storing temporary SAS tokens received from the Consumer. We don't need the overhead of an Azure Key Vault for this.
