### ISSUE TITLE
Integration tests are not executed after a merge

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#288]
I noticed that integration tests arent't running after a merge, so, currently, they are executed only on pull request push but against the main branch.
Is this the expected behaviour? I would make them running also after a PR merge.

**Comment by paullatzelsperger** [comment]
we might want to run them on every push to `main`, that includes merge commits IMO. @ndr-brt can you look into this?
