### ISSUE TITLE
`ContractValidationService` Add functionality

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#295]
This issue is about adding the following functionality to the `ContractValidationService`:

- The contract validation service should be able to tell when a contract is expired
- The contract validation service should also check whether the corresponding asset is part of the contract
- The contract validation service should return a result object with found errors, so that the caller is able to log them with some context information.

Additionally the `ContractValidationService` checks currently in two places whether a `contract` id is valid. Therefore it would be nice if
- The `contract id` would be a value objects, that cannot be formatted incorrectly. So that we don't need this checks in several places. 

Update:
> The contract validation service should also check whether the corresponding asset is part of the contract

This requirement will become invalid as future `ContractAgreement` will only contain one `Asset` -> Ignore it.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by jimmarino** [comment]
I think only 1 of 1-3 should be done.

The contract validation service should only return a boolean to indicate its status. We don't want to give any reason to the client why the validation failed as that may result in a security leak. Instead, the validator can log more information if required and those logs can be correlated via the contract offer/agreement id by operations.

The contract id must not be a value object. The contract id is explicitly designed to be a string that implements an architected scheme as described by `ContractId`. This is because that scheme is opaque to the client and only understood by the contracting subsystem. No other system or subsystem should have that knowledge.

**Comment by DominikPinsel** [comment]
> The contract id must not be a value object. The contract id is explicitly designed to be a string that implements an architected scheme as described by `ContractId`. This is because that scheme is opaque to the client and only understood by the contracting subsystem. No other system or subsystem should have that knowledge.

I'm sure what par of the system the contracting subsystem should represent. But wouldn't it work like this?

```java
@JsonDeserialize(builder = ContractId.Builder.class)
public final class ContractId {

   private static final String DELIMITER = ":";

    private final String definitionId;
    private final UUID uuid;

    @JsonIgnore
    public String getDefinitionId() {
        return definitionId;
    }

    public String getId() {
        return definitionId + DELIMITER + uuid;
    }

    private ContractId(@NotNull String id) {
        // validate format of the id
    }

    @JsonPOJOBuilder(withPrefix = "")
    public static class Builder {

        private String id;

        @JsonCreator
        public static Builder newInstance() {
            return new Builder();
        }

        private Builder() {
        }

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public ContractId build() {
            return new ContractId(id);
        }
    }
}
```

**Comment by jimmarino** [comment]
Please see my previous comment and the documentation in the code. The id must be an opaque string similar to a URN that only the contract subsystem knows how to dereference.

**Comment by jimmarino** [comment]
Closing as this work has now been completed.
