### ISSUE TITLE
Adding a logger extension

### ISSUE THREAD

**Issue by cpeeyush** [eclipse-dataspaceconnector/DataSpaceConnector#297]
This issue is about adding a logger extension. Current default implementation of Monitor usage a ConsoleMonitor which prints logs on standard output without using a logger.

Using a logger will provide benefits: 

- A logging configuration file can be used to add various log handlers e.g. FileHandler, logging level can be configured e.g. INFO, ERROR, DEBUG etc., also log statements formatting can be specified as well.
-  Needed for Azure Monitor Application Insights javaagent to [auto collect logs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent#auto-collected-logs). Other cloud provider might also have similar advantages when using logs.

_Implementation_
A PR will be created soon with a logger extension implementation. It usages java.util.logging package for logger so will not introduce any additional dependency.

_Know limitation_
A class level logger cannot be created as current Monitor interface methods does not have class as method arguments . So instead a global or extension level can be used.

**Comment by jimmarino** [comment]
This can be handled by creating an extension and configuring it in the runtime. We don't want to dictate a particular logger implementation.

I personally don't find class level logging very informative, but this can also be handled by passing that via a json type or wrapping the Monitor object .
