### ISSUE TITLE
Verify contract offer request flow (message dispatchers and handlers)

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#306]
Depends on PR #285

**Comment by MoritzKeppler** [comment]
@jimmarino can you please adde some more details what needs to be done - just to make sure we are on the same page. Thanks!

**Comment by DominikPinsel** [comment]
I tested the data transfer on the main branch (including requesting the data offers first) and its working fine. Also there is now an update for the simple 5 documentation in PR #321.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by mspiekermann** [comment]
@DominikPinsel can this one be closed, since we merged the PR already?

**Comment by DominikPinsel** [comment]
@mspiekermann Yea. Sorry I forgot about this and will close it myself.
