### ISSUE TITLE
Implement Cosmos ContractNegotiationStore

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#309]

**Comment by bscholtes1A** [comment]
Hi @jimmarino 
what would contain this store? I see no ContractNegotiation object in the code.

Benjamin.

**Comment by juliapampus** [comment]
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/negotiation/ContractNegotiation.java

We will add negotiation logic with #284 @bscholtes1A
