### ISSUE TITLE
README.md is not current

### ISSUE THREAD

**Issue by sn0wcat** [eclipse-dataspaceconnector/DataSpaceConnector#31]
The readme is still talking about microsoft/data-application-gx and not about eclipse-dataspace connector.

**Comment by MoritzKeppler** [comment]
thx, we will provide an updated version soon!

**Comment by MoritzKeppler** [comment]
@beardyinc maybe you can have a look

**Comment by beardyinc** [comment]
> @beardyinc maybe you can have a look
will do.

**Comment by sn0wcat** [comment]
Is the CLA requirement in the README.md just a remnant of the past project? I actually thought that there is agreement within Catena-X network not to go with CLAs?

**Comment by MoritzKeppler** [comment]
We will remove the requirement to sign a Microsoft CLA.
But as it's an Eclipse project you need to sign the Eclipse Contributors Agreement to contribute.

**Comment by MoritzKeppler** [comment]
PR merged
