### ISSUE TITLE
Service for building ContractAgreement

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-dataspaceconnector/DataSpaceConnector#317]
During the contract negotiation, either the provider or the consumer builds a ContractAgreement in order to accept a previously received offer. Currently, the `Provider-` and `ConsumerContractNegotiationManagerImpl` build the ContractAgreement when confirming an offer. This should be extracted to a designated service in the `core/contract` module. An open question is, whether any additional operations (like e.g. validation) should be performed by the service before the agreement is returned.

**Comment by jimmarino** [comment]
Hi @ronjaquensel in our model the provider always creates the ContractAgreement right? Also, the agreement is created from a valid ContractOffer that is always originated from the provider and previously validated. Given that do you think it is necessary to revalidate the ContractAgreement?

**Comment by juliapampus** [comment]
> in our model the provider always creates the ContractAgreement, right?

I would not just agree to that. Currently yes, as the consumer starts the negotiation with a contract offer. It's always some kind of pull principle: the provider creates a contract offer, the consumer can view this and asks for a contract based on it. But maybe we could think of a scenario, where the provider initiates the contract negotiation. Maybe as a technical continuation of other transactions? So the provider actively sends a contract offer. According to previous discussions, the consumer would not create a counter offer but send an agreement. Or would the sequence then needed to be changed, so the provider always creates the agreement? We never talked about possible modifications of this agreement.

> Also, the agreement is created from a valid ContractOffer that is always originated from the provider and previously validated. Given that

I understand this point. Nevertheless, we cannot assume that the participant sending the contract agreement has not changed it. Or that it creates the agreements from the agreed on offer. Only because this is implemented in the EDC, we should never trust other (IDS or non-IDS) connector implementations.

**Comment by jimmarino** [comment]
> > in our model the provider always creates the ContractAgreement, right?
> 
> I would not just agree to that. Currently yes, as the consumer starts the negotiation with a contract offer. It's always some kind of pull principle: the provider creates a contract offer, the consumer can view this and asks for a contract based on it. But maybe we could think of a scenario, where the provider initiates the contract negotiation. Maybe as a technical continuation of other transactions? So the provider actively sends a contract offer. According to previous discussions, the consumer would not create a counter offer but send an agreement. Or would the sequence then needed to be changed, so the provider always creates the agreement? We never talked about possible modifications of this negotiation sequence.
> 

The state machine disallows this. I would say in this situation, the provider and consumer roles would be swapped and the provider then becomes the consumer requesting a contract.

> > Also, the agreement is created from a valid ContractOffer that is always originated from the provider and previously validated. Given that
> 
> I understand this point. Nevertheless, we cannot assume that the participant sending the contract agreement has not changed it. Or that it creates the agreements from the agreed on offer. Only because this is implemented in the EDC, we should never trust other (IDS or non-IDS) connector implementations. Thus, the participant receiving the agreement should always validate the content and be able to reject the agreement if any modifications are detected.

In the state machine, only the provider can create an agreement. In the EDC implementation, the contract offer from the consumer is sanitized into a newly created by the provider and validated. Only a sanitized contract offer can be used to create an agreement.

Does that flow make sense?

**Comment by juliapampus** [comment]
> In the state machine, only the provider can create an agreement. In the EDC implementation, the contract offer from the consumer is sanitized into a newly created by the provider and validated. Only a sanitized contract offer can be used to create an agreement.

What happens if the provider is **not** an EDC? The state machine should allow to communcate with non-EDC connectors, at least over IDS. So we cannot be sure that the provider created an agreement from a sanitized contract offer.

**Comment by jimmarino** [comment]
I don't think it matters if the consumer is an EDC or another implementation. It should always sanitize the contract offer. So, I think the current state machine model we have will handle this case.

Regarding the consumer side, that is a good point, the consumer needs to validate that the `ContractAgreement` it receives matches the last ContractOffer in the `ContractNegotiation`. It should do this by comparing the asset id, the contract start/end times, and the attached Policy are identical. 

Does that make sense?
