### ISSUE TITLE
Add CommandQueue to TransferProcessManager

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#330]
## Problem statement
The `TransferProcessManagerImpl` (TPM) uses several methods to check and advance the state of transfer processes. Those "check-methods" are not transactional, so another process/thread could intercede and perform another modification, which would get overwritten by the TPM, e.g.:
```java
private int checkCompleted(){
  var processesInProgress = transferProcessStore.nextForState(TransferProcessStates.IN_PROGRESS.code(), batchSize);
  for(var process : processesInProgress){
    // modify processes in a loop, advance state, etc
    // Problem when "process" gets modified by another thread before the call to update()!
    transferProcessStore.update(process);
  }
```
The fundamental problem is that the read and write calls (here: `nextForState()` and `update()`) are not performed within the same transaction, which was not a problem until now, since the TPM is single-threaded. However, as soon as a second thread comes into play, e.g. a watchdog, or a cleanup job, we're running into concurrency problems.

## Proposed solution
I propose the implementation of a command queue, which gets drained at specific points in the code. Any modifications to the TP's must be submitted through the command queue.
A command would basically be a `Function<TransferProcessStore, TransferProcess>`, that receives the TPS as parameter, loads the TP and does whatever  modification it needs to do, and returns the TP back out again. 

There is a few important considerations about this:
- The TPM must pass the TPS to the command so that it can load the TP
- The command cannot maintain a reference to the TP, because that might become "stale"
- The command should not persist the TP, rather it should return the TP and let the TPM manage persisting.

All put together this could look something like this:
```java
//TransferProcessManagerImpl.java, line 111
 try {
   drainCommandQueue();
   int provisioning = provisionInitialProcesses();
   drainCommandQueue();
   int sent = sendOrProcessProvisionedRequests();
   drainCommandQueue();
   //...
   if (provisioning + provisioned + sent + finished + deprovisioning + deprovisioned == 0) {
     Thread.sleep(waitStrategy.waitForMillis());
   }
   waitStrategy.success();
  } //catch...
```

### Modifying the `TransferProcessManager`
An additional method will be added to the `TransferProcessManager` allowing the submission of the aforementioned commands.

## Resilience considerations
Persisting commands to guard against connector crashes, especially in clustered environments, is the responsibility of the implementor of the command, e.g. by writing status information to persistent storage etc. or even serializing the entire command. Then, after the connector comes up again, the command would have to be restored using that information and be re-inserted into the queue.

## Other remarks
This pattern should be used for other transaction-style state machines, like the contract negotiation. @juliapampus @ronjaquensel what do you think?

**Comment by ndr-brt** [comment]
I agree on refactoring this class, but I'm not able to see how this approach will resolve the concurrency problem, unless we'll have only one class that could handle updates on the `TPS` (at the moment there are 3), and then a command queue approach will solve the problem (only in a case of a single/non clustered EDC instance).

I would model that similarly to the CQRS way: the `command` will be only a data class containing the informations of the modification to apply on the TP (what and how), then there should be a `command-handler` component for every command that would execute the domain logic (get the TP from TPS, modify and store it). 
That would permit to easily serialize and persist commands to handle e.g. edc reboot or execution on different nodes.

**Comment by DominikPinsel** [comment]
Maybe another approach. I would appreciate it if the state machine would not be known in the SPI. For me that's an implementation detail of the transfer implementation and not some knowledge it should share with other extensions. By eliminating this knowledge, the resolving of the concurrency problem probably becomes a lot easier.

**Comment by paullatzelsperger** [comment]
@ndr-brt It's almost a CQRS, without the query part :)
in clustered environments we don't have a problem, because (at least for cosmos) there is a leasing mechanism using SPROCs.
The problem arises within the same connector, and by only allowing TP modifications through the command queue we can eliminate concurrency. Granted, it does not strictly speaking _allow concurrency_, rather it _removes_ it.

**Comment by ndr-brt** [comment]
I don't know how that leasing mechanism works, but it will handle also situations like:
```
node1: read TP 1
node2: read TP 1
node2: edit TP 1
node2: update TP 1
node1: edit TP 1
node2: update TP 1 <-- this should fail, or the command should be retried
```
?

**Comment by jimmarino** [comment]
> I agree on refactoring this class, but I'm not able to see how this approach will resolve the concurrency problem, unless we'll have only one class that could handle updates on the `TPS` (at the moment there are 3), and then a command queue approach will solve the problem (only in a case of a single/non clustered EDC instance).
> 
> I would model that similarly to the CQRS way: the `command` will be only a data class containing the informations of the modification to apply on the TP (what and how), then there should be a `command-handler` component for every command that would execute the domain logic (get the TP from TPS, modify and store it). That would permit to easily serialize and persist commands to handle e.g. edc reboot or execution on different nodes.

@ndr-brt these are really good observations. Yes, all modifications need to be done via the command queue, so the ProvisionManager will need to be updated use that mechanism.

Separate Commands and Handlers seem a bit complicated for what we need (it is essentially a unit-of-work), but lets see where the discussion leads.

**Comment by jimmarino** [comment]
> I don't know how that leasing mechanism works, but it will handle also situations like:
> 
> ```
> node1: read TP 1
> node2: read TP 1
> node2: edit TP 1
> node2: update TP 1
> node1: edit TP 1
> node2: update TP 1 <-- this should fail, or the command should be retried
> ```
> 
> ?

This is an optimistic concurrency scheme. The EDC currently uses exclusive locks so this won't happen.

**Comment by jimmarino** [comment]
> Maybe another approach. I would appreciate it if the state machine would not be known in the SPI. For me that's an implementation detail of the transfer implementation and not some knowledge it should share with other extensions. By eliminating this knowledge, the resolving of the concurrency problem probably becomes a lot easier.

Please see my response to this same question in #246. The core tenet of the EDC architecture - the thing on which everything else is built - is that the transfer process is an asynchronous state machine. This must therefore be reflected in the SPI. 

The reason we are facing these issues is because writing distributed systems is difficult. Fortunately, we have a central locking mechanism in the form of the TransferProcessStore implementations (e.g. Cosmos), so we don't have to deal with even more complex problems such as a consensus mechanism.   

That said, restricting visibility of the TransferProcessStore to the TPM is probably something we need to do, and can be achieved by loading a "private" extension, which would involve having the TPM module use a service locator to resolve an implementation.

**Comment by marcgs** [comment]
@jimmarino A wish that we would have as EDC users would be to have the possibility of cancelling transfer processes on the consumer side. At the moment we are doing that by using the TransferProcessStore to update the state of processes to ERROR (which caused the concurrency problems that motivated this issue). If the TransferProcessStore is no longer visible we would need another way to do that.

**Comment by jimmarino** [comment]
@marcgs We definitely need to be able to do that. I'm not sure whether we would hide the TPS or split it into different interfaces. In any event, we need a mechanism to safely update a transfer process. I think some form of a command queue that provides the equivalent of a safepoint for updates will fit the bill. The implementation should be as simple as possible, the tricky part will designing it in a safe way. Your feedback has been really helpfully with this so please keep it coming.

**Comment by ndr-brt** [comment]
To split this activity one task could be to avoid calling of `transferProcessStore.update` from components that are not the `TransferProcessManager`. That will help introducing command because all the logic that handles TP state modification will be in a single place. Will open a PR soon.

**Comment by ndr-brt** [comment]
I have a question, looking at the current main branch, seems like the "deprovision" phase is not automatically started after transfer completion but it's triggered calling the `deprovision` method.
Is this right or that should be automatic?

**Comment by ndr-brt** [comment]
@paullatzelsperger can be closed now?

**Comment by paullatzelsperger** [comment]
Closed it
