### ISSUE TITLE
Some source files say Copyright Microsoft

### ISSUE THREAD

**Issue by HamletDRC** [eclipse-dataspaceconnector/DataSpaceConnector#343]
Some source files say copyright Microsoft: 

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/build.gradle.kts

But the LICENSE file is Apache. Does Microsoft really have copyright ownership of the specified files? If not, we should really remove the copyright claim. Thanks,

**Comment by mspiekermann** [comment]
This is the guideline for the Apache Software Foundation (ASF). We are using the Apache 2.0 license, but are not part of the foundation. Our project belongs to the Eclipse Foundation, and we ofc stick to their guideline (see above link).
This is totally fine and is also described in the link you provided **"It does not apply to developers outside the ASF who are applying the Apache License to their work"**
