### ISSUE TITLE
Hint that config is not loadable via IntelliJ's terminal in sample 03

### ISSUE THREAD

**Issue by SebastianOpriel** [eclipse-dataspaceconnector/DataSpaceConnector#345]
Whysoever the command of the readme does not work in my IntelliJ's terminal, see: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/90902a94a6a3c0c48623cf2a7dd43f90970e103f/samples/03-configuration/README.md?plain=1#L58

```
PS C:\projects\EclipseDataSpaceConnector> java -Dedc.fs.config="/etc/eclipse/dataspaceconnector/config.properties" -jar samples/03-configuration/build/libs/filsystem-config-connector.jar
Error: Could not find or load main class .fs.config=.etc.eclipse.dataspaceconnector.config.properties
Caused by: java.lang.ClassNotFoundException: /fs/config=/etc/eclipse/dataspaceconnector/config/properties
```

But executing it via CMD works:
```
C:\projects\EclipseDataSpaceConnector> java -Dedc.fs.config="/etc/eclipse/dataspaceconnector/config.properties" -jar samples/03-configuration/build/libs/filsystem-config-connector.jar
INFO 2021-12-02T21:06:11.1797218 Initialized FS Configuration extension
INFO 2021-12-02T21:06:11.8958256 Secrets vault not configured. Defaulting to null vault.
```

OS: Win 10
Java: openjdk 11

**Comment by jimmarino** [comment]
I cut-and-pasted the command and it worked fine for me. It appears there may be something wrong with your classpath. However, I'm not on Windows and generally use Zsh so it may be related to the former.

**Comment by SebastianOpriel** [comment]
I was afraid of that :-) Then let's close the ticket. Thanks for checking Jim!
