### ISSUE TITLE
Listener for contract negotiation

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-dataspaceconnector/DataSpaceConnector#352]
Like the TransferProcessManagerImpl, the Provider- and ConsumerContractNegotiationManagerImpl should be observable and provide the possibility to notify listeners about state changes of ContractNegotiation instances. Therefore, a ContractNegotiationListener interface should be added to the spi module. The ContractNegotiationManagerImpls should extend Observable and notify all listeners when a state is changed.

Then, the ContractNegotiationIntegrationTest can be refactored to use listeners instead of the currently used SignalingInMemoryContractNegotiationStore.

**Comment by ndr-brt** [comment]
I have another question on this topic: why `TransferProcessObservable` is an abstract class and not simply an interface? Since it does not define any abstract logic

**Comment by ronjaquensel** [comment]
I assume it's because it extends the Observable abstract class, which contains the logic for registering and unregistering listeners.

**Comment by ndr-brt** [comment]
whoa, how I could miss that detail? sorry
