### ISSUE TITLE
Support for correlating trace headers between incoming and outgoing requests

### ISSUE THREAD

**Issue by Izzzu** [eclipse-dataspaceconnector/DataSpaceConnector#355]
To monitor the E2E transaction flow in our scenario we’d like to build the distributed traces across Client, Consumer, Provider and API backend.

Currently the EDC framework doesn’t support forwarding the [_traceparent_ header](https://www.w3.org/TR/trace-context/#traceparent-header):

- between http request incoming to Consumer API endpoint and the IDS message sent to the provider.
- between http request sent to the provider from the consumer and the final data transfer operation or backend API request.

Examples of an expected behavior:

- When I send a http request to consumer API with _traceparent_ http header I expect the outgoing request to the provider to also contain _traceparent_ header with the same _trace id_ attribute.
- If the http request sent from the consumer to the provider contains _traceparent_ http header I expect the final data transfer request to also contain _traceparent_ header with the same _trace id_ attribute.

**Comment by jimmarino** [comment]
Hi @Izzzu this is interesting. I have a few questions:

1. The consumer and provider are typically controlled by different organizations. Does it make sense to propagate tracing information across that type of boundary (this is separate from client-to-consumer or provider-to-backend)? Could this boundary be handled by the correlation id? For example, IDS (I believe) has a concept of correlation built-in.

2. How would async requests be handled? There are two subcases here. 

a. First, a data request is sent from the client to the consumer. The request to the producer will be done asynchronously at some later point (e.g. after provisioning has happened). How would traceparent work in that case?

b. A second subcase is from the consumer to the provider and back.  A request will receive a sync ack (over HTTP) but the actual "response" data may be sent at a later time. Would those data responses have to propagate the data? The response data may also be sent by completely different infrastructure. 

3. How would non-HTTP protocols be handled? Are there bindings for other protocols?

Thanks!

**Comment by Izzzu** [comment]
Hi Jim!
Thanks for your questions. 

> 1. The consumer and provider are typically controlled by different organizations. Does it make sense to propagate tracing information across that type of boundary (this is separate from client-to-consumer or provider-to-backend)? Could this boundary be handled by the correlation id? For example, IDS (I believe) has a concept of correlation built-in.

Yes, it can be also very useful to propagate the tracing information across organisations, even if they are using different vendors. This will also help overall a request debugging. If one organisation wants to report an issue to other organisation they can report it with a tracing context information and by using this information other organisation may debug it further to exactly pin point a specific request/trace. 
 
Some information can be found here:

https://opentelemetry.lightstep.com/core-concepts/context-propagation/ 
https://www.w3.org/TR/trace-context-1/ 
https://www.w3.org/TR/trace-context/#problem-statement 
 
> 2. How would async requests be handled? There are two subcases here.
> 
> a. First, a data request is sent from the client to the consumer. The request to the producer will be done asynchronously at some later point (e.g. after provisioning has happened). How would traceparent work in that case?

When the consumer sends the request to the provider it should forward the trace information from the incoming request from the client, so that the provider can use this trace information as a parent to build the correlation chain.  
 
Each activity should contain a parent information about the event that triggered current activity, no matter if the trigger is asynchronous or synchronous. If the operation is asynchronous then perhaps the trace information can be saved from parent thread and forwarded at some later point when the request to the provider is triggered. 
 
This information may be also useful: 
https://opentelemetry.io/docs/reference/specification/trace/api/#spankind 
Open telemetry API uses a concept of Spans. There are different kind of spans.  e.g. PRODUCER can be a span that describes an initiation of an async request. 
 
Here also described an example how it’s solved in case of Azure Functions: 
https://medium.com/swlh/correlated-logs-deep-dive-for-eventhub-triggered-azure-function-in-app-insights-ac69c7c70285 
It contains some details that may be not relevant but the whole concept seems to be similar. 
The ids that are then captured by Azure Insights in this example are created based on WC3 trace context. 

> b. A second subcase is from the consumer to the provider and back. A request will receive a sync ack (over HTTP) but the actual "response" data may be sent at a later time. Would those data responses have to propagate the data? The response data may also be sent by completely different infrastructure.

What do you mean by sending the response data by a provider? Are you referring to the “push” mechanism that can be used between consumer and provider? 

> 3. How would non-HTTP protocols be handled? Are there bindings for other protocols?

According to this doc trace context is also relevant for non-HTTP communication protocols. 
https://www.w3.org/TR/trace-context/#other-communication-protocols 

Do you have any specific non-HTTP protocols in mind that should be supported within EDC?  

Let us know if you have any more questions.  Thank you!
