### ISSUE TITLE
Samples: improve the implementation of the `DataFlowControllers`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#364]
Currently there is only two `DataReader` and `DataWriter` implementations: one of each for S3 and Azure BlobStore. This should be expanded additional readers and writers can be supplied easily, e.g. through a registry.

The emerging `DataFlowController` could then even be adopted into the EDC "core" codebase (as opposed to it being a sample).

Linked to #246 

will be done together with @bscholtes1A

**Comment by jimmarino** [comment]
Instead of putting it into "core" the extension could offer its own SPI

**Comment by paullatzelsperger** [comment]
> Instead of putting it into "core" the extension could offer its own SPI

I may have misspoken, I didn't mean the `core` module, I meant it could become part of the "main" EDC codebase. That may entail also adding code to `spi`, e.g. the `DataReader` and the `DataWriter`. I envision the `BlobToS3DataFlowController` becoming an `InlineDataFlowController`, that is agnostic of where data comes from and where it goes to. Its sole job is to shovel bits from A to B. 

This is in contrast to an "out-of-band"-DataFlowController, which would hand-off the transfer to an external system.

**Comment by ndr-brt** [comment]
I think this is completed, right @paullatzelsperger @bscholtes1A ?

**Comment by paullatzelsperger** [comment]
yes, @bscholtes1A solved this in the `InlineDataFlowController`
