### ISSUE TITLE
Wasteful to run integration tests on PRs from forks

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#376]
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/2e4b1223dd958efa8793ec5deefe39f83ee741c9/.github/workflows/integrationtests.yaml#L6

It seems wasteful to run (cloud based) integration tests on PRs from forks: with `pull_request_target` the target will be the main repo and not the PR code, therefore these runs are wasted. They may also give a false sense of safety to reviewers that the PR code actually went through integration tests.

`pull_request_target` is for workflows that act on PRs themselves, e.g. to automatically add comments.

**Comment by ndr-brt** [comment]
I agree, but now we are working on make integration tests working with self contained systems (#360), so then we could make them run at every commit also on the PRs

**Comment by paullatzelsperger** [comment]
In the (distant) future we'd like to have some sort of End-to-End test environment, possibly even several of them, where we could deploy any amount of connectors, storage systems, ...

This would also give us the possibility to run stress tests and advanced scenarios like simulate network outages, latencies, failing K8S pods, etc.

**Comment by paullatzelsperger** [comment]
unfortunately, the CosmosDB Emulator is ... (how do I put this politely) ... a bit clunky to use, see my comment in issue #360, so I'm afraid we are stuck with a test instance in Azure for the time being. 
Feel free to weigh in or contribute though :)
