### ISSUE TITLE
Use-Case Experience: Support of ECDSA private keys

### ISSUE THREAD

**Issue by tmberthold** [eclipse-dataspaceconnector/DataSpaceConnector#382]
We just had a requirement in the IDSA Dataspace Connector and Messaging-Services to also support ECDSA (ES256) private keys as well as RSA (RS256). Might be worth considering adding support for ECDSA (ES256) private keys in the future as well.

Currently, only RSA private keys are supported in the E-DSC:

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/cff70576e768cac95ab625504c121e296fa7159c/extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java#L105

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/cff70576e768cac95ab625504c121e296fa7159c/extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/impl/Oauth2ServiceImpl.java#L192

**Comment by mspiekermann** [comment]
@tmberthold sounds good to me and the linked comment also shows the intention for adding support of further key types. Would you like to provide a PR with a proposal?

**Comment by tmberthold** [comment]
I put it on my list for next week. If someone else has done it by then, that's of course ok too.

**Comment by jimmarino** [comment]
Hi @tmberthold that would be a great addition. Feel free to sync with @bscholtes1A and @paullatzelsperger who have been working in this area.
