### ISSUE TITLE
oauth2-core extension Readme 

### ISSUE THREAD

**Issue by tmberthold** [eclipse-dataspaceconnector/DataSpaceConnector#383]
1. Small hint on a typo in the readme of the oauth2-core extension: The first green dot in the picture below should be `edc.oauth.provider.jwks.url` and not `edc.oauth.provider.jwks.refresh` (probably copy paste mistake).
2. Description for `edc.oauth.client.id` could be missing, at least the EdcSetting is used in the `Oauth2Extension`

![image](https://user-images.githubusercontent.com/75306992/145225091-094fcd7d-8646-493b-aa4a-540cdb41cb01.png)

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/83711690eafd2c4875bdb87110766a5c861a24f8/extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/Oauth2Extension.java#L70

Readme:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/extensions/iam/oauth2/oauth2-core

**Comment by ndr-brt** [comment]
Good catch, could you provide a PR for this?

**Comment by tmberthold** [comment]
I put it on my list for next week. If someone else has done it by then, that's of course ok too.

**Comment by tmberthold** [comment]
fixed with https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/d71097bc097eb9285501a42e87b35ddd43a1ec41
