### ISSUE TITLE
Cleanup IDS SPI packaging and documentation

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#385]
There are a number of chores here. We need to come up with a proposal for structuring this module. Some suggested changes:

1. Move IdsId, IdsIdParser, and IdsType to a subpackage under the types package
2. Cleanup the types package
2.a Put Connector and SecurityProfile in a subpackages
2.b Rename the "container" package where OfferedAsset is as this class deals with contracts. 
3. Document what ArtifactRequestMessagePayload is. spec/extension does not seem to be the correct place for this. Is this a message class or a type? If so it should go under one of those packages and have its purpose documented.
4. The "service" package seems to be a grab-bag of different services. These should be moved out to packages that describe their function.

**Comment by juliapampus** [comment]
Is this something that should be moved to M3, or should it stay in Scoping, or be removed from any milestone? @jimmarino
