### ISSUE TITLE
Possibility of cancelling TransferProcesses

### ISSUE THREAD

**Issue by marcgs** [eclipse-dataspaceconnector/DataSpaceConnector#386]
The EDC API should provide a mechanism to cancel running TransferProcesses in a clean way. To achieve this we are currently using the `TransferProcessStore.update` method to update the process state to ERROR. A problem with that, is that `TransferProcessListeners` are not called back, as with any other state change triggered within the `TransferProcessManager`. Additionally having process updates from different threads lead to race conditions.

This has already been provided as feedback for the planned TransferProcessManager redesign #330, but we would appreciate having a temporary solution ASAP. Our suggestion would be to add a `void cancelTransferProcess(String processId)` method to the TransferProcessManager interface which takes care of calling the listeners after moving the state to ERROR (see https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/pull/7 for a solution we are working on as a possible contribution)

**Comment by jimmarino** [comment]
Hi @marcgs if a basic implementation of #330 could be done in the next two weeks, would that be acceptable? I'm hesitant to put a temporary approach in that will be removed shortly.

**Comment by marcgs** [comment]
Hi @jimmarino, but wouldn't the implementation #330 require such a `cancelTransferProcess` method in the `TransferProcessManager` interface anyways? As I understand the command queue will be managed internally by the `TransferProcessManager`, so there has to be a way to add a `CancelProcess` command through its interface, correct?

**Comment by jimmarino** [comment]
> Hi @jimmarino, but wouldn't the implementation #330 require such a `cancelTransferProcess` method in the `TransferProcessManager` interface anyways? As I understand the command queue will be managed internally by the `TransferProcessManager`, so there has to be a way to add a `CancelProcess` command through its interface, correct?
> 
> 
> 
> But to answer your question, yes we can wait 2 weeks, that is not an issue.
It may be a Command implementation and not require a separate method. I just want to make sure we address this holistically when we tackle the issues
