### ISSUE TITLE
Release the first non-SNAPSHOT version

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#391]
Could be a good idea to release the 0.0.1 version, because, from an external perspective, using a SNAPSHOT version is too prone to unexpected changes from night to day.
The release would also marked as unstable, as we already stated, every release will be unstable until 1.0.0

**Comment by paullatzelsperger** [comment]
The question will be, _when_ to release version 0.0.1. I think at least the following features should be included:
- contract negotiation 
- data transfer via IDS multipart
- whatever the result of the refactoring week is

**Comment by ndr-brt** [comment]
I think we can identify a set of issues that needs to be implemented for the release, and in parallel define the release process (someone mentioned gitflow but I think there could be also alternatives to be discussed), changelog handling and so on...

**Comment by ndr-brt** [comment]
I propose to publish a 0.0.1 release since we'll have working samples for the EDC conference of monday. 
so there we could give to the developers a version where there's something that works. 
Even a simple tag could be enough, but I would go with the artifacts release.

**Comment by ndr-brt** [comment]
Closed as done: https://search.maven.org/search?q=g:org.eclipse.dataspaceconnector
