### ISSUE TITLE
Migrate and remove ids-api-transfer

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#403]
From https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/367

> Second, migrate use of ids-api-transfer
> 
> Samples
> EDC Showcase
> Catena-X PRS service and playground

**Comment by ndr-brt** [comment]
It was done in #493 right?

**Comment by paullatzelsperger** [comment]
yes
