### ISSUE TITLE
Release artifacts on Maven Central

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#404]
Since github packages require authentication for retrieve the artifacts, would be nice to publish them on maven central.

**Comment by mohitsaxenaknoldus** [comment]
Can I work on this?

**Comment by ndr-brt** [comment]
@mohitsaxenaknoldus I think so, but I don't know if there's something we need from eclipse (keys/permissions?). Maybe @alexandrudanciu or @mspiekermann can help on thin?

**Comment by MoritzKeppler** [comment]
would also great if we do run the publish actions on forks

**Comment by paullatzelsperger** [comment]
> would also great if we do run the publish actions on forks

Do you mean to publish SNAPSHOTs to Maven Central from forks or to publish into the forks' Github Packages Repo?

**Comment by MoritzKeppler** [comment]
publishing to maven central, e.g.

**Comment by paullatzelsperger** [comment]
> publishing to maven central, e.g. https://github.com/paullatzelsperger/DataSpaceConnector/runs/4716009254

Mh, you bring up a worrying point - i don't think forks should publish anywhere, other than maybe private repos. 

Publishing to EDC Packages and Maven Central should only be done from EDC upstream upon pushes to `main`, otherwise we'd potentially publish code with unreviewed code or unfinished features and we'd also have to distribute credentials to all forks...

**Comment by ndr-brt** [comment]
I agree that only main branch should publish on maven central.

What is needed to be done for this task?

**Comment by paullatzelsperger** [comment]
I assume some sort of account is required with MavenCentral, which should probably be created by @mspiekermann. Then, the credentials to it need to be stored as repo secret, and ultimately we'll need a Github workflow or job to publish them, triggered by PR merges and pushes to `main`.

Also, we could publish release artifacts when tags are created on main, the tag name could serve as the version number, e.g. `0.0.1`.

**Comment by mspiekermann** [comment]
We need a Jenkins instance for Eclipse Foundation projects to publish artifacts at Maven Central. I already started the process to set this up and will provide an update as it is available.

**Comment by domreuter** [comment]
+1 Any news about this topic?

Why going the complicated way using yet another tool if it can be solved via CI/CD with github-actions?

Keeping all the stuff in one place is important as well, so github should be first class citizen here!

**Comment by ndr-brt** [comment]
Close as done: https://search.maven.org/search?q=g:org.eclipse.dataspaceconnector
