### ISSUE TITLE
(Samples) Inconsistency in return type

### ISSUE THREAD

**Issue by tmberthold** [eclipse-dataspaceconnector/DataSpaceConnector#405]
The `HealthApiController` is specified to produce JSON.

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/152d47854f67731cff554831f5df8a0a3726307f/samples/02-health-endpoint/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthApiController.java#L12

But produces simple plain text.

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/152d47854f67731cff554831f5df8a0a3726307f/samples/02-health-endpoint/src/main/java/org/eclipse/dataspaceconnector/extensions/health/HealthApiController.java#L26

---

**Problem:**
Depending on the software used, the following error message may be caused by this:
![image](https://user-images.githubusercontent.com/75306992/145798585-e56198f3-4b92-4a3a-bf19-6603c08708d0.png)

---

**Possible solutions:**
**1.** Change the _produces_ to `@Produces({MediaType.TEXT_PLAIN})`
**2.** Return JSON, e.g. change the return to `return "{\"response\":\"I'm alive!\"}";`

**Comment by paullatzelsperger** [comment]
Hey, thanks for noticing. Could you submit a PR to fix this? Either solution is fine.

**Comment by tmberthold** [comment]
Will do, made a note on my list.

**Comment by ndr-brt** [comment]
I think this problem exists also in the samples 3/4/5

**Comment by tmberthold** [comment]
Fixed with https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/commit/d83c90fc646968dc7396a58cd1ce4bc2f0cea5ad
