### ISSUE TITLE
Handling Exceptions in DataflowController

### ISSUE THREAD

**Issue by marcgs** [eclipse-dataspaceconnector/DataSpaceConnector#418]
When a TransferProcess is in PROVISIONED state, the provider connector initiates the transfer by calling `org.eclipse.dataspaceconnector.spi.transfer.flow.DataflowController#initiateFlow`. The javadoc on this interface specifies the contract "Implementations should not throw exceptions" and instead return an appropriate `DataFlowInitiateResponse`.

However if an exception is accidentally thrown during this operation, the TransferProcess remains stuck in the PROVISIONED state forever. The message "Error caught in transfer process manager" is logged repeatedly on each iteration.

* Uncaught Exceptions in DataflowController should be automatically mapped to a `DataFlowInitiateResponse` with `ResponseStatus#FATAL_ERROR` by the EDC framework to prevent this situation.

**Comment by jimmarino** [comment]
The TPM should also catch these exceptions so the event-loop is not aborted.

**Comment by marcgs** [comment]
@jimmarino I think this is already the case, see [TransferProcessManagerImpl](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java#L136). This is exactly the point where the error message is logged.
