### ISSUE TITLE
Observability - Essential - Missing logging

### ISSUE THREAD

**Issue by Izzzu** [eclipse-dataspaceconnector/DataSpaceConnector#420]
Logging is missing in following places:

- If the Provider URL is unreachable
    - Possible solution: add log messages in DataRequestMessageSender/QueryMessageSender classes
- When the requested artifact is not found in the asset index
    - Possible solution: add log message in ArtifactRequestController class
    
Suggestion to consider:
- implementing toString methods for descriptive logging and assertion failures

**Comment by arckumari** [comment]
Closing this issue since the classes mentioned in the story have been deleted after refactoring.
