### ISSUE TITLE
High Availability - Critical - Provider High Availability

### ISSUE THREAD

**Issue by marcgs** [eclipse-dataspaceconnector/DataSpaceConnector#423]
If a provider connector fails after receiving a request, a transfer process needs to be picked up by another provider connector instance. This is specially important when deploying to Kubernetes, since pods can be restarted at any time (e.g. VM autoscale).

A `TransferProcessStore` backed by an external storage is required to achieve this. In addition a transfer process leasing mechanism to orchestrate the assignment of transfer processes to provider connector instances needs to be in place as well. 

A CosmosDB-based solution is [partially implemented](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/azure/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStore.java) in EDC. This solution requires two stored procedures which available in test resources but not packaged for runtime ([#1](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/azure/transfer-process-store-cosmos/src/test/resources/lease.js), [#2](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/azure/transfer-process-store-cosmos/src/test/resources/nextForState.js)). Finally this implementation is missing lease expiration logic to allow a leased transfer process to be taken by another provider connector instance after a timeout.

Suggested fixes and improvements:
* Provide working implementation of the Cosmos stored procedures in a source folder together with terraform files for deployment.
* Implement lease expiration logic to allow a second provider connector instance to take over a transfer process on failure of a first provider connector instance.
* Provide a working sample for this solution.

**Comment by paullatzelsperger** [comment]
the lease expiration has been [implemented](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/azure/contract-negotiation-store-cosmos/src/test/resources/nextForState.js), it just has not been ported to the TPS yet.

**Comment by jimmarino** [comment]
@marcgs this would be a great hardening task
