### ISSUE TITLE
Architecture - Useful - Resource lifecycle management

### ISSUE THREAD

**Issue by cpeeyush** [eclipse-dataspaceconnector/DataSpaceConnector#425]
The EDC framework provides managed creation of storage resources, but not for their destruction. More comprehensive management of cloud resources (e.g. blob policies, permissions, expiration, container destruction) would be useful.

**Comment by jimmarino** [comment]
@paullatzelsperger this can be a use case for the command queue, correct?

**Comment by paullatzelsperger** [comment]
Yup, think so. Provided there is an ingress path for such a "decommission" signal

**Comment by jimmarino** [comment]
Closing as this will be addressed with the command queue
