### ISSUE TITLE
SDK usage - Useful - Use immutable types

### ISSUE THREAD

**Issue by Izzzu** [eclipse-dataspaceconnector/DataSpaceConnector#427]
Some classes don't provide the immutability. Using [immutable object types](http://www.javapractices.com/topic/TopicAction.do?Id=29) would bring the advantages:
- Immutable objects are thread-safe and require no synchronisation.
- The code is easier to read and reason about.
- The internal state of the application stays consistent.
- References to immutable objects can be cached.
- The failure atomicity is provided for free.
- Can help design the code for memory saving optimisation (reusing the same objects as they are not going to change).

**Comment by paullatzelsperger** [comment]
could you provide an overview of what classes you mean in particular?

**Comment by Izzzu** [comment]
It's about all objects which state can be modified after the creation.
Some examples could be: DataAddress, DataRequest, ResourceManifest, TransferProcess, ProvisionedResourceSet from the spi module.
There are also some classes in identity-did-spi e.g. DidDocument, DidDocumentMetadata, DidResolveResponse.

This point is to consider if it would make sense to minimise the object mutability when possible.

**Comment by ndr-brt** [comment]
I agree on making our value objects immutable, I just want to point that `TransferProcess` is not a value object, it's an entity, with an identifier and a "story", so it needs to be mutable (at least from a classic DDD perspective).

**Comment by jimmarino** [comment]
Is there an actionable set of work here? If so, can we create individual issues for those items? Otherwise, I think everyone agrees that we should use immutable objects where it makes sense, but not to the point where it is impractical or introduces unnecessary complexity.
