### ISSUE TITLE
Architecture - Important - Single JVM and Classloader limitations

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#429]
The requirement to build our extension business code to run in the same JVM and class loader as the EDC code prevents our choice of programming language and runtime. It causes a form of "JAR Hell". The Jetty web server introduces many dependencies such as Logging, Validation. These introduce lock-in, besides, some of these are alpha versions.

We were not able to reuse our preexisting Spring Boot code as it introduced version conflicts with Jetty and Bean Validation. Even our DTO classes, annotated with Bean Validation annotations, were incompatible, and we had to rewrite [DTO classes with Jakarta annotations](https://github.com/catenax/tractusx/blob/main/coreservices/partsrelationshipservice/connector/prs-connector-models/src/main/java/net/catenax/prs/connector/requests/PartsTreeByObjectIdRequest.java). Similar concerns apply to Jackson configuration for JSON serialisation.

The aim of providing a non-intrusive very generic framework seems difficult to achieve, given the framework is effectively very much an application server. and provides advanced services such as a web server.

After we have rewritten our business code to conform to the libraries introduced by EDC, it is unclear how this code will be compatible with future EDC versions and their inevitable library upgrades.

A more flexible and robust approach could be to design EDC as a sidecar. The connector could be an application that communicates with an arbitrary application, e.g. via HTTP. That could be deployed in multi-container pods, or a in more complex topology e.g. to scale out the different layers independently.

For application without such requirements, the current structure could still be allowed, developers can leverage the built-in web server.

**Comment by jimmarino** [comment]
There is nothing to preclude running the EDC as a sidecar. That deployment scenario has already been factored into the EDC design.

Also, the Jetty server extension can simply be replaced with an alternative by changing the extension.
