### ISSUE TITLE
Architecture - Important - Scale-out deployments

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#430]
We architected our business application with EDC as follows:
- A client application issues an HTTP request to the Consumer connector. A Service distributes these in round-robin to a pod deployment. 
- Our customer extension code interacts with the EDC SDK to send an HTTP request to the Provider connector. A Service distributes these in round-robin to a pod deployment. 
- The Consumer connector that "owns" the transfer polls the output storage container for provider result data. When that is available, our extension code (transfer process listener) performs business logic on the output data.

This had the following drawbacks:
- The necessary scale must be deployed in advance in both Consumer and Provider layers.
- The compute requirements may be different on the "inbound" and "return" (listener) path of the Consumer-side processing.
- Round-robin assignments may be suboptimal in terms of load distribution.
- The Provider connector must be deployed on the edge, but also have access to internal business systems to retrieve data, leading to increased attack surface.
- At-least once guarantees are not provided on the listener (#434)

Cloud-native patterns such as [queue-based load leveling](https://docs.microsoft.com/azure/architecture/patterns/queue-based-load-leveling) can help with these, and also with high availability and resiliency.

**Comment by jimmarino** [comment]
@algattik thanks for this. Can we move this to a discussion (and close the issue) until we have concrete issues that can be addressed with PRs?
