### ISSUE TITLE
SDK usage - Important - Extension point for Jetty configuration

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#431]
We wanted to introduce custom exception mappers in our JAX-RS controller. Other foreseeable use cases include middleware for authentication, payload management etc.

We would need an extension point in EDC to provide custom configurations for the Jetty web server. In embedded mode, it appears Jetty does not scan the classpath for `@Provider` annotations.

**Comment by jimmarino** [comment]
@Provider instances are already supported and can be registered with WebService, .cf HttpApiKeyAuthContainerRequestFilter for an example.
