### ISSUE TITLE
DevOps - Useful - provide Helm charts

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#432]
Providing sample charts would accelerate implementation and favour use of best practices.

**Comment by ndr-brt** [comment]
In Catena-x we have a specific repository to do that: https://github.com/catenax-ng/product-edc
Probably they won't fit better here as every EDC deployments depends from the extensions needed.

@algattik if you agree I would close this

**Comment by algattik** [comment]
Closing as implemented in #701
