### ISSUE TITLE
DevOps - Useful - Service credential managed identity

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#433]
EDC requires a principal with an X.509 certificate. That is cumbersome to deploy with IaC and manage. **Managed Identity** and **Service principal passwords** are useful alternatives in cloud environments.

**Comment by paullatzelsperger** [comment]
The SP is primarily used for the `AzureVault`, which also supports Client-Secret-based auth, even though it is currently not used. 
To my knowledge, Terraform supports creating certificates, so it shouldn't be a problem.

We don't support ManagedIdentities at this point though, that's certainly something that can be added.

**Comment by paullatzelsperger** [comment]
There is a PR (#442) from @bscholtes1A that takes care of the client secret secret part.

**Comment by algattik** [comment]
Thank you @bscholtes1A :) Updated title to reflect that only managed identity would be to-do
