### ISSUE TITLE
Naming - DID - Rename Distributed Identity to Decentralized Identifier

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#435]
Rename the package `extensions/iam/distributed-identity/..` to `extensions/iam/decentralized-identifier/..`

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by bcronin90** [comment]
According to @jimmarino the name "Decentralized Identity" is preferred. Reopening to change it.
