### ISSUE TITLE
can not clone project, file name too long - please; some people use windows

### ISSUE THREAD

**Issue by a-trzewik** [eclipse-dataspaceconnector/DataSpaceConnector#440]
unable to clone the repository please remote the test file

$ git clone https://github.com/eclipse-dataspaceconnector/DataSpaceConnector.git
Cloning into 'DataSpaceConnector'...
remote: Enumerating objects: 35169, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 35169 (delta 0), reused 0 (delta 0), pack-reused 35167
Receiving objects: 100% (35169/35169), 8.29 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (10706/10706), done.
error: unable to create file extensions/iam/daps/src/test/resources/keys/OEI6REU6RUU6NEM6N0M6MkQ6N0I6OTM6NTE6MkY6RkQ6QTA6RDM6NTM6NEM6NTg6Q0E6OUQ6NzA6QzI6a2V5aWQ6Q0I6OEM6Qzc6QjY6ODU6Nzk6QTg6MjM6QTY6Q0I6MTU6QUI6MTc6NTA6MkY6RTY6NjU6NDM6NUQ6RTg=.cert: Filename too long

**Comment by ndr-brt** [comment]
Do you know what's the limit for the file name on windows?
If I'm not wrong the filename is used by the omejdn to identify the name of the client, but we can find an alternative anyway

**Comment by jimmarino** [comment]
@ndr-brt has this been resolved?

**Comment by ndr-brt** [comment]
In my opinion, yes. We could wait for a feedback from @a-trzewik , but in the meantime I will close this.
