### ISSUE TITLE
Add Unit Tests to `DataAddress` (and fix possible issues)

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#452]
The class `DataAddress` is currently missing some Unit Tests. At the same time I assume there might be some issues within the implementation.

Here a list of things to address within this issue. But maybe there are more:

### 1. `KeyName` and `Type` Setter

I would assume the setter are only working, when the corresponding property was set before in the builder.

```java
public void setType(String type) {
        Objects.requireNonNull(type);
        properties.replace(TYPE, type);
}
```

```java
public void setKeyName(String keyName) {
        Objects.requireNonNull(keyName);
        properties.replace(KEYNAME, keyName);
}
```

### 2. Required Property of the Builder

The builder does not always check for required properties. It only validates that if there is at least one property. Looking at the null-check I assume this is an implementation error.

```java
public DataAddress build() {
            if (!address.getProperties().isEmpty()) {
                Objects.requireNonNull(address.getType(), "type");
            }
            return address;
}
```

### 3. Builder method `properties(Map<String, ?> properties)` converts object to String using `toString()`

The `DataAddress` has a `Map<String, String` which is filled by the builder method `properties(Map<String, ?> properties)`.
To convert the objects into a String the `toString()` method is called. This looks not very safe and looking at the comment I assume there is already a situation, where this doesn't work properly. Maybe change it to `properties(Map<String, String> properties)`?

```java
public Builder properties(Map<String, ?> properties) {
            // ArtifactRequestMessageImpl#urifyObjects (line 176): this "feature" converts every string starting with
            // 'http' to become a URI.
            // Thus, sometimes the <String, String> map can contain ... you guessed it ... URIs :(
            properties.forEach((k, v) -> address.properties.put(k, v.toString()));
            return this;
}
```

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
Another Issue.

The serializer will use the setter and create a property ("keyName", null) and ("type", null) if they are not set.

Please annotate them with `@JsonIgnore`.

```java

 @JsonIgnore
    public void setType(String type) {
           // code
    }

    @JsonIgnore
    public void setKeyName(String keyName) {
           // code
    }
```

@bcronin90 Maybe you can take a loot at this, too.

**Comment by bcronin90** [comment]
Waiting for merge of [493](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/493)

**Comment by bcronin90** [comment]
Solved with PR [500](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/500)
