### ISSUE TITLE
Provide openAPI spec for REST endpoints

### ISSUE THREAD

**Issue by mygordienko** [eclipse-dataspaceconnector/DataSpaceConnector#46]
Would be nice to have something providing an API description either on the build stage or in runtime. For example, it could be a swagger plugin that adds an additional endpoint, like `/swagger.json`.

**Comment by MoritzKeppler** [comment]
thx for this issue. We agree and will provide open api specs with our first release.

**Comment by ndr-brt** [comment]
Done by #522
