### ISSUE TITLE
Image assets: inclusive content / potential license issue

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#465]
Please update image assets to reflect the [Code of Conduct](https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php), e.g. (NSFW) resources under https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/samples/other/copy-file-to-s3bucket/src/main/resources

Also the license status of assets should be clarified, e.g.
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/samples/other/dataseed/dataseed-aws/src/main/resources/donald.png

**Comment by paullatzelsperger** [comment]
i think its easier to just can them and replace them with some other file. doesn't have to be an image to showcase the demo.

**Comment by mspiekermann** [comment]
If the showcase does not add value I would also vote for just removing it. Otherwise, I could change images to some that clearly are free for commercial use and no attribution is required. 
@paullatzelsperger just give me a ping if we choose the latter.

**Comment by paullatzelsperger** [comment]
as far as i remember this was one of the very first samples we did, even before the project moved to Eclipse, so I'm not even sure it still works :)
lets remove it, that'll keep the samples nice and tight.
