### ISSUE TITLE
Metrics should be posted on a separate port 

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#472]
Metrics should be posted on a separate port that is not accessible externally. With Jetty we can do this with `SelectChannelConnector`s.

_Originally posted by @algattik in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/412#discussion_r768378200_

**Comment by juliapampus** [comment]
Seems to be resolved as issue #584 was closed.
