### ISSUE TITLE
Contract offer framework

### ISSUE THREAD

**Issue by mspiekermann** [eclipse-dataspaceconnector/DataSpaceConnector#48]
Implement the framework as an extension. In a first step provide a contract that just allows everything as a response.

**Comment by jimmarino** [comment]
@MoritzKeppler Do you think it would be a good idea to create a Wiki page containing the domain model diagram and link to it from here? I would do that, but I believe I do not have the latest version of the model.

**Comment by MoritzKeppler** [comment]
have you checked the models uploaded by Dominik: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/main/docs/diagrams ?
Why "wiki page" or do you mean markdown doc in the sourcecode repo?
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
Ah, that's it, thanks.

Here is the link I was referring to:

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/diagrams/context-model-contract.png

**Comment by jimmarino** [comment]
Closing as this initial work has been completed.
