### ISSUE TITLE
IDS-Messaging

### ISSUE THREAD

**Issue by mspiekermann** [eclipse-dataspaceconnector/DataSpaceConnector#49]
-	Implement DAPS Communication / Identity Management
-	Implement an extension that understands IDS-REST messages and responses accordingly
-	/map incoming & outgoing IDS-messages into internal asset index (internal cata-log)

**Comment by MoritzKeppler** [comment]
we decided not to depend on the IDS messaging service just the information model library.

**Comment by mspiekermann** [comment]
We have the IDS communication to transfer data mostly in place, so I can fully agree to close this one, which was created to remind us on the general requiremend. If we run into additional message types, as requirements from use cases, we create separate issues as already proposed.

Just a small note for documentation: In the meantime we decided to not use IDS-REST but go for the Multipart approach first, since more background information was available.
