### ISSUE TITLE
Further Modularize core/base

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#497]
It seems like core/base is doing a lot of things:

- Registering Jetty and Jersey
- Registering SchemaRegistryImpl
- Contains NullVaultExtension
- Contains RemoteMessageDispatcherRegistryImpl

Now that we have simplified dependency ordering, can we push the module restructuring further? I have in mind:

- Place Jetty and Jersey in a separate extension that is loaded after the core extensions. Ensuring that downstream extensions require them through @Inject should be a straightforward task.

- Kill SchemaRegistryImpl as it is no longer used (correct, @paullatzelsperger?)

- Introduce a core/boot module. This module would only contain classes related to runtime bootstrap (e.g. the extension loading and related infrastructure, monitor) currently in core/base

- The core/base module remains as a service extension that is loaded prior to other core extensions. This would only include RemoteMessageDispatcherRegistryImpl and the ExponentialWaitStrategy services (which it would register). RemoteMessageDispatcherRegistryImpl needs to be loaded here since it is required by the TPM and CNM.

- Create a BOM to make referencing these modules easy

**Comment by jimmarino** [comment]
@ndr-brt is this something you have cycles to help with? If so, ping me and we can discuss.

**Comment by bscholtes1A** [comment]
Hi @jimmarino 
concerning this point:
> The core/base module remains as a service extension that is loaded prior to other core extensions. This would only include RemoteMessageDispatcherRegistryImpl and the ExponentialWaitStrategy services (which it would register). RemoteMessageDispatcherRegistryImpl needs to be loaded here since it is required by the TPM and CNM.

There is today a `CoreServicesExtension` which :
- registers the `HealthCheckService`
- register the parser in the `PrivateKeyResolver`
- register the `RetryPolicy`
- register the `OkHttpClient`

If I am properly following, you suggest that `CoreServicesExtension` registers only the `RemoteMessageDispatcherRegistryImpl` and the `ExponentialWaitStrategy`. If yes, where should we put all the `CoreServicesExtension` logic described just above?

Benjamin.

**Comment by jimmarino** [comment]
I think those are OK to keep in core

**Comment by jimmarino** [comment]
Here are a couple of additional items we need to do:

- Move WebService our of core-spi and into its own spi
- More ResponseStatus and ResponseFailure into their own package in core-spi. These classes are useful outside of the transfer implementation, e.g. from the data plane, which should not have visibility into the transfer services
- Move DataFlowRequest into core. This class will be used by the data plane as well

**Comment by bscholtes1A** [comment]
Trying to sum-up all tasks described in this thread:

- [ ] Move Jetty and Jersey in separated extension --> done with PR #508 
- [ ] Remove `SchemaRegistry` --> on-going through PR #532 
- [ ] Move all low-level infra for extensions loading, monitor... into `core/boot`
- [ ] Register `RemoteMessageDispatcherRegistryImpl` and the `ExponentialWaitStrategy` in `core/base` extension
- [ ] Create BOM (not clear to me what it precisely to be done here, @jimmarino ?)
- [ ] Move `WebService` to dedicated spi
- [ ] Move `ResponseStatus` and `ResponseFailure` into their own package within core-spi
- [ ] Move `DataRequest` into core

**Comment by paullatzelsperger** [comment]
could this be closed?

**Comment by jimmarino** [comment]
Completed
