### ISSUE TITLE
Contract negotiation

### ISSUE THREAD

**Issue by mspiekermann** [eclipse-dataspaceconnector/DataSpaceConnector#50]
-	Concept/Implementation for the negotiation using IDS-REST
-	Persist / Contract management (implement interfaces and (initially) a basic in-memory storage)

**Comment by DominikPinsel** [comment]
Hello everyone,

@denisneuling and I would like to start with the implementation. We would like to split this into several pull request:
- SPI Interfaces and implementation of
  - Negotiation Service
  - Auto Approval Service
- In Memory Contract Store (sample)
- IDS REST or Multipart

@MoritzKeppler Please assign this issue to us

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by ticapix** [comment]
Hello,

Is the use of the data exchange endpoint Gaia-X conformant self-description part of the planned negotiation happening between EDC ?

thank you,
Pierre

**Comment by bmaier** [comment]
... like GAIA-X, is the plan to produce a signed document that follows https://www.w3.org/TR/vc-data-model/ spec as the result of the negotiation?

**Comment by stefan-ettl** [comment]
@ticapix: We're planning to implement a negotiation also taking the Self-Description into account. Starting from attributes that are used e.g. in the IDS, we are planning to extend these based on the requirements of Gaia-X and use cases that use its compliant self-descriptions.

**Comment by jimmarino** [comment]
I'm going to close this out as the work is being done in #239
