### ISSUE TITLE
S3-to-S3 transfer cross account

### ISSUE THREAD

**Issue by MikhailGordienk** [eclipse-dataspaceconnector/DataSpaceConnector#510]
Hello!
Currently, a cross-account transfer is not possible, because `S3toS3DataStreamer` does not have any hook methods to configure the access.
I think there should be something along these lines:

```
interface AccessConfigurator {
    setUp(DataAddress destination, DataAddress source);
    cleanUp(DataAddress destination, DataAddress source);
}
```

or 

```
interface AccessConfigurator {
    setUp(DataRequest dr);
    cleanUp(DataRequest dr);
}
```

It must be done on the publisher side (the Consumer does not need to know the Publisher's account), and it should not be configured in advance since the `DataRequest ` might never come.

**Comment by jimmarino** [comment]
Hi @MikhailGordienk,

Can you take a look #463? The idea was to enable optimizations when transferring data across a common infrastructure, e.g. cloud provider, such as copy-in-place. Specificlly,

```
/**
 * A data sink.
 */
public interface DataSink {

    /**
     * Transfers the data to the sink, returning a future to obtain the result. Implementations may be non-blocking.
     */
    CompletableFuture<Result<Void>> transfer(DataSource source);
}
``` 

In the transfer method implementation, the sink can determine if the source is an instance of a particular subtype, cast to it, and reference specialized methods to perform the needed operation.

Will that work for your case?

**Comment by MikhailGordienk** [comment]
Hi @jimmarino !

I don't think the DPF concept solves the problem I described. As I understood, the DPF is an alternative, consumer-driven transfer layer. There is already a transfer layer - DataFlowController, it is just provider-driven. In both cases there might be a need for provisioning, preparing the required infrastructure. So the problem I mentioned is closer to Resource management (provisioned resources and TransferProcess state). And there might be provisioning on both sides - on the Consumer side we might need to create a bucket and a user, and on the Provider side, we might need to configure access (as it is in my case).

**Comment by jimmarino** [comment]
DPF is a data plane implementation for the connector. A DataFlowController (in this case the HttpFunctionDataFlowController) would call out to the DPF either on the client or producer side depending if the transfer is pull or push.

As a general rule, resource creation should be done using a provisioner, not in a DataFlowcontroller.
