### ISSUE TITLE
Logging and Monitoring

### ISSUE THREAD

**Issue by mspiekermann** [eclipse-dataspaceconnector/DataSpaceConnector#52]
Write an extension for basic logging and monitoring

**Comment by jimmarino** [comment]
I think this is already covered by the console monitor. This output can be piped directly from a deployed container to logging infrastructures such as DataDog or LogStash or stated. 

Is there an additional requirement?

**Comment by MoritzKeppler** [comment]
logging: maybe users want ways to format log lines in a unique way (add fields dynamically, json format, ...); maybe System.out
monitoring: offer endpoints for tools like prometheus etc.
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by softabout** [comment]
I think it would make sense to define different extensions for logging and monitoring and use/integrate - if possible - already existing implementations (e.g. logging -> slf4j). 
The console monitor as currently defined provides basic logging functionality but does not provide interfaces for monitoring the performance and health of the system.

<sub> Helmut Pfister <helmut.pfister@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by jimmarino** [comment]
A JDK logging extension has been created and it is possible to change the console monitor implementation so I'm going to close this issue out.
