### ISSUE TITLE
Error: "Token audience did not match required audience: null"

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#520]
I'm trying to make two connectors communicate using DAPS, but, on the validation of the token on the provider side I get this error:

`Token audience did not match required audience: null`

Looking at the code I think that's because a `null` is passed as audience value to the `verifyJwtToken` of the IdentityService:
Should that value read from the configuration instead?

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/ce440245189ca48f2a10a63c51c7f8b223660756/data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/controller/MultipartController.java#L98

EDIT: not strictly releated, but I noticed this `DapsService` interface and implementation that are not used by anyone, can they just go away?
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/6193ffa2fcc1e9b081851ac26570e5da456b572b/data-protocols/ids/ids-spi/src/main/java/org/eclipse/dataspaceconnector/ids/spi/daps/DapsService.java

**Comment by jimmarino** [comment]
@bscholtes1A I couldn't add you to this, can you add yourself?
