### ISSUE TITLE
Connector ID property duplication

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#525]
I went through this problem where, although I set the `connectorId` through the `edc.connector.name` property
(https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/aaa2ae95ffa7d3b537df197016fd05349c684b86/core/base/src/main/java/org/eclipse/dataspaceconnector/core/system/DefaultServiceExtensionContext.java#L166)

another connectorId appeared on some ids calls, with the value `urn:connector:edc`. I found out that's the default value for a property named `edc.ids.id` that is read by a method called `resolveConnectorId` present in two different extensions, one is here: 
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/9835f6d5c501540db92fc8eb31522887e255f75b/data-protocols/ids/ids-api-multipart-dispatcher-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/dispatcher/IdsMultipartDispatcherServiceExtension.java#L101

Do we need both those ids or we just need one of them? Which are the preferred? It's correct the existence of a default value for that property? (having two connectors with the same id should not be permitted).

**Comment by paullatzelsperger** [comment]
the IDS connector name might be different from the connector ID, which e.g. is used for locking shared resources in clustered environments.

**Comment by ndr-brt** [comment]
Ok, so they are two different ids, currently this is confusing because they are used with the same name. Could make sense a PR to rename their occurrences accordingly?

**Comment by ndr-brt** [comment]
Closed as it seems not so relevant.
