### ISSUE TITLE
Fix Sample 5: BlobStoreApi not "injectable"

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#564]
The `CloudTransferExtension` tries to inject the `BlobStorageApi`. But the corresponding extension was converted to a library some time ago.

```java
public class CloudTransferExtension implements ServiceExtension {
    public static final String USE_EU_POLICY = "use-eu";
    @Inject
    private DataFlowManager dataFlowMgr;
    @Inject
    private DataAddressResolver dataAddressResolver;
    @Inject
    private BlobStoreApi blobStoreApi; /* doesn't work */
    @Inject
    private DataOperatorRegistry dataOperatorRegistry;

   /* more code */
}
```

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by ndr-brt** [comment]
The problem is that `BlobStoreApi` is registered by `blob-provision`, but it should be provided by `blob-core`, right?

**Comment by DominikPinsel** [comment]
As the CloudTransferExtension mainly registers a new `FlowController`, I would let the extension initialize the `BlobStorageApi` itself. A reference to the `blob-provision`, just to get the API, doesn't seem the correct way to do it.

@ndr-brt Would this be fine, too?

**Comment by ndr-brt** [comment]
Would work, yes, but looking at the future, registering the `BlobStorageApi` directly in the `blob-core` if not directly in the `blob-api` extension seems like the best choice, so it will be registered automatically for every extension that depends on that module
(as `blob-data-operator` and `blob-provision`)

@bscholtes1A you worked recently on this part, what do you think?

**Comment by paullatzelsperger** [comment]
I agree with @ndr-brt on this. The `BlobStoreApi` should be registered in `blob-api` using a new extension, e.g. `BlobStoreApiExtension`. By that point though I'd argue in favor of merging `blob-core` and `blob-api`.

**Comment by ndr-brt** [comment]
:+1: on merging `blob-core` and `blob-api` and make `blob-core` provide the `BlobStorageApi` feature

**Comment by DominikPinsel** [comment]
Merging `blob-core` and `blob-api` sounds good. 

@paullatzelsperger  As you wrote the initial code, you can assign the issue to you, too, if you want.
