### ISSUE TITLE
Inject mock services

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#569]
It appears mock services directly registered with the JUnit runner cannot be injected. A service extension implementation is needed so that provides can be specified. 

I'll look into either fixing this or providing a way to handle this by automatically creating an extension behind the scenes.

**Comment by algattik** [comment]
If we change `DefaultServiceExtensionContext.registerService`, not to overwrite a service if already registered (which sounds sensible also at runtime, to respect classpath order), then we can use the existing `registerServiceMock` method:

```
    @BeforeEach
    protected void before(EdcExtension e) {
        edc.registerServiceMock(ContractNegotiationStore.class, mock(ContractNegotiationStore.class));
    }
```

**Comment by ndr-brt** [comment]
@algattik I agree with this proposal, don't know if there are hidden downsides, in the meantime a more safe solution is to have a test extension of the  `DefaultServiceExtensionContext` class that overrides the `registerService` method:
```
@Override
    public <T> void registerService(Class<T> type, T service) {
        if (hasService(type)) {
            getMonitor().warning("A service of the type " + type.getCanonicalName() + " was already registered and it will not be replaced");
        } else {
            super.registerService(type, service);
        }
    }
```
