### ISSUE TITLE
Add IDS Description field to `Assets`

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#578]
At the time of writing it is not possible to send the description of an asset to another connector. 

Therefore, this issue is about introducing a new property key `ids:description` that is written into the [IDS Resource](https://github.com/International-Data-Spaces-Association/Java-Representation-of-IDS-Information-Model/blob/main/de/fraunhofer/iais/eis/Resource.java) description field.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
PR #579

**Comment by paullatzelsperger** [comment]
Are you suggesting mapping a generic Asset description into the (specific) IDS description? The Asset shouldn't have IDS-specific properties, they need to be mapped.
