### ISSUE TITLE
Data Plane Framework (DPF) API

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#585]
## Overview

- As mentioned in #463, DPF is (or can be) a separated runtime that _lives_ independently of the Control Plane, e.g. in a dedicated POD, as a sidecar... Thus it should expose API to support the following types of data transfer:

1. client pull: consumer actively pulls data from the consumer,
2. provider push: data is pushed asynchronously from the provider to the consumer,
3. event streaming: same as (2) except that data source is now a stream: events are pushed continuously to the consumer 

Supporting these three configuration requires two kinds of API in the data plane. 

- **Control Plane API** used to trigger the data transfer from the control plane (push)
- **Data Transfer API** used to request data (pull) 

### Sequence

- Consumer control plane sends artifact request to the provider control plane which returns back a signed token containing the data address (obtained from the `Asset`) and the `contractId`,
- It is now up to the consumer to hit the public API exposed by the Provider DPF with the previous token in order to collect the data,
- Token is forwarded to the validation façade exposed by the provider control plane, in order to decode the signed token, 
- If token is valid then data address is returned back to the DPF which then hits the provider data source to retrieve the data.
- Data is then passed returned in the response.

![client_pull drawio](https://user-images.githubusercontent.com/88310985/152530072-3bb940a1-8739-405e-b509-c47933f00fe1.png)

There will be a `DataPlaneResolver` that will resolve the incoming request into a public URL and the data plane to use for the transfer.

### Additional requirements

- at least `GET`, `POST` and `PUT` verbs should be supported
- it should be possible to convey query parameters to the data source.

Controller for public API exposed by the DPF would then look like this:

```
public interface DataPlanePublicApiController {

    @GET
    @Path("/{token}")
    Object get(@PathParam("token") String token, @Context UriInfo uriInfo) {
       ...
    }

    @POST
    @Path("/{token}")
    Object get(@PathParam("token") String token, @Context UriInfo uriInfo) {
       ...
    }

    @PUT
    @Path("/{token}")
    Object get(@PathParam("token") String token, @Context UriInfo uriInfo) {
       ...
    }
}
```
 
### Sequence

- Consumer control plane sends artifact request to the provider control plane which acknowledge the consumer that its request is being processed, i.e. policy and other checks have been successfully performed...
- Provider control plane then hits its DPF API to initiate the flow (it is recommended to leverage on http function extension here) => request contains both the source and destination data addresses,
- The provider DPF then hits the data source and push back the data provided destination data address, which can be an endpoint exposed by the consumer DPF or any other endpoint (S3 bucket, Azure blobstorage...).

![provider_push drawio](https://user-images.githubusercontent.com/88310985/152364497-cd764533-ae19-42f6-9316-a674fd7a726e.png)

Controller for the _internal_ DPF API should be as follows

```
public interface ControlPlaneApiController {

    @POST
    Response initiateFlow(DataRequest request) {
       ...
    }

   @POST
   void cancelTransfer(String processId) {
      ...
   }
}
```

All push data transfers are by default trackable and persisted in a dedicated store maintained by the data plane (in-memory, cosmos...)

### Sequence

- Consumer control plane sends artifact request to the provider control plane which acknowledge the consumer that its request is being processed, i.e. policy and other checks have been successfully performed...
- Provider control plane then hits its DPF API to initiate the flow, which triggers the creation of a `Subscriber` (if none was already existing for this data source),
- `Subscriber` persists the provision message in a store for recovery purpose,
- `Subscriber` then consumes from the event source (e.g. Kafka topic...) and convey the event as a `DataSource` to the pipeline along with the destination data address which is used to create the `Sink`. **Note that there can be more than one destination data address!**,
- Event is then propagated to the `DataSink`, which can for example be an event system (e.g. Azure EventGrid) to which the consumer applications can subscribe, a multicast sink that pushes event to consumer through http, or even a combination of both (`CompositeSink`)
- In case of a crash of the Data Plane, the persistent store is used to restart the `Subscriber` instances.

![streaming drawio](https://user-images.githubusercontent.com/88310985/152529665-c4b6bad5-7b43-48ca-a7ec-7c2536015408.png)

**Comment by paullatzelsperger** [comment]
Hey @bscholtes1A, thanks for this, looks promising. I did have a couple of remarks though:
- `ControlPlaneApiController`
  - `DataTransferDto`: that might need some sort of `correlationId`, which could be the ID of the transferprocess. 
  - `DataAddress`: for consistency that should be a `*Dto` as well, even if its probably identical to the `DataAddress`
  - Maybe for a future version we'll need some "Cancel" endpoint as well
- `PublicDataPlaneController`: 
  - Am I right in assuming that a contract must be established?
  - Why is the destinationDataAddress needed? Whouldn't the data be wrapped in the response to that `GET` call?
  - We'll have to be able to handle the other HTTP Verbs as well, at least `POST and PUT`.

**Comment by MoritzKeppler** [comment]
thx for the proposal, @bscholtes1A !

Some questions, especially to the "Client Pull" scenario which matches our ideas how to (offer a REST API)[https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/567] like the one defined by [AAS](https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShell-REST-API/Final-Draft) via the connector:

1. Which of the calls is thought to be a sync http request/response? Guess the steps 2 - 6 are one http roundtrip, whereas 0 and 1 are potentially async messages. Right?
2. What needs to be changed to keep the data plane running even if control plane is down? E.g. can we avoid a call to control plane with every request?
3. understood that the idea of passing the encrypted data address as token to the consumer helps to keep the data plane on provider side stateless. Do we have other options to avoid passing any internal information to a consumer (even if it's encrypted something I like to avoid from a security perspective)
4. the proposed `DataPlanePublicApiController` takes the token as path param - how could that be used to grant access to various endpoints of a REST API?
5. The credentials needed to access the actual data source (step 4) are stored in a vault, right?

thanks a lot!

<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/cImpressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by MoritzKeppler** [comment]
@bscholtes1A  I could offer to update the diagrams we provided in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/567 according to this issue and the code contributions you provided. Would be great to have some docs in the repo
