### ISSUE TITLE
DataManagementApi: Create API for ContractNegotiations

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#589]
_This issue only deals with the API, i.e. a stub for the `*Controller` class. An implementation is explicitly NOT to be done._

## API Endpoints
- `GET /api/v1/contractnegotiations`: gets all ContractNegotiations, accepts paging spec, returns `List<ContractNegotiationDto>`
- `GET /api/v1/contractnegotiations/{id}`: gets one particular `ContractNegotiationDto`
- `GET /api/v1/contractnegotiations/{id}/state`: gets the state of one particular negotiation, useful for polling 
- `POST /api/v1/contractnegotiations/{id}/cancel`: moves the ContractNegotation to the `CANCELLING/CANCELLED` state. Throws `IllegalStateException` if not possible. Returns `void`
- `POST /api/v1/contractnegotiations/{id}/decline`: moves the ContractNegotation to the `DECLINING/DECLINED` state. Throws `IllegalStateException` if not possible. Returns `void`.

## DTOs
```java
public class ContractNegotiationDto{
    private String id;
    private String counterPartyAddress;
    private String protocol;
    private Type type = Type.CONSUMER;
    private String state;
    private String errorDetail;
    private String contractAgreementId; // is null until state == CONFIRMED
    //getters, setters,...
}
```
Code should go into `extensions:api:data-management:contract-negotiation`

**Comment by florianrusch-cluetec** [comment]
I will work on this

**Comment by florianrusch-cluetec** [comment]
@paullatzelsperger is the package name written in plural correct? At the other issues they are written in singular.

**Comment by paullatzelsperger** [comment]
corrected

**Comment by florianrusch-cluetec** [comment]
@paullatzelsperger Package name with `.` or combined?
- `org.eclipse.dataspaceconnector.api.data.managment`
- `org.eclipse.dataspaceconnector.api.datamanagment`

**Comment by paullatzelsperger** [comment]
Don't have a strong opinion, but would lean towards "combined"

**Comment by paullatzelsperger** [comment]
@florianrusch-cluetec updated the description, added the `GET ..../state` endpoint, which was previously in the #628 issue.

**Comment by florianrusch-cluetec** [comment]
@paullatzelsperger should the `GET .../state` endpoint return this object (`org/eclipse/dataspaceconnector/api/control/response/NegotiationStatusResponse.java`) or just the plain state as string?

**Comment by paullatzelsperger** [comment]
In the `GET .../state` endpoint I'd return a String, and I'd also keep a String in the `ContractNegotiationDto`.
On the client side it doesn't make much of a difference whether to parse a String or an int anyway, so at least a String is more readable.

**Comment by florianrusch-cluetec** [comment]
@paullatzelsperger short question and then the PR should be ready: You wrote at the DTO schema, that the type should always be `CONSUMER`. What is the reason for this?
