### ISSUE TITLE
Record and publish an onboarding video

### ISSUE THREAD

**Issue by beardyinc** [eclipse-dataspaceconnector/DataSpaceConnector#59]
In order to become more scalable a short video introduction to the different moving parts of the connector will be recorded.
Most notably this will involve the following areas not necessarily in that order:
- basic folder structure
- nomenclature (what is a "runtime", "connector", "launcher", "extension", etc.)
- the ServiceLoader mechanism
- core components such as `Vault`,` Monitor`, `TransferProcessManager`, `Provisioner`, `DataFlowController`, Policies, etc.
- the role of IDS
- why we try to avoid third party dependencies

We should publish that video to Youtube unless the Eclipse Foundation has special requirements. @mspiekermann can you follow up on this with EF?

**Comment by mspiekermann** [comment]
Si, I will clarify that with EF asap.

**Comment by beardyinc** [comment]
Videos are done, I put them in my OneDrive and will share the link upon request.

**Comment by mspiekermann** [comment]
YT channel created and videos published (s. https://www.youtube.com/channel/UCYmjEHtMSzycheBB4AeITHg). Thanks a lot @beardyinc, great resource for onboarding new people.
