### ISSUE TITLE
DataManagementApi: Create API for Policies

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#590]
_This issue only deals with the API, i.e. a stub for the `*Controller` class. An implementation is explicitly NOT to be done._

## API Endpoints
- `POST /api/v1/policies`: creates a new Policy, accepts `PolicyDefinitionDto` in body, returns `void`
- `GET /api/v1/policies`: gets all defined policies, accepts paging spec. Returns `List<PolicyDefinitionDto>`
- `GET /api/v1/policies/{id}`: gets one particular policy as `PolicyDefinitionDto`
- `DELETE /api/v1/policies/{id}`: deletes a policy definition if possible

## DTOs
```java
public class PolicyDefinitionDto {
    private final List<Permission> permissions = new ArrayList<>();
    private final List<Prohibition> prohibitions = new ArrayList<>();
    private final List<Duty> obligations = new ArrayList<>();
    private final Map<String, Object> extensibleProperties = new HashMap<>();
    private String inheritsFrom;
    private String type = "SET;
    //getter, etc.
}

**Comment by florianrusch-cluetec** [comment]
@paullatzelsperger You said to @dr-markus that this issue needs to be discussed with Jim, is that still the case?

**Comment by paullatzelsperger** [comment]
How policies are handled internally should not greatly influence the API. However, we will keep semantic consistency with other BOs, so only create, read and delete will be implemented in M3.
