### ISSUE TITLE
Data Plane Framework (DPF) deployment

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#592]
As mentioned in #463, it must be possible to deploy the DPF:

- to a K8s cluster
- remotely from the control plane
- deploy the DPF in the same process as the control plane (demo/testing)

We need to provide the required material in order to support these different deployment topologies:

- a runtime, i.e. `.kts` file,
- a Dockerfile, 
- a `Deployment` K8s file

**Comment by juliapampus** [comment]
Is this something that has been solved or should I move it to M3? @jimmarino @bscholtes1A
