### ISSUE TITLE
Create Onboarding Experience

### ISSUE THREAD

**Issue by beardyinc** [eclipse-dataspaceconnector/DataSpaceConnector#60]
In order to make it easier to welcome new community members (devs, companies, ...) we should create an easy-to-understand onboarding experience.

I propose a multi-step tutorial:
1) build and operate your first connector (i.e. the `launchers/basic` launcher)
2) write your first extension e.g. write a simple HTTP `/hello-world` endpoint
3) implement your first file transfer process using the file-copy example created by @DominikPinsel 
4) improve the file transfer to copy a file from Azure Blob Store to AWS S3 (optional)

Accompanying this I'll record an Onboarding Video [(see the respective issue)](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/59) explaining the different moving parts of the connector code base

**Comment by mspiekermann** [comment]
PR #61  merged
