### ISSUE TITLE
CI Build: Move self-contained integration tests into another workflow

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#604]
All the self-contained integration tests, that is the ones that don't depend on external systems, should be moved out of `integrationtests.yaml` into to a separate workflow, so that they can run on every PR push, even on forks.

At the time of this writing those are:
- Object Storage StatusChecker Test
- AWS S3 StatusChecker Test
- Daps Integration Test

This new workflow should run on every push on PRs, thus also on forks.

**Comment by ndr-brt** [comment]
This is not needed anymore. Ref #376
