### ISSUE TITLE
Health check startup status lazyness

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#605]
Currently, the `HealthCheckService` is started at it's instantiation, that's during the `inititalize` phase.

Doing so, the first execution of the `query` runner will always update the cache with a "unhealthy" state, and that's correct, because during the initialization the connector is not yet started.

Unfortunately, also after all the extensions startup we have to wait the whole "startupStatus" period to have that checks updated (by default 60 seconds), until then the connector will be marked as "unhealty"

There's the possibility to reduce that time in configuration, but I think we need a more general approach.

A solution that comes to mind could be to have a method on the `HealthCheckService` that permits to force the cache update, that could be called by the runtime after completing the startup.
@paullatzelsperger what do you think?

**Comment by paullatzelsperger** [comment]
Sounds reasonable. I agree, overloading the `query[Liveness|StartupStatus|Readiness]` methods would be the lowest hanging fruit here.

Another more invasive way would be to have some sort of listener/observer concept on the *providers, which allows them to initiate a cache update.

Maybe do the first approach first and keep the second approach in mind for when we do the telemetry+metrics stuff (not formally planned yet)?

**Comment by ndr-brt** [comment]
Yes, let's go with the first approach that will solve the issue for the moment. PR opened
