### ISSUE TITLE
DPF - Azure Object Storage Extension

### ISSUE THREAD

**Issue by zeier** [eclipse-dataspaceconnector/DataSpaceConnector#618]
# Overview

This issue adds the Azure Object Storage extension for stream copy to the Data Plane Framework (DPF) #463 to read data from and write data to Azure Blob Storage.

### Data Movement

- Extend the existing DPF Transfer function controller to:
  - Read data from Azure Blob Storage
  - Write data into Azure Blob Storage
- Azure SDK streams operations are used to perform data operations. This will support large datasets as well.
- End-to-end testing on Azure
- Test execution to validate builds

### In-Place Copy and Parallelization (Out of Scope)

In-place copy and parallelization are out of scope for this issue.

#773 will provide another extension that uses Azure Data Factory for optimized transfers.

Additional optimizations (parallelization and server-side copy) without usage of Azure Data Factory could be implemented in a subsequent step if needed.

**Comment by zeier** [comment]
Updated to reflect usage of Azure Data Factory instead of implementation of parallelization and server-side copy to optimize throughput and latency.

**Comment by algattik** [comment]
Item left is to share a thread pool across all DataSink implementations. We will raise a PR for this.

**Comment by zeier** [comment]
Made delineation between this issue and #773 clearer by mentioning that Azure Data Factory is out of scope for this issue.
