### ISSUE TITLE
core:transfer module depends by an extension

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#620]
Seems like the core:transfer depends from an extension:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/core/transfer/build.gradle.kts#L24

Core modules should not depend on extensions, only on spi and other core modules eventually (like core:base)

**Comment by paullatzelsperger** [comment]
Haven't looked at it closely, but i suspect this is because there is an SPI inside `inline-data-transfer`, which should probably be moved to the more general `spi/transfer-spi` module

**Comment by ndr-brt** [comment]
Seems like it's because currently, `core-transfer` register `DataOperatorRegistry` service.
I think it should be registered by `inline-data-transfer-core`.

**Comment by paullatzelsperger** [comment]
technically it could, but especially for samples and quick-start-situations it may make sense to have this available, so that we do not have to deploy a fully-fledged DPF. Alternatively we can come up with an easy embedded DPF, that replaces the `inline-data-transfer-*` stuff.
