### ISSUE TITLE
Add option to update provider-side resource address;

### ISSUE THREAD

**Issue by MikhailGordienk** [eclipse-dataspaceconnector/DataSpaceConnector#627]
During consumer-side resource provisioning it is possible to update the destination information 
(e.g. add information about provisioned S3 bucket and credentials). But there is no way to update the corresponding 
source information. Consider the scenario when resources are stored in an external system that generates temporary 
download URLs on-demand (like S3 does). These URLs would be associated with specific `TransferProcess`. Essentially, they are 
resources that need to be provisioned.

A solution to this could be:

* Get URL during the provisioning phase on the provider side
* Update the source `DataAddress` in the corresponding `DataRequest` object

The problem is `DataRequest` does not have that address, it holds only assetId. 

Obviously, the idea was to resolve actual source coordinates on-demand since they are not of consumer's concern. It is possible to have a specific `AddressResolver` implementation, that resolves source `DataAddress` based on provisioned resources, but such implementation is bound to use `TransferProcess` registry and can't work with assets not requiring provisioning. So a generic implementation is needed. `Asset` does not have a special flag indicating whether it has associated provisioned resources, and doubtfully it has to.

I think the best way here would be to resolve source `DataAddress` when `DataRequest` instance gets created and allow that address to be updatable during the provisioning phase.

Please see also [this issue](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/575) since it is related.

**Comment by MoritzKeppler** [comment]
A similar scenario can occur if it takes time to extract and prepare the data, think of extracting data from a data lake, a machine etc.

Would prefer a solution that works similar to the provisioning on consumer side, e.g. introduce something like `ProvisionedDataSourceResource` (see `ProvisionedDataDestinationResource`) and then store the source address as an additional attribute at the `TransferProcess` (maybe prefilled with the DataAddress of the referenced asset. 

What do you think @paullatzelsperger ?

<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
