### ISSUE TITLE
API for Metadata management

### ISSUE THREAD

**Issue by mygordienko** [eclipse-dataspaceconnector/DataSpaceConnector#66]
How metadata records are supposed to get into _MetadataStore_? For now, there is no API for that, only some test values get stored during Nifi extension initialization.

**Comment by MoritzKeppler** [comment]
We plan to replace MetadataStore with Contracts, ContractOffers, Assets, AssetIndex etc, see https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/Terminology.md
Assume there will be multiple implementations in future, e.g. an AssetIndex that is backed by an existing data catalog (e.g. ApacheAtlas) but also a solutions that offer REST APIs to manage metadata of Assets.
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
Closing this as these capabilities are implemented by the AssetIndex and DataLoader framework.
