### ISSUE TITLE
Unstable tests in CI

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#728]
Running 100 CI builds shows 17 failures mostly in unit tests.

It seems the introduction of Jacoco (#702) has increased test time by ~50%, which might cause some timeouts or race conditions to be hit. *(NB: in another PR we will disable Jacoco outside of CI, to improve the developer experience)*

Problems seem to be in:
- Multiple tests using OkHttp client. Default timeouts are quite short.
- LoaderManagerImplTest#batchSizeNotReachedWithinTimeframe, which relies on a 100 ms timeout.

**Comment by ndr-brt** [comment]
Also `JerseyRestServiceTest` sometimes breaks, I think that's because it's not using the `getFreePort` method

**Comment by algattik** [comment]
> Also `JerseyRestServiceTest` sometimes breaks, I think that's because it's not using the `getFreePort` method

This was solved by #642 it seems

**Comment by ndr-brt** [comment]
Oh well, I forgot that, and that was me :D
