### ISSUE TITLE
Create Checkstyle configuration and Github Action

### ISSUE THREAD

**Issue by beardyinc** [eclipse-dataspaceconnector/DataSpaceConnector#73]
In order to ensure a consistent code style let's create a [CheckStyle](https://checkstyle.sourceforge.io) configuration that is enforced as a pre-PullRequest check on Github.

Why CheckStyle? Because it's open-source, widely used, highly configurable, has plugins for most Java IDEs, Gradle, Maven and also has a (actually several) Github Action(s).

Checkstyle is configured using an XML file, which will be committed here. The initial config will be based on [Google's Style](https://checkstyle.sourceforge.io/google_style.html).

Once this issue is done, devs can simply reference the CheckStyle config via HTTP in their IDE.

PS: As convenience I will also create a [SaveActions](https://plugins.jetbrains.com/plugin/7642-save-actions) config, that reformats code such that it conforms to the Checkstyle configuration.

**Comment by jimmarino** [comment]
LGTM. Quick question - Is there a way enforce line wrapping minimums and maximums?

**Comment by beardyinc** [comment]
There sure is for maximums: https://checkstyle.sourceforge.io/config_sizes.html#LineLength
currently we have that set at 250. 
Can't really think of a use case where a min line length would make sense. Mostly we'd have to do that with any of the other (code style) checks.
