### ISSUE TITLE
Multiple extensions for the same feature

### ISSUE THREAD

**Issue by MikhailGordienk** [eclipse-dataspaceconnector/DataSpaceConnector#75]
Will it be possible to support multiple extensions of the same type (ex. multiple Vault types)?

**Comment by jimmarino** [comment]
This is currently supported in two ways:

1. One Vault implementation can be substituted for another by configuring the appropriate extensions (e.g. include the Vault module you want in your build)

2. In case you want to store secrets in different places, implement a multiplexing vault extension that delegates to different Vault backends
