### ISSUE TITLE
IDS: `ContractOffer` is missing values for `provider` and `consumer`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#753]
### Problem statement
in the `ContractValidationServiceImpl` there is a check in place that requires that both the `provider` and `consumer` fields of a `ContractOffer` be not-null:
```java
private boolean isMandatoryAttributeMissing(ContractOffer offer) {
    // TODO add contractStart and contractEnd check as soon as the Infomodel serializer is used
    return offer.getProvider() == null || offer.getConsumer() == null;
}
```
However, those values are never set, which causes **all contract negotiations to be declined**.

### Proposed solution
The `provider` and `consumer` fields must be set during the creation of the `ContractOffer`, which is done in the `ContractOfferServiceImpl`. 

Suggestion:
- `provider`: the offering connector's ID as URN
- `consumer`: the ID of the `ParticipantAgent` for whom the offer is generated

**Comment by MoritzKeppler** [comment]
What is the ID of the ParticipantAgent? The `sub` of the corresponding JWT token?
What about using the "referringConnector" property if set?
See also https://github.com/International-Data-Spaces-Association/IDS-G-pre/blob/main/Components/IdentityProvider/DAPS/README.md

**Comment by juliapampus** [comment]
@MoritzKeppler The DSC uses the `connectorId`, so the `referringConnector` as suggested by you. Nevertheless, the IDS in general defines something different (as I understood): [Here](https://github.com/International-Data-Spaces-Association/InformationModel/blob/develop/model/contract/Contract.ttl), `consumer` and `provider` are represented by an `ids:Participant`. The reason why we never implemented this, was that there was no ParIS and no defined participant handling.

**Comment by sebbader** [comment]
Actually, the case where they are not set is an important one (for an offer, not an agreement, an agreement needs both defined): `consumer = null` -> 'this offer is applicable to any Participant who is interested'
So, is this if clause in the `isMandatoryAttributeMissing` really needed?
