### ISSUE TITLE
DPF Azure extension: support Azure Data Factory (serverless)

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#773]
Serverless data transfer infrastructure is provided by major cloud providers and integration software vendors. For example, Azure Data Factory (ADF) offers a serverless way to copy data at scale in an optimised manner. As a managed service, it offers increased scalability and reduced operational load on the application when copying data.

Serverless offerings cannot replace DPF stream-based copy, since EDC users may not want a vendor dependency, and each serverless product supports a limited range of integrations. Serverless transfer can, however, be an optional module in DPF. DataFlowRequests can be routed to either serverless transfer or DPF source/sink streams, depending on rules to be defined, such as whether the serverless platform supports the source and sink, as well as transfer size.

**Comment by algattik** [comment]
`DataPlaneManagerImpl` is currently calling `PipelineService` to perform a synchronous transfer request.
We want to do the following:
1) Other services than `PipelineServiceImpl` should be able to serve the request. E.g. a DataFactory service. Just like `PipelineServiceImpl` is resolving a source and a sink factory from multiple extensions based on the request, we want `DataPlaneManagerImpl` to resolve a `TransferService` based on the payload. Multiple TransferServices might be able to accept the payload, e.g. the `PipelineService`, the AzureDataFactory service, AwsDataPipeine etc. A `Strategy` is then used to decide which implementation to favour. The default `Strategy` will pick first-from-classpath; the user may plug in something more complex for their preferences.
2) `DataPlaneManagerImpl` is currently synchronous. This means a thread is hogged for the duration of the transfer, and transfers are lost on crashes. This is not good for potentially large transfers which could last minutes or hours. We could use the state machine library from https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/787 to better support asynchronous poll-based processes. **That will be looked at in a subsequent step, for now synchronous polling is enough for a first PR**

**Comment by jimmarino** [comment]
Looping in @bscholtes1A here as well.

**Comment by jimmarino** [comment]
FYI @algattik will do some refactoring to introduce a concept of a `TransferService` to handle ADF and other 'server-side' transfer services. The existing `PipelineServiceImpl` will become an implementation of that more general interface. This shouldn't impact the API controllers/filters.

**Comment by bscholtes1A** [comment]
Hi @algattik and @jimmarino 
Might be a stupid question but we have been discussing recently how to handle streaming of events through the Data Plane here: #585. Especially it was proposed to have a `Subscriber` (e.g. kafka consumer) that pushes events to the `PipelineService`.

Based on what you suggested, could we consider having an implementation of `TransferService` that covers this streaming use-case?
