### ISSUE TITLE
CosmosDB tests are broken

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#774]
Seems like #721 make cosmos db integration tests fails, mainly because the PR brought the `container` object instantiation at class level and added a `deleteAllItems` function after every test execution, but this seems like it's not supported on the test instance:
```Partition key delete feature is disabled for this account.``` (ref: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5356527290)

**Comment by algattik** [comment]
@ndr-brt also note that cleanup in CosmosContractDefinitionStoreIntegrationTest is not working properly because one test is changing the partition key. I'll fix that in my upcoming PR

**Comment by ndr-brt** [comment]
@algattik which one? I have my PR ready so I can add this fix right on.

**Comment by algattik** [comment]
https://github.com/agera-edc/DataSpaceConnector/pull/111

**Comment by ndr-brt** [comment]
Nice, so now they are working every time? Can I assign this issue to you then?

**Comment by ndr-brt** [comment]
Ok, hust saw the comment on #360. will close this
