### ISSUE TITLE
[Eclipse] provide SECURITY.md

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#78]
At the latest with our first release we should provide a SECURITY.md describing how vulnerabilities can be reported.

See: 
https://www.eclipse.org/security/policy.php
https://gitlab.eclipse.org/eclipse/dash/org.eclipse.dash.handbook/-/issues/150

Example: 
https://github.com/eclipse/rdf4j/blob/main/SECURITY.md

<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by mspiekermann** [comment]
Can be closed by merging PR #85
