### ISSUE TITLE
System tests for EDC core: folder structure and performance test setup

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#783]
In #665 and #701 we built a system test around sample 4 to test end-to-end flow across application instances. However, system tests should have a different lifecycle than samples. They should be able to be scaled up for performance testing. Samples should remain as simple as possible for new users to understand the behaviour of EDC.

- Move system test out of the samples directory. Create new projects under root `system-tests` directory. System tests should use their own set of `launchers` to configure EDC applications to run (e.g. sample 4 consumer EDC instance and provider EDC instance). Do not "pollute" the root  `launchers` directory with system-test specific stuff.
- Wrap client call with Gatling to build an illustrative performance test set up. The load test should run as fast as possible (i.e. for a single query), but be configurable to run higher load tests manually.

Note: DPF is not yet integrated in the system test.

Note: there is no new test code or logic to write (except to bind into Gatling).

**Comment by ndr-brt** [comment]
could `system-tests` folder be a good place also for e2e tests without performance purposes?

**Comment by algattik** [comment]
> could `system-tests` folder be a good place also for e2e tests without performance purposes?

Yes absolutely. Performance tests are just one kind of system tests. (It often just makes sense to reuse the end to end scenarios for system validation as scenarios to scale on)
