### ISSUE TITLE
S3StatusCheckerIntegrationTest unstable

### ISSUE THREAD

**Issue by algattik** [eclipse-dataspaceconnector/DataSpaceConnector#795]
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5404183090?check_suite_focus=true

```
2022-03-03T08:42:26.6733834Z S3StatusCheckerIntegrationTest > isComplete_noResources_whenNotComplete() FAILED
2022-03-03T08:42:26.6735270Z     java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Connection refused: localhost/127.0.0.1:9000
```

Race condition because we don't wait for the emulator to be fully started?

**Comment by paullatzelsperger** [comment]
The MinIO image doesn't seem to include a HEALTHCHECK (check [Minio Github](https://github.com/bitnami/bitnami-docker-minio/blob/master/2022/debian-10/Dockerfile)), so the proper way to do this would be to create our own MinIO image that has a health check. 

The second options, would be to create a default bucket using an [environment variable](https://github.com/bitnami/bitnami-docker-minio#creating-default-buckets) and have a wait-loop in the test waiting for that bucket to become available.

...and one makes three: MinIO offers a [http health endpoint](https://docs.min.io/minio/baremetal/monitoring/healthcheck-probe.html), which we could also probe. That would mean adding an HTTP client to the test though.

Unrelated: the `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` appear to be deprecated in the `latest` build:
![image](https://user-images.githubusercontent.com/43503240/156562522-54466d2d-5baf-4939-831e-ca3e40bb8365.png)
