### ISSUE TITLE
AssetLoader: add `deleteById`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#801]
Add a `deleteById` method to the `AssetLoader` interface and all its implementors:

It should return the deleted `Asset` or `null` if that Asset does not exist. It should throw an `EdcPersistenceException` if anything goes wrong (e.g. a `CosmosException` happens, network error, unreachable service,...).
```java
public Asset deleteById(String assetId);
```

[Edit] updated/improved description

**Comment by algattik** [comment]
@paullatzelsperger what to do if the asset cannot be found? It might be better to make the method idempotent, hence also not return any value. (and not throw an exception if asset not found)

**Comment by paullatzelsperger** [comment]
ok, i should have been more precise. i updated the description.
