### ISSUE TITLE
ContractDefinitionStore: add `deleteById` method

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#802]
Add a `deleteById` method to the `ContractDefinitionStore` interface and all its implementors:

It should return the deleted `ContractDefinition` or `null` if not found and throw an `EdcPersistenceException` if anything goes wrong.

```java
public ContractDefinition deleteById(String definitionId);
```

_Note: this does not need to perform any higher-level checks e.g. whether the CD is used in an agreement. This will happen at the service level._

[edit] added "return null if not found" part

**Comment by ouphi** [comment]
@paullatzelsperger I assume that we want to return null if the ContractDefinition does not exist? Like in story #801 ?
