### ISSUE TITLE
DataManagementApi: add `ContractDefinitionService` and `ContractDefinitionTransformer`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#806]
For the implementation of the contract definition endpoint we need an `ContractDefinitionService` (and an `ContractDefinitionServiceImpl`) with roughly the following signature:
```java
public interface ContractDefinitionService {
  Asset findbyId(String contractDefinitionId);
  Collection<ContractDefinition> query(QuerySpec query);
  ContractDefinition delete(String contractDefinitionId);
  ContractDefinition create(ContractDefinition newDef);
}
```

In addition, there needs to be an `ContractDefinitionTransformer`, that converts an `ContractDefinition` into an `ContractDefinitionDto` and back. This depends on #779 

Important aspects:
- service must provide transactional consistency
- service must perform defensive checks before performing an operation, e.g. `delete`: must check first, whether a `ContractAgreement` already exists with the same ID, in which case it cannot be deleted.
- invoking the transformer is done by the controller, **not** the service.
- transformer does not perform any validation, it simply converts

**Comment by ndr-brt** [comment]
Started working on this, unfortunately it depends from #828, since currently `ContractDefinitionDto` contains policy ids, while `ContractDefinition` contains policy objects. So it's impossible to implement `ContractDefinitionDto` to `ContractDefinition` transformer.
