### ISSUE TITLE
DataManagementApi: add `PolicyService` and `PolicyTransformer`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#808]
For the implementation of the policy endpoint we need an `PolicyService` (and an `PolicyServiceImpl`) with roughly the following signature:
```java
public interface PolicyService {
  Policy findbyId(String policyId);
  Collection<Policy> query(QuerySpec query);
  Policy delete(String policyId);
  void create(Policy policy);
}
```

In addition, there needs to be an `PolicyTransformer`, that converts an `Policy` into a `PolicyDefinitionDto` and back. This depends on #779 

Important aspects:
- service must provide transactional consistency
- service must perform defensive checks before performing an operation:
  - `delete`: a `Policy` can only be removed if not yet referenced in a `ContractDefinition`
- invoking the transformer is done by the controller, **not** the service.
- transformer does not perform any validation, it simply converts
- depends on #803

**Comment by diegogomez-zf** [comment]
Hi, since I'm not listed as contributor. I confirm that I take this issue.
