### ISSUE TITLE
DataManagementApi: add `TransferProcessService` and `TransferProcessTransformer`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#809]
For the implementation of the transfer process endpoint we need an `TransferProcessService` (and an `TransferProcessServiceImpl`) with roughly the following signature:
```java
public interface TransferProcess {
  TransferProcess findbyId(String transferProcessId);
  Collection<TransferProcess> query(QuerySpec query);
  String getState(String transferProcessId);
  Result cancel(String transferProcessId);
  Result deprovision(String transferProcessId, String reason);
}
```

In addition, there needs to be an `TransferProcessTransformer`, that converts an `TransferProcess` into a `TransferProcessDto` and back. This depends on #779 

Important aspects:
- service must provide transactional consistency
- service must perform defensive checks before performing an operation:
  - `cancel`: must check first, whether a `TransferProcess` can be cancelled according to valid state transitions
  - `deprovision`: check whether a `TransferProcess` can be declined according to valid state transitions
- state transitions must be done through the `CommandQueue` mechanism and their `Result` only reflects the successful submission of the command
- invoking the transformer is done by the controller, **not** the service.
- transformer does not perform any validation, it simply converts

Depends on #859

**Comment by paullatzelsperger** [comment]
seems like #859 slipped through the cracks and must be implemented **before** this!

**Comment by algattik** [comment]
Discussion with Paul today regarding "converts an TransferProcess into a TransferProcessDto and back.": we agreed there's no need to convert back from that DTO to that entity.
