### ISSUE TITLE
Improve Launcher concept

### ISSUE THREAD

**Issue by beardyinc** [eclipse-dataspaceconnector/DataSpaceConnector#81]
- [x] Move out the runtime code (e.g. `ConnectorRuntime.java`) to the `core:bootstrap` module, make it overridable

- [x] introduce bill-of-material (BOM) build files, much like the IDS BOM or the Ion BOM
- [x] the launcher's `build.gradle.kts` then just references BOMs resulting in a very simplistic basic launcher

The upside of that is that we don't need to dupllicate the `*Runtime.java` files and a launcher becomes just a Gradle build file.

**Comment by beardyinc** [comment]
pull request #114

**Comment by MoritzKeppler** [comment]
@beardyinc guess we can close this issue, right?

**Comment by beardyinc** [comment]
yup, think so. PR #114  is already merged.

**Comment by EHJ-52n** [comment]
@paullatzelsperger @jimmarino @MoritzKeppler 
This change is not reflected in the documentation, e.g. [README.md](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector#launchers) still points to the [ConnectorRuntime.java](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/launchers/basic/src/main/java/org/eclipse/dataspaceconnector/runtime/ConnectorRuntime.java) file which is removed from the repository. At least, [github cannot find it anymore](https://github.com/search?q=org%3Aeclipse-dataspaceconnector+ConnectorRuntime.java). Hence, I ended up here.
So, please update the README.md.
