### ISSUE TITLE
DataPlaneFramework: Create DPF Selector

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#832]
## Description
We need a service which we'll call "DPF Selector" that contains a list of all the available DPF instances that a connector has access to.

## Requirements

- **Data Model:** every DPF is represented as a `DataPlaneInstance` with its name and metadata such as:
  - available `DataSource` implementations
  - available `DataSink` implementations
  - configuration (URL)

  As a starting point the API of that service should look something like this:
  ```java
  public interface DpfSelector {
     DataPlaneInstance select(DataRequest request, SelectionStrategy strategy);
  }
  ```

- **Storage:** those `DataPlaneInstances` are stored in a mutable `DpfSelectorStore` (provide in-mem implementation by default), so adding and removing is possible at runtime.

- **Selection algorithm:** the DPF Selector should also be able to use different _strategies_ for DPF selection, e.g. round-robin, select-first-matching, random, etc. Regardless of strategy the selector can only return DPFs that can handle the request.

## Deployment
The DPF Selector should be able to embedded in a connector runtime or standalone, e.g. as a K8S pod. This may influence how the control plane communicates with the selector (REST vs. Java SPI) and it may also influence the choice for a storage backend.

## Out of scope
In future developments we can collect dynamic metrics such as load average, number of transfers in progress, CPU utilization, etc. and report back to the selector who in turn updates the `DataPlaneInstance` in the store.

- [x] Create technical proposal #851
- [ ] Add minimal implementation #890 

[edit] added implementation PR

**Comment by MoritzKeppler** [comment]
Do we already have scenarios from one of the dataspaces where one connector needs to support multiple dataplanes?
<sub> Moritz Keppler <moritz.keppler@mercedes-benz.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by paullatzelsperger** [comment]
There is a requirement for a project MSFT is working on, where we want to show off multiple/different dataplanes.
