### ISSUE TITLE
Standardize EDC Setting Keys

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#84]
The EDC setting keys should be standardized and implement a namespace feature. Dot notation is used already, so we should probably reserve the first segment for that purpose. The issue is some settings use "dataspaceconnector" while others use "edc". For example:

public class CosmosTransferProcessStoreExtension implements ServiceExtension {

    @EdcSetting
    private static final String COSMOS_DBNAME_SETTING = "edc.cosmos.database.name";
    @EdcSetting
    private static final String COSMOS_PARTITION_KEY_SETTING = "dataspaceconnector.cosmos.partitionkey";
    private static final String DEFAULT_PARTITION_KEY = "dataspaceconnector";
    private static final String CONTAINER_NAME = "transferprocess";

----------------------
I would vote for brevity, and hence "edc".

**Comment by jimmarino** [comment]
@bscholtes1A did your PR solve this and can we close this issue out?

**Comment by bscholtes1A** [comment]
@jimmarino yeap, we can close it
