### ISSUE TITLE
Policy and Rule Evaluation Endpoints

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#857]
Track support for policy and rule HTTP endpoints as described in #855. 

A policy evaluation endpoint is an external service hosted outside the process boundaries of an EDC runtime that is responsible for evaluating a `Policy` in a given scope. The EDC runtime may communicate with that endpoint via HTTP, gRPC, or some other protocol.

This issue will track adding support for RESTful HTTP endpoints. EDC deployers will specify the following configuration to enable an endpoint:

1. A configuration key containing the policy scope with a value set to the endpoint URL (the URL scheme will be used to determine the protocol).
2. An API key per protocol.

If that configuration is present, policy evaluation for the given scope will be delegated to the endpoint.

**Comment by jimmarino** [comment]
A policy evaluation endpoint is an external service hosted outside the process boundaries of an EDC runtime that is responsible for evaluating a `Policy` in a given scope. The EDC runtime may communicate with that endpoint via HTTP, gRPC, or some other protocol.

This issue will track adding support for RESTful HTTP endpoints. EDC deployers will specify the following configuration to enable an endpoint:

1. A configuration key containing the policy scope with a value set to the endpoint URL (the URL scheme will be used to determine the protocol).
2. An API key per protocol.

If that configuration is present, policy evaluation for the given scope will be delegated to the endpoint.

**Comment by juliapampus** [comment]
When talking about PEPs, we should also consider structuring the policy engine according to use PAPs, PIPs, PXPs, PMPs and PDPs, shouldn't we?
