### ISSUE TITLE
Policy Enforcement Points (PEPs)

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspaceconnector/DataSpaceConnector#858]
Placeholder for Policy Enforcement Points (PEPs) support as described in #855.

**Comment by alexandrudanciu** [comment]
@jimmarino In literature on usage and access control the term policy decision point (PDP) is used for the step of evaluating policies. The abbreviation PEP is used for the concept of a policy enforcement point. Would it be possible to reuse the established naming for avoiding confusions?

**Comment by jimmarino** [comment]
> @jimmarino In literature on usage and access control the term policy decision point (PDP) is used for the step of evaluating policies. The abbreviation PEP is used for the concept of a policy enforcement point. Would it be possible to reuse the established naming for avoiding confusions?

Sure, I always conflate evaluation and enforcement. Updated the issue.
