### ISSUE TITLE
SQL: implement `PolicyStore`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#866]
An SQL-based implementation of the `PolicyStore` is needed. 

### Requirements
1. `save()`: implement upsert semantics
2. Querying: the query implementation must be flexible enough to accomodate  a `QuerySpec`.
2. Table Schema: serialize all related objects (Duty, Permission, ...) to JSON.
3. Indexing: queries will be targeting `Policy.id`.

_Please provide a written proposal for requirements 2 and 3 before beginning the implementation._

**This issue depends on #803**

- [x] Design Proposal: #920 
- [ ] Implementation (PR reference goes here)

**Comment by bcronin90** [comment]
Quick question about that: Is querying only required for the Policy.id parameter? Just want to make sure I understand the usage of the QuerySpec correctly here.

**Comment by paullatzelsperger** [comment]
I'd suggest keeping things simple for now, which means:
- `findAll(QuerySpec)` only uses the `offset` and `limit` properties
- `Permission`, `Prohibition` and `Duty` objects are stored as `varchar`, i.e. serialized JSON

At a later point we can add the following improvements:
- add caching to the `PolicyStore`
- `QuerySpec`: also use the `filterExpression`, `sortOrder` and `sortField` properties and either let the query hit the cache (using `Predicates`), or adopt the `Clause` API

**Comment by paullatzelsperger** [comment]
Implementation can be done after #930 as it will provide the interface
