### ISSUE TITLE
Data Plane Framework - Provider Data Push

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#871]
This is a child issue of #463. 

## Overview

The Data Plane Framework (DPF) should support two transfer directions:
1. client pull (sync): transfer is triggered by the consumer backend applications which query actively the data using their DPF.
2. provider push (async): once agreement request is successfully processed, the provider control plane sends a request to the DPF that triggers the data transfer from the provider data source to the consumer data destination. Data transfer can be finite or non-finite (event streaming).

Two kinds of API are therefore required within the DPF (each API should be registered on a separated context):
- a Public API used for client pull, which can be directly targeted by the backend applications,
- a Control API used for provided push which is only hit by the Control Plane. 

**The present issue only covers the asynchronous provider data push and the associated DPF Control API**, as Synchronous Data Pull has already been covered extensively in #585. 

## Requirement

- success of the artifact request directly triggers the data transfer, 
- DPF can be part of the Control Plane runtime (testing, samples...) or it can run as a separated runtime, thus the DPF should provide:
  - a Java API enabling to run the DPF directly from the Control Plane,
  - a REST API that can be hit remotely by the Control Plane through a dedicated client. 

## Design

The transfer orchestration belongs to the **Control Plane** runtime. All classes related to this orchestration are therefore placed in a dedicated extension `data-plane-transfer` which is separated from the `data-plane` module. 

The Provider Data Push mode is active for any `DataRequest` whose destination type is different from `HttpProxy`, which is reserved for Synchronous Data Pull (see #585 for more details). When the `DataRequest` is first received by the consumer Control Plane, it will first provision the data destination if needed (e.g. S3 bucket, Azure storage...), put the corresponding `DataAddress` in the `DataRequest` and finally send it to the provider Control Plane. 

The provider Control Plane will then map the `DataRequest` into `DataFlowRequest` (counterpart of the `DataRequest` in the DPF data model) and send this `DataFlowRequest` to the Control API exposed its DPF. The selection of the DPF instance is delegated to the DPF selector which is treated in a separated issue #832. We propose to rely on the existing `transfer-functions` extension for sending the `DataFlowRequest` to the DPF. 

The Control API of the DPF will then simply validate the received `DataFlowRequest` and, if valid, enqueue it in the `DataPlaneManager`. Note depending on the data source/destination combination some optimization of the data transfer are possible that avoids streaming the data through the DPF, which becomes crucial when dealing with massive data transfers. 

The whole sequence is depicted below:

![provider_push drawio](https://user-images.githubusercontent.com/88310985/157632226-aadc1a48-3e6f-44bc-9e04-acc9023f9ec1.png)

**Comment by bscholtes1A** [comment]
@paullatzelsperger @jimmarino @ndr-brt @algattik 
your kind review is welcomed here :)

**Comment by MoritzKeppler** [comment]
I propose to distinguish between a streaming like behavior, i.e. a data transfer process is kept open for a long time (regardless if it's technically a real streaming protocol or an ongoing access to a REST API), and a finite data transfer behavior.
In both cases a data transfer process gets started via the control plane. 
In the finite data transfer case the control plane will immediately trigger the dataplane after provision. In the streaming case the dataplane will get accessed/triggered by one of the participants in a separate call.

Push/Pull is independent from that. E.g. we could agree on "streaming" via push http. Means a consumer connector needs to provide a public http endpoint that can be accessed by a data provider. Or it is the other way round and a provider offers a public endpoint that can be called by a consumer whenever needed (case "access to a REST API on provider side").

Terms sync/async maybe misleading as there can be async steps (provisioning, data transfer) while the actual data transfer is done via a sync protocol (http).

Does that make sense?
<sub> Moritz Keppler <moritz.keppler@mercedes-benz.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
