### ISSUE TITLE
Data Plane Public API fails to map request HTTP method

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#879]
# Bug Report

## Describe the Bug
Data Plane public API, which is modeled by the `DataPlanePublicApiRequestFilter` class does not map properly the request HTTP method into the `DataFlowRequest`. Every request is mapped as a _GET_ regardless of the actual HTTP method used to call the DPF public API. 

During testing we observed that proper behavior is obtained when a random path is appended at the end of the url. Thus it seems that `ContainerRequestFilter` only fails to map the HTTP method when targeting the root path. 

### Expected Behavior
The HTTP verb of the request should be mapped into the `DataFlowRequest`.

### Observed Behavior
The HTTP _GET_ verb is always mapped into the `DataFlowRequest`, regardless of the actual HTTP method used in the request. 

## Steps to Reproduce
1. Send _POST_ request to the DPF public API, i.e. POST http://my-dpf-instance.com:9191/public
2. Inspect which verbs is mapped into the `DataFlowRequest`

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation
A possible approach would be to try replacing the current ContainerRequestFilter by a Jetty [AbstractHandler](https://www.programcreek.com/java-api-examples/?api=org.eclipse.jetty.server.handler.AbstractHandler). Not sure it will fix the issue though, should be tested.

**Comment by bscholtes1A** [comment]
FYI: @ndr-brt @florianrusch-zf

**Comment by MoritzKeppler** [comment]
What about replacing the filter by a normal controller impl having java methods for every HTTP Verb we like to support?
<sub> Moritz Keppler <moritz.keppler@mercedes-benz.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by bscholtes1A** [comment]
> What about replacing the filter by a normal controller impl having java methods for every HTTP Verb we like to support? Moritz Keppler [moritz.keppler@mercedes-benz.com](mailto:moritz.keppler@mercedes-benz.com), Daimler TSS GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md)

Note that we need to support any request body type (form, application json...) 
Is there an annotation saying that the endpoint can consume them all?
