### ISSUE TITLE
Data Plane Framework - Pass Path Information

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#881]
# Feature Request
The public dataplane api catches all incoming http calls but drops the path information before calling the actual service in the backend. Query params and http method get already passed properly.
Propose to append the path retrieved to the URL that is used to call the backend service.
We could also make this configurable (e.g. toggles for "pass http method", "pass query params", "pass path information", ...)

## Which Areas Would Be Affected?
DPF and maybe Assets

## Why Is the Feature Desired?
Integration of REST APIs like the one described by AAS https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShell-REST-API/Final-Draft
It should be possible to grant access to multiple endpoints / pathes via one EDC contract, e.g. grant access to a complete AAS.

## Solution Proposal
pass path information similar to how we pass query params today, e.g. just add path information retrieved in `DataPlanePublicApiRequestFilter` to the end of the `DataAddress` that is called on provider side.

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by MoritzKeppler** [comment]
@bscholtes1A

**Comment by dr-markus** [comment]
Are HTTP-Header already passed?
