### ISSUE TITLE
Express Access to REST API as Asset

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#882]
# Feature Request
Data is often shared via REST APIs that exist independent from a connector/IDS, an AAS e.g. https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShell-REST-API/Final-Draft
A connector in front of such an API can ensure, that any call is covered by a contract that describes the interactions allowed (http methods, endpoints, parameters).
We need a way to express that as a asset / contract (or a policy) and enforce the rules during data transfer.

## Which Areas Would Be Affected?
DPF, data management API, maybe policy handling

## Why Is the Feature Desired?
Integration of AAS, e.g. a asset / contract for access to "all submodels of type x from all shells"

## Solution Proposal
maybe a regex match to URLs?

## Type of Issue
new feature

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

related to #881

**Comment by jimmarino** [comment]
relates to #858

**Comment by MoritzKeppler** [comment]
`HttpDataSourceFactory` is implemented in a way that it partially overwrites values given in the `DataAddress` with values from `DataFlowRequest` properties (a list filled by the http call coming in `DataPlanePublicApiController`), especially the http path. But also the actual http method is taken from that list.

Propose to change it in a way, that the DataAddress always wins and just if a value is not defined there it is taken from the `DataFlowRequest` properties.
Advantages:
* improved security: caller cannot access any address accidentally
* covers some basic scenarios in http proxy behavior of DPF, e.g. "one Asset = one URL" and "Asset = all subpathes" etc. (improved solution will be available as soon as the DPF can evaluate policies on the call)

Propose to add the HTTP method to the `DataAddress` (optional) with Fallback to `GET`

What do you think @bscholtes1A @paullatzelsperger  @stefan-ettl ?

**Comment by bscholtes1A** [comment]
Hi @MoritzKeppler 

for the path I get it, and that's quite easy to put precedence in the code to the path coming from the `DataAddress`. 

However, for the method I am not sure what you mean. What if I call with a POST an API for which the `DataAddress` does not contain any verb?

**Comment by MoritzKeppler** [comment]
> 
> However, for the method I am not sure what you mean. What if I call with a POST an API for which the `DataAddress` does not contain any verb?

If DataAddress does not contain any Verb, POST would be used.
If DataAddress contains a verb, e.g. "GET", this verb would be used (alternativ: call will be rejected in case of mismatch)

**Comment by MoritzKeppler** [comment]
Result of alignment between @bscholtes1A  and me:
the decision if an aspect (body, http method, path, ...) is taken from the actual request is made explicit by toggles that can be set in the data address. The creation of the final http call made to retrieve the data stays in `HttpDataSourceFactory`. Factories for other type of data sources could be built in a similar way.

**Comment by MoritzKeppler** [comment]
We decided to merge #1079 as a short-term solution. Assume that the concept will get improved (e.g. via a PEP in the data plane) as part of the upcoming milestone.

**Comment by ndr-brt** [comment]
@MoritzKeppler seems that the purpose of this issue has been covered by the PR, can this be closed?
