### ISSUE TITLE
Failing Test: `DemoPushStreamTransferTest`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#889]
# Bug Report

## Describe the Bug
Sometimes the `DemoPushStreamTransferTest#verifyWsPushStreamFlow` test fails to complete within the specified time frame (1 minute), for example:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5538888562?check_suite_focus=true

### Expected Behavior
Test does not fail.

### Observed Behavior
_A clear and concise description of what happened instead._

## Steps to Reproduce
cannot be reproduced deterministically

## Context Information
happens during CI Unit tests

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

**Comment by ndr-brt** [comment]
I think I already fixed this in #831 because it often failed

**Comment by paullatzelsperger** [comment]
+1 on excising the entire ext!

**Comment by jimmarino** [comment]
I'm happy to axe this extension if there are no objections.

**Comment by ndr-brt** [comment]
no objections, it's a pity that this didn't happened before I passed half a day struggling with that test :D
