### ISSUE TITLE
Data Plane Framework - Functional implementation of event streaming

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#903]
This is a child issue of #463. 

## Overview

In #585 and #871, both client data pull and provider data push have been implemented within the DPF. The present issue focuses on streaming. more specifically, the objective is here to have a _functional_ implementation using the DPF as a media to share events from an event broker with the data consumers. The term _functional_ refers to the fact that scalability, delivery guarantee and ordering are not in scope of this first implementation. 

The possibility to provision a public event broker in the provider environment to which consumer will connect to will be covered later in a dedicated issue. 

## Requirement

- once data request is successfully processed, the provider Control Plane delegates the data transfer using the DPF Control API,
- DPF should be able to connect to a SSL-secured Kafka (EONA-X use-case) cluster from which events will be pulled,
- DPF must be able to push events to data consumer by leveraging on existing `DataSink` implementations,
- recovery (i.e. restart of the streaming process after a DPF crash) is not in scope of this issue as it is a more generic issue that does not only apply to streaming, covered by #941.
- scalability, delivery guarantee, ordering (...) are not in scope of this first implementation.

### Flow

The flow is very similar to finite data push (#871), as depicted below. 

![streaming_push drawio](https://user-images.githubusercontent.com/88310985/166213620-1945fbce-3658-46ec-b1c7-6a5eb4ec5f91.png)

Based on the data source type of the `DataFlowRequest` (e.g. Kafka, MQ...), the provider DPF creates a `DataSource` which consumes events from the event source (e.g. Kafka topic) and the `DataSink` pushes it to destination. 

### Persistence and recovery

By definition, streaming can implies that data transfer never actually finishes. In case of POD crash, Data Plane should be able to recover and restart automatically the streaming process. This implies to persist the `DataFlowRequest`, which is tracked separately in #941, as it applies also to other types of data transfers.

**Comment by newinnovations** [comment]
Very much interested in streaming with respect to the EDC. And thus in this issue. What I don’t understand is why data would/should stop streaming at the provider and then be transferred to the cloud like a file, blob or bucket for access by the consumer. That is how I understand your diagram. For me a real world scenario would be to transfer the actual data to the consumer (instead of to some external entity) and to “keep the data streaming“.

![edc-streaming](https://user-images.githubusercontent.com/8201694/166894313-0948421c-dfe3-4657-9a6d-c552f9f85009.png)

**Comment by bscholtes1A** [comment]
> Very much interested in streaming with respect to the EDC. And thus in this issue. What I don’t understand is why data would/should stop streaming at the provider and then be transferred to the cloud like a file, blob or bucket for access by the consumer. That is how I understand your diagram. For me a real world scenario would be to transfer the actual data to the consumer (instead of to some external entity) and to “keep the data streaming“.
> 
> ![edc-streaming](https://user-images.githubusercontent.com/8201694/166894313-0948421c-dfe3-4657-9a6d-c552f9f85009.png)

Hi @newinnovations 
sorry for the late reply. You are raising a very interesting point. Actually the "consumer streaming" part you are mentioning was something that we have already in mind but was not high-prio for our use-case. 

However, we can completely leverage on what we have implemented so far in the context of this issue and extend it so that we also continues the streaming on the consumer side. 

This will involves the implementation of an extension on consumer side that will receive events (probably this extension will be exposing an ingestion REST endpoint), and then publish these event to Kafka. 

Would you be ok to create an issue in the project to track this?

**Comment by newinnovations** [comment]
Created #1390
