### ISSUE TITLE
Confusion what the EndpointDataReferences.correlationId is about

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-dataspaceconnector/DataSpaceConnector#913]
# Bug Report

## Describe the Bug
I was confused today trying to figure out what exactly the `correlationId` is that @jimmarino pointed out in a discussion we had today regarding the controller's asynchronous callback regarding the dataplane connection information. After some debugging and hopping through the code for minutes, I finally saw that it is just the transfer process id.

### Observed Behavior
It is called `correlationId`, where someone who doesn't know the code doesn't know where it comes from or where it "correlates" to.

### Expected Behavior
Naming the attribute after what it is: `transferProcessId`.

**Comment by bscholtes1A** [comment]
Hi @florianrusch-zf 
this id correlation id is not necessarily the transfer process id. We can put anything as long as this enables to correlate with the data request, as this EndpointDataReference is received asynchronously. 

Here we should instead put the data request id in this correlation id. 

Note that this field is already renamed here: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/901

**Comment by jimmarino** [comment]
Closing this out per @bscholtes1A comment.
