### ISSUE TITLE
Provide Callback for Contract Negotiation/Agreement

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-dataspaceconnector/DataSpaceConnector#914]
# Feature Request

After the contract negotiation was initialised it could possibly take hours or even days until the provider side decide to approve, decline or send a counter offer. Therefore it's maybe a bad practise to have the client application regularly checking the current state of the negotiation (which for example would maybe implemented like a loop or some kind of cronjob or something else). 

Therefore we could maybe adopt like it is done within the dataplane framework and implement the possibility to receive a callback from the controller if the state of the negotiation changes.

## Which Areas Would Be Affected?
Contract Negotiation, Management API and currently still also the control api

## Why Is the Feature Desired?
We want to avoid unnecessary network traffic. If a company is conducting several hundred or even a thousand contract negotiations at the same time and checking the status of things every second, for example, then this could lead to a negative load on the network, which in turn could potentially result in poorer transmission rates for ongoing data transfers.

## Solution Proposal
We need a callback functionality as already implemented in the dataplane framework for sending the `EndpointDataReference` to the client on the consumer side.

## Type of Issue
New feature & improvement

## Checklist

- [ ] assigned appropriate label?
- [ ] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
This was also superseded by #1160
