### ISSUE TITLE
Improvement: `SqlContractDefinitionStore` implement filtering and sorting

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#915]
# Feature Request

The `SqlContractDefinitionStore` in its current implementation allows for querying with a `QuerySpec` but only takes the `offset` and `limit` properties. 

Now, also the `filterExpression`, `sortField` and `sortOrder` should be added to the query.

## Which Areas Would Be Affected?
- DataManagementAPI

## Why Is the Feature Desired?
to establish feature parity with all other data backends and implementations

## Solution Proposal
If possible wait for Issue #916 and have the query hit the cache using `Predicate`s, similar to the `InMemoryContractDefinitionStore`

_If that's not desirable/feasible_: 
implement the filtering directly in SQL: adopt the `Clause` interface that was originally developed for CosmosDB's SQL API, but can be re-used and ported to SQL.

## Type of Issue
Improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by ndr-brt** [comment]
This should be done for every postgresql store implementation

**Comment by paullatzelsperger** [comment]
FYI: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/discussions/1424

**Comment by paullatzelsperger** [comment]
Closing as it's a duplicate of #1432
