### ISSUE TITLE
Improvement: add cache to `SqlContractDefinitionStore`

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-dataspaceconnector/DataSpaceConnector#916]
# Feature Request

The `SqlContractDefinitionStore` should have a simple in-memory write-through cache to speed up access e.g. during contract offer generation. It will also simplify querying using a `QuerySpec` greatly as `Predicate`s can be used.

## Which Areas Would Be Affected?
- DataManagementApi
- Catalog request

## Why Is the Feature Desired?
It will greatly speed up read access to the store and make filtering by `QuerySpec` much simpler.

## Solution Proposal
add an `AtomicReference<Map<String, ContractDefinition>>` field which acts as cache

The behaviour should be as follows:
- on `save`/`update`/`delete` write to cache _and_ database. Write to DB first!
- on `find`/`findAll` hit cache

## Type of Issue
Improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by DominikPinsel** [comment]
I assume in the future it will be possible for two control-planes to run in parallel. If each of these connectors has it's own local cache there might be problems. For example if a contract definition is deleted but one control-plane has it still in its cache, it creates invalid contract offers for it. It might even create invalid contract agreements, based on the invalid contract offer.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>
