### ISSUE TITLE
Do not rely on `ParticipantUpdateNotification` IDS message for send `EndpointDataReference`

### ISSUE THREAD

**Issue by bscholtes1A** [eclipse-dataspaceconnector/DataSpaceConnector#918]
In the case of synchronous data transfer using the Data Plane (see #585 for more details), an `EndpointDataReference` object is generated by the provide Control Plane to the consumer Control Plane through the `RemoteMessageDispatcherRegistry`. 

A dedicated IDS 'Sender'/'Handler' was therefore created in order to be able to send and process these message. This also requires to have an IDS message that contains the actual `EndpointDataReference` object.

As a first approach, it was chosen to use the IDS `ParticipantUpdateNotification` message which was not yet used in our code base. 
However, based on recent discussions, it seems this is not the proper message to use for that purpose. 

This issue aims at defining which IDS should be used instead of `ParticipantUpdateNotification` and then perform the code update.

**Comment by bscholtes1A** [comment]
@juliapampus @ronjaquensel @MoritzKeppler 
asking for your kind suggestions here :)

**Comment by juliapampus** [comment]
Hi @bscholtes1A. Assuming I have understood everything correctly, based on [this](https://user-images.githubusercontent.com/88310985/157418442-da5cc5aa-6b54-42b3-b836-e4f0a3f46fcf.png) image, I would suggest the following IDS messages (that also have been outlined in some diagrams before, see [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/diagrams/transfer-messages-pull-async.png), [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/diagrams/transfer-messages-pull-sync.png) and [here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/docs/diagrams/transfer-messages-push-async.png)):

Step 0: Consumer sends an `ArtifactRequestMessage`. Provider directly responds with a 200 `RequestInProcessMessage` (as it will come back later).
Step 1: Provider sends a `NotificationMessage` with the EDR in the payload. Consumer directly responds with a 200 `MessageProcessedNotificationMessage` (as this part of the communication is finished). If the EDR is invalid, it responds with a 200 `RejectionMessage` (as always, when something goes wrong).
Steps 3-11 are non-IDS
Step 12 (maybe needs to be introduced): Provider sends an `ArtifactResponseMessage` to tell the Consumer that everything is finished. Consumer directly responds with a 200 `MessageProcessedNotificationMessage`.

All messages need to reference a `correlationMessage`:
- `ArtifactRequestMessage` id in `RequestInProcessMessage` (0)
- `ArtifactRequestMessage` id in `NotificationMessage` (1)
- `NotificationMessage` id in `MessageProcessedNotificationMessage`(1)
- `ArtifactRequestMessage` id in `ArtifactResponseMessage` (12)
- `ArtifactResponseMessage` id in `MessageProcessedNotificationMessage` (12)

I am not sure whether this is the correct flow as IDS multipart messages never covered an asynchronous flow. So e.g. the `ArtifactResponseMessage` is not of type request, therefore was never intended to be sent initially. Also, one could argue to send the EDR within an `ArtifactResponseMessage` to finish the sequence with a `NotificationMessage`. Or we could skip step 12 and not involve the control plane anymore. I guess this may depend on logging and tracing information the EDC should collect.

@ronjaquensel @MoritzKeppler @DominikPinsel wdyt?

**Comment by ronjaquensel** [comment]
@juliapampus I agree, the EDR should be sent in a Notification- or an ArtifactResponseMessage. For me, both sequences you described would be fine, but I think we can just skip step 12 and send the EDR directly in an ArtifactResponseMessage. As both Data Planes should know when the transfer is complete, I assume they could also signal the Control Plane, if this is required for e.g. tracing. So we could stick to the existing flow and just exchange the message type.
