### ISSUE TITLE
Improve folder structure

### ISSUE THREAD

**Issue by MoritzKeppler** [eclipse-dataspaceconnector/DataSpaceConnector#92]
We will have multiple associated services in our repo next to the connector, e.g. registration service for DID functionality.
I suggest to update the folder structure in a way that makes it easier to understand, which code belongs to which service.
Proposal:
```
/docs                       overall docs
/common                     shared libs, like the service loading framework
/services                   all services that form the connector ecosystem
e.g.
/services/connector         the connector itself :-)
/services/did-registration  registration service that crawls ION network
/services/catalog           ...
```
each service can have the following subfolders
```
.../core                core business functionality of the service
.../launcher            one or more bundles / launchers
.../scripts             e.g. helm charts
.../extensions          extensions that can get bundled
.../interfaces (or spi) extension interfaces
```
What do you think?
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by jimmarino** [comment]
+1

**Comment by DominikPinsel** [comment]
I think that's great idea. What do you think about restructuring the extension directory, too? 
It would be nice if the directory structure would show which part of the system is extended.

Examples:
- /filesystem/configuration-fs -> /configuration/filesystem
- /filesystem/vault-fs -> /vault/filesystem
- /aws/s3/provision -> /transfer/provision/aws/s3
- /aws/s3/s3-schema -> /schemas/aws/s3
- /azure/transfer-process-store-cosmos -> transfer/store/azure-cosmos
- /azure/vault -> /vault/azure

**Comment by DominikPinsel** [comment]
Would it be fine when I create a draft pull-request with these changes?
