### ISSUE TITLE
GitHub Packages not up-to-date

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#932]
# Bug Report

## Describe the Bug

GitHub snapshot packages **do not** reflect the state of the main branch.

### Expected Behavior

GitHub snapshot packages **do** reflect the state of the main branch.

### Observed Behavior

EndpointDataReferenceRequest no part of [core-spi package](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/packages/1189230).

## Steps to Reproduce

1. Download [core-spi package](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/packages/1189230)

Add auth to the `wget` call or just open the URL in the browser.
```
wget https://maven.pkg.github.com/eclipse-dataspaceconnector/DataSpaceConnector/org/eclipse/dataspaceconnector/core-spi/0.0.1-SNAPSHOT/core-spi-0.0.1-20220111.080052-1.jar
```

2. Check the JAR

<img src="https://user-images.githubusercontent.com/20866918/159236300-0cc65135-7ed8-467a-a59c-884c99a48383.png" width="400">

-> `/edr` package is missing

Screenshot from the `main` branch:
<img src="https://user-images.githubusercontent.com/20866918/159235195-791989fb-2c72-4683-b333-0b4ed5fcb440.png" width="250">

## Context Information

I ran into this problem while creating an application from the EDC packages only. Therefore, some of the packages already know the `EndpointDataReferenceRequest` class while others don't.
It might be the case that multiple EDC versions are currently stored in the repository with version number `0.0.1-SNAPSHOT`.

## Detailed Description

-

## Possible Implementation

-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DominikPinsel** [comment]
Closing this issue. Just saw that there might be something wrong with my local repository. Will check again.

**Comment by domreuter** [comment]
+1 As there is no public release on maven-central, i tried to use the github packages. They seem to be outdated as the last update was December 04, 2021
