### ISSUE TITLE
transport-spi uses same name/id as web-spi

### ISSUE THREAD

**Issue by lholthof** [eclipse-dataspaceconnector/DataSpaceConnector#945]
# Bug Report

## Describe the Bug
Maven artifact web-spi gets overwritten by transport-spi. Maybe some copy-paste error during refactoring.

### Expected Behavior
transport-spi should use its own MavenPublication artifact name/id

## Steps to Reproduce
Build project multiple times and check your local maven cache for web-spi-0.0.1-SNAPSHOT.jar. It sometimes contains transport-spi classes, depending on the build sequence.

## Context Information
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/spi/transport-spi/build.gradle.kts#L26

## Possible Implementation
gradle file should contain instead e.g.:
```
publishing {
    publications {
        create<MavenPublication>("transport-spi") {
            artifactId = "transport-spi"
            from(components["java"])
        }
    }
}

```

**Comment by jimmarino** [comment]
Thanks for pointing this out, it appears to be a cut-and-paste error. Does one of you want to submit a PR?

**Comment by danilomo** [comment]
@lholthof feel free to do this, if you would like to!

**Comment by lholthof** [comment]
@danilomo sorry for the delay, but finally my first contribution over here :-)
