### ISSUE TITLE
Provide S3-to-S3 transfer demo

### ISSUE THREAD

**Issue by MikhailGordienk** [eclipse-dataspaceconnector/DataSpaceConnector#96]
Would be helpful to have a complete demo where a consumer can request
a file from a provider and the transfer will be done completely on the AWS side.

This demo would show the case when resource provisioning is not necessary.

**Comment by MikhailGordienk** [comment]
PR: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/97

**Comment by bscholtes1A** [comment]
@jimmarino I guess this one can closed as well
