### ISSUE TITLE
Wrap read accesses in a transaction on api services

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#966]
# Feature Request

Not only the "write operations" should be wrapped with a `TransactionContext.execute()` call on api services, but also read ones

## Which Areas Would Be Affected?
Data management API.
Classes:
`AssetService`
`ContractAgreementService`
`ContractDefinitionService`
`ContractNegotiationService`
`PolicyService`
`TransferProcessService`

## Why Is the Feature Desired?
@paullatzelsperger 
> all read access in services should be wrapped in a transaction, even if there is just one store or one call involved. E.g. we may want to change the transaction isolation level later, to guard against race conditions in clustered environments (=DB write locks, thanks @algattik for the hint).

## Solution Proposal
Wrap all the read calls with the transaction. Probably better to wait until the transaction context execute with return will be implemented ( #968 )

## Type of Issue
improvement

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
I extracted the functionality from PR #950 (relates to #865) into a separate PR #968

**Comment by ndr-brt** [comment]
already done in #957
