### ISSUE TITLE
DataManagementApi: add ContractAgreementService and ContractAgreementTransformer

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#969]
For the implementation of the contract negotiation endpoint we need an `ContractAgreementService` (and an `ContractAgreementServiceImpl`) with roughly the following signature:

```java
public interface ContractAgreementService {
  ContractAgreement findbyId(String contractAgreementId);
  Collection<ContractAgreement> query(QuerySpec query);
}
```
In addition, there needs to be an `ContractAgreementTransformer`, that converts a ContractAgreement into a `ContractAgreementDto` 

Important aspects:

* service must provide transactional consistency
* service must perform defensive checks before performing an operation:
* invoking the transformer is done by the controller, not the service.
* transformer does not perform any validation, it simply converts

**Comment by paullatzelsperger** [comment]
depends on #1008
