### ISSUE TITLE
Remove `contractOffer` with `contractOfferId` on `ContractOfferRequest`

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-dataspaceconnector/DataSpaceConnector#985]
# Feature Request

Currently, to start a negotiation, a complete `ContractOffer` entity is requested into the `ContractOfferRequest` object.
We should rely on the `catalog`, in particular on the `QueryEngine` to get the contract offer instance and pass the id only.

## Which Areas Would Be Affected?
_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?
This will fix a problem existent in the `ContractNegotiationApi`, since at the moment (ref #957)
> The NegotiationInitiateRequestDto contains an offerId, while the ContractOfferRequest in which it is transformed contain a full ContractOffer object. For the moment I created it with a ContractOffer that has only the id, but's obvious that we need a better process.

## Solution Proposal
Replace `contractOffer` with `contractOfferId` in `ContractOfferRequest` and use `QueryEngine` to retrieve the full entity

## Type of Issue
improvement

**Comment by juliapampus** [comment]
How would you start a negotiation with a contract content that is not identically with the queried contract offer? A missing alignment with the API should maybe be solved there, not in the basic negotiation logic. WDYT @jimmarino and @ronjaquensel?

**Comment by paullatzelsperger** [comment]
@juliapampus the fundamental problem is that in order to initiate a negotiation, consumers need to provide the full asset and policy objects, where the respective _id's_ would be sufficient, at least from a functional perspective. 
To that point, AFAIK providers currently only use the asset id to check whether that particular asset is still covered by the referenced contract definition.

**Comment by juliapampus** [comment]
@paullatzelsperger From a functional perspective yes, but not from a general conceptual perspective. That the provider currently only checks the target id, doesn't mean that, in the end, this is the whole validation process. I agree that the assetId as the target should be sufficient, I already stumbled across this, but nevertheless a user should have the possibility to initiate the negotiation with custom policy content.

**Comment by paullatzelsperger** [comment]
@juliapampus those things don't need to be mutually exclusive: we could allow sparsely populated `Asset`/`Policy` objects, where only the ID is filled out, which would mean "no custom policy". Then, when a custom policy _should indeed be used_, we just fill out the entire `ContractOffer.policy` object. WDYT?

**Comment by juliapampus** [comment]
@paullatzelsperger Sounds good.
